# -*- coding: utf-8 -*-
Q = []

Q.append({
"q": "In the classic 'counting inversions' problem solved via modified merge sort, an inversion is a pair (i,j) with i&lt;j and A[i]&gt;A[j]. During the MERGE step, when an element from the right subarray is copied because it's smaller than the current left element, how many new inversions does this single event account for, and why?",
"opts": ["The number of remaining (uncopied) elements in the left subarray, because each of those left elements is greater than the copied right element and appears earlier in the array", "Exactly one inversion, corresponding to the single comparison just made", "The total size of the right subarray, because all right elements are assumed smaller", "Zero, since inversions are only counted after the merge completes, not during it"],
"ans": 0,
"exp": "When a right-subarray element R[j] is copied ahead of the remaining left-subarray elements, every one of those remaining left elements L[i], L[i+1], ..., L[end] is (a) positioned before R[j] in the original array's relative order and (b) greater than R[j] (since the left subarray is sorted and R[j] was smaller than the current left element, hence smaller than all subsequent ones too) — so each remaining left element forms an inversion with R[j]. This is the crucial insight that lets inversion-counting piggyback on merge sort's Θ(n log n) structure. (B) drastically undercounts; the trick's entire value is that ONE copy operation can resolve MANY inversions in O(1) additional work by just adding a count, not enumerating each pair individually. (C) incorrectly assumes ALL right elements are smaller than ALL left elements, which isn't given by a single comparison. (D) is wrong; the counting must happen precisely during the merge, using the invariant about sorted subarrays, or the Θ(n log n) efficiency is lost."
})

Q.append({
"q": "What is the overall time complexity of the inversion-counting algorithm based on modified merge sort, and how does it compare to the brute-force O(n&sup2;) pairwise-comparison approach?",
"opts": ["Θ(n log n); strictly better than the brute-force O(n&sup2;) approach for large n", "Θ(n&sup2;); identical to brute force since every pair must still be considered eventually", "Θ(n); better than brute force because merging is a single linear pass", "Θ(log n); because inversions only depend on the recursion depth"],
"ans": 0,
"exp": "The modified merge sort retains merge sort's exact recurrence T(n) = 2T(n/2) + Θ(n) (the O(1) extra work per copy to increment the inversion counter doesn't change the asymptotic merge cost), giving Θ(n log n) overall — a substantial improvement over the O(n&sup2;) brute-force approach that explicitly checks every pair. (B) incorrectly assumes that because the concept 'inversions' is about pairs, the algorithm must inspect pairs individually — but the merge-based trick avoids this via the bulk-counting insight. (C) underestimates the true complexity; a single merge pass is Θ(n), but there are Θ(log n) levels of merging in total, not just one merge. (D) misunderstands the recurrence entirely; recursion depth alone doesn't determine total work when there's linear work performed at every level."
})

Q.append({
"q": "Consider the D&C algorithm for finding both the maximum AND minimum of an array simultaneously by comparing elements in pairs and recursing. What is the tight bound on the number of comparisons, and how does it beat the naive 2n&minus;2 approach (separate max and min scans)?",
"opts": ["&lceil;3n/2&rceil; &minus; 2 comparisons, achieved by comparing elements pairwise first and only comparing each pair's winner to the running max and loser to the running min", "n&sup2; comparisons, because every element must be compared against every other", "n log n comparisons, matching a general D&C recurrence with a log factor", "2n comparisons; the D&C approach doesn't actually improve on the naive method"],
"ans": 0,
"exp": "The tournament-style approach processes elements in pairs: 1 comparison per pair to find the pair's local max and min (n/2 comparisons for n/2 pairs), then compares each pair's max against the running overall max and each pair's min against the running overall min (2 more comparisons per pair beyond the first), totaling &lceil;3n/2&rceil; &minus; 2 in the tight analysis — beating the naive approach's 2n&minus;2 (which separately scans for max, using n&minus;1 comparisons, and min, using another n&minus;1). (B) wildly overestimates; this problem does not require all-pairs comparison. (C) invents a log factor that doesn't apply; this is a linear-comparison-count problem, not one governed by a recursive divide that changes the comparison count by a logarithmic factor in this particular formulation (the 3n/2 bound stands regardless of how the recursion is structured, as it's proven via a general comparison-counting/adversary argument). (D) is factually wrong; the whole point of this classical example is that the smarter pairing strategy DOES reduce the comparison count below 2n&minus;2."
})

Q.append({
"q": "In the 'skyline problem' (merging building silhouettes) solved via D&C, two skylines of sizes m and n are merged in O(m+n) time by a linear sweep. What is the overall recurrence and complexity for n buildings, assuming an even split at each level?",
"opts": ["T(n) = 2T(n/2) + Θ(n) = Θ(n log n)", "T(n) = 2T(n/2) + Θ(n&sup2;) = Θ(n&sup2;)", "T(n) = T(n/2) + Θ(n) = Θ(n)", "T(n) = 2T(n/2) + Θ(log n) = Θ(n)"],
"ans": 0,
"exp": "Splitting n buildings into two halves and merging their resulting skylines in linear time (via a coordinated sweep comparing heights at overlapping x-ranges) gives the classic merge-sort-shaped recurrence T(n) = 2T(n/2) + Θ(n) = Θ(n log n) by Master theorem Case 2. (B) drastically overstates the merge cost; the linear-sweep merge is specifically designed to avoid quadratic behavior by processing critical x-coordinates in sorted order rather than comparing all pairs of edges. (C) incorrectly halves the number of recursive calls; the skyline problem genuinely needs both halves solved and then merged, not just one. (D) understates the merge cost to Θ(log n), which is far too little work to correctly merge two silhouettes of total size n — this would only be plausible if the merge step didn't have to examine each building's contribution."
})

Q.append({
"q": "A poorly designed D&C algorithm for computing the sum of an array recurses as SUM(A, 1, n) = SUM(A, 1, n&minus;1) + A[n]. What recurrence does this describe, and is it truly 'divide-and-conquer'?",
"opts": ["T(n) = T(n&minus;1) + Θ(1) = Θ(n); this is decrease-by-one recursion, not true divide-and-conquer, since the problem size shrinks by a constant, not a fraction", "T(n) = 2T(n/2) + Θ(1) = Θ(n); this is legitimate D&C with balanced splitting", "T(n) = T(n/2) + Θ(1) = Θ(log n); this is an efficient D&C solution", "T(n) = T(n&minus;1) + Θ(n) = Θ(n&sup2;); this is inefficient D&C"],
"ans": 0,
"exp": "This recurrence peels off one element per call, giving T(n) = T(n&minus;1) + Θ(1), which unrolls to Θ(n) — asymptotically no worse than a simple loop, but it is 'decrease-and-conquer' (reducing by a constant amount), not divide-and-conquer in the CLRS sense (which specifically involves splitting into smaller-by-a-fraction subproblems, like n/2). This distinction matters conceptually even though the complexity here happens to match a simple linear scan. (B) and (C) incorrectly claim a halving recursion that isn't present in the given pseudocode — the problem explicitly shows SUM(A,1,n&minus;1), a decrement, not SUM(A,1,n/2), a division. (D) incorrectly attributes Θ(n) work per call when only Θ(1) work (the addition of A[n]) happens outside the recursive call."
})

Q.append({
"q": "For the recurrence T(n) = 7T(n/3) + n&sup2;, which Master theorem case applies, and what is T(n)?",
"opts": ["Case 3: Θ(n&sup2;), since f(n)=n&sup2; grows polynomially faster than n<sup>log&#8323;7</sup>&asymp;n<sup>1.77</sup>, and the regularity condition holds", "Case 1: Θ(n<sup>log&#8323;7</sup>), since the recursive term always dominates when a&gt;1", "Case 2: Θ(n&sup2; log n), since the exponents are 'close enough'", "The Master theorem does not apply because 7 is not a power of the base 3"],
"ans": 0,
"exp": "a=7, b=3, so n<sup>log&#8323;7</sup> &asymp; n<sup>1.771</sup>. Since f(n)=n&sup2; is polynomially larger (n&sup2; = &Omega;(n<sup>1.771+&epsilon;</sup>) for small &epsilon;), and the regularity condition a&middot;f(n/b) = 7&middot;(n/3)&sup2; = (7/9)n&sup2; &le; c&middot;n&sup2; holds for c=7/9&lt;1, this is Case 3, giving Θ(n&sup2;). (B) misapplies Case 1 as a blanket rule; Case 1 specifically requires f(n) to be polynomially SMALLER than n<sup>log_b a</sup>, which is false here since n&sup2; is larger. (C) misapplies Case 2, which requires the two functions to match (not merely be 'close'); 2 and 1.771 differing by roughly 0.23 is NOT within the same polynomial class in the Master theorem's precise sense — the theorem provides an exact test, not a fuzzy proximity judgment. (D) is a fabricated restriction; a need not be a power of b for the Master theorem to apply."
})

Q.append({
"q": "What is the output and time complexity of applying the D&C paradigm to evaluate a polynomial of degree n&minus;1 at a single point x using Horner's rule versus a naive term-by-term approach?",
"opts": ["Horner's rule: Θ(n) multiplications via nested evaluation (((a&#8345;x+a<sub>n-1</sub>)x+...)x+a&#8320;); naive term-by-term (computing each x&#7496; separately): Θ(n&sup2;) multiplications without a shared power ladder", "Both approaches are Θ(n log n) since polynomial evaluation always requires a D&C-based FFT-like structure", "Horner's rule is Θ(n&sup2;) because of the nested parentheses; naive is Θ(n)", "Both are Θ(n) since only n coefficients need to be touched regardless of method"],
"ans": 0,
"exp": "Horner's rule restructures the polynomial to require exactly n&minus;1 multiplications and n&minus;1 additions via nested evaluation, giving Θ(n) — this is not literally a recursive D&C algorithm but is often taught alongside D&C evaluation strategies as an efficient alternative and building block for polynomial-related D&C algorithms (like the FFT). The naive approach recomputes each power x&#7496; independently (e.g., via repeated multiplication) without reusing prior work, costing Θ(i) per term and summing to Θ(n&sup2;) overall. (B) incorrectly asserts that O(n log n) FFT-style evaluation is the ONLY way to evaluate a polynomial; single-point evaluation via Horner's rule is a distinct and much simpler Θ(n) technique, unrelated to multi-point FFT evaluation. (C) has the complexities backwards. (D) ignores that the two approaches genuinely differ in complexity because the naive approach fails to share/reuse partial power computations."
})

Q.append({
"q": "Consider T(n) = &radic;2&middot;T(n/2) + log n, where a=&radic;2&gt;1. What is n<sup>log_b a</sup>, and which Master theorem case applies?",
"opts": ["n<sup>log&#8322;&radic;2</sup> = n<sup>0.5</sup>; since f(n)=log n = O(n<sup>0.5&minus;&epsilon;</sup>) for a suitable small &epsilon;&gt;0, f(n) IS polynomially smaller than n<sup>0.5</sup>, so Case 1 applies, giving T(n)=Θ(n<sup>0.5</sup>)", "n<sup>log&#8322;&radic;2</sup> = n<sup>0.5</sup>; log n cannot be polynomially smaller than any power of n, so this falls into a genuine Master theorem gap requiring Akra&ndash;Bazzi", "This is Case 2, since log n and n<sup>0.5</sup> are 'close enough' by convention", "The recurrence is invalid because a must be an integer for the Master theorem to apply"],
"ans": 0,
"exp": "a=&radic;2, b=2, so n<sup>log_b a</sup> = n<sup>log&#8322;&radic;2</sup> = n<sup>0.5</sup>. The key test for Case 1 is whether f(n) = O(n<sup>log_b a &minus; &epsilon;</sup>) for SOME constant &epsilon;&gt;0 — and log n indeed satisfies log n = O(n<sup>0.5&minus;&epsilon;</sup>) for, say, &epsilon;=0.4 (since log n grows slower than n<sup>0.1</sup>, let alone n<sup>0.5</sup>), so Case 1 genuinely applies here, giving T(n) = Θ(n<sup>0.5</sup>). This question specifically tests the common student overreaction of assuming 'any log n term automatically breaks the Master theorem' — that's only true when f(n) sits in the polynomial GAP between being smaller and being of the exact matching order (as in the earlier n/log n example), not whenever a logarithm appears at all. (B) is the trap: students pattern-match 'log' to 'special case / gap' without actually checking whether the polynomial-gap condition for Case 1 is satisfied — here it clearly is. (C) misapplies Case 2, which requires f(n)=Θ(n<sup>log_b a</sup>) exactly (within possible log-factor extensions), not vague 'closeness'. (D) is a fabricated restriction; irrational values of a are perfectly valid, as long as the resulting asymptotic comparisons can be carried out."
})

Q.append({
"q": "A student incorrectly claims that T(n) = 2T(n/2) + n/2 solves to a DIFFERENT complexity class than T(n) = 2T(n/2) + n. Evaluate this claim.",
"opts": ["False — both solve to Θ(n log n); constant multiplicative factors on f(n) never change the Master theorem's resulting Θ-class", "True — n/2 is smaller than n, so the first recurrence is Θ(n) while the second is Θ(n log n)", "True — the first is Θ(n log n) while the second is Θ(n&sup2;) since whole-number coefficients push it to a higher case", "False — both are Θ(n&sup2;) because doubling recursive calls always squares the complexity"],
"ans": 0,
"exp": "Θ-notation absorbs constant factors: f(n) = n/2 = Θ(n), so despite the surface-level difference in the coefficient, T(n) = 2T(n/2) + Θ(n) in BOTH cases, and both solve identically to Θ(n log n) by Case 2. This tests whether students understand that Θ(n) and Θ(n/2) are literally the same asymptotic class, not different ones — a very common student misconception is to treat a constant-factor change in the driving function as altering which Master theorem case applies. (B) and (C) fall for exactly this misconception, incorrectly treating n/2 as asymptotically distinct from n. (D) is unrelated nonsense with no mathematical basis; 'doubling recursive calls' doesn't generically square complexity — that depends entirely on the base b and the driving function, per the Master theorem."
})

Q.append({
"q": "For the D&C convex hull algorithm that splits points by x-coordinate, recursively finds hulls of each half, then merges via finding upper and lower tangent lines in O(n) time, what is the overall complexity, and what dominates it in practice (after an initial sort)?",
"opts": ["Θ(n log n) overall; dominated by the initial Θ(n log n) sort by x-coordinate, since the recursive merging itself is Θ(n log n) via T(n)=2T(n/2)+Θ(n)", "Θ(n&sup2;) overall; dominated by an O(n) tangent-finding step performed naively at every possible pair of points", "Θ(n) overall; the D&C structure eliminates the need for any sorting", "Θ(n log&sup2; n) overall; each merge step requires an additional log n factor for tangent-line binary search"],
"ans": 0,
"exp": "After an initial Θ(n log n) sort by x-coordinate (needed once, not per recursive level), the D&C merge step (finding the upper and lower tangents connecting two hulls) can be done in O(n) time with careful pointer-walking, giving T(n) = 2T(n/2) + Θ(n) = Θ(n log n) for the recursive part — and since the sort is also Θ(n log n), the two combine (not multiply) to remain Θ(n log n) overall. (B) incorrectly assumes a naive O(n&sup2;) tangent search; the whole point of the efficient D&C convex hull algorithm is avoiding this via a smarter walking technique. (C) is false; sorting by x-coordinate is a necessary prerequisite step for this specific divide strategy to make geometric sense (so the 'left half'/'right half' split is spatially meaningful), and it cannot be skipped. (D) fabricates an unnecessary extra log factor; well-known implementations achieve the O(n) merge without needing an internal binary search over tangent candidates."
})

Q.append({
"q": "In tournament-style D&C algorithms for finding the second-largest element among n elements (using a single-elimination tournament followed by re-examining only elements the winner directly beat), what is the total comparison count, and how does it improve on the naive 2n&minus;3 approach (find max, then find max excluding it)?",
"opts": ["n + &lceil;log&#8322;n&rceil; &minus; 2 comparisons: n&minus;1 for the tournament to find the max, plus &lceil;log&#8322;n&rceil;&minus;1 more among the &le;&lceil;log&#8322;n&rceil; elements the max directly defeated", "2n&minus;2 comparisons, identical to naively finding max then min", "n&sup2;/2 comparisons, since every pair must eventually be compared in a tournament bracket", "log&sup2;n comparisons, since tournaments are inherently logarithmic in every dimension"],
"ans": 0,
"exp": "A single-elimination tournament to find the overall maximum takes exactly n&minus;1 comparisons (each comparison eliminates exactly one contender). The key insight: the second-largest element MUST have lost directly to the overall maximum at some round (since it beat everyone else it faced along the way but couldn't beat the eventual champion), and the maximum played at most &lceil;log&#8322;n&rceil; matches, so there are at most &lceil;log&#8322;n&rceil; candidates for second place — finding the best among them takes &lceil;log&#8322;n&rceil;&minus;1 more comparisons via another mini-tournament, giving the improved total of n + &lceil;log&#8322;n&rceil; &minus; 2, strictly better than the naive 2n&minus;3 for n &gt; a small constant. (B) restates the naive approach's complexity, missing the clever tournament-tracking optimization entirely. (C) drastically overcounts; a well-run tournament never requires quadratic comparisons since half the field is eliminated at each round. (D) is a fabricated bound with no derivation; log&sup2;n is not achievable here since finding the max ALONE already requires a linear (n&minus;1) number of comparisons in a comparison-based model."
})

Q.append({
"q": "For merge sort applied to a LINKED LIST (rather than an array), what critical difference in the divide step changes compared to array-based merge sort, and why doesn't this change the overall Θ(n log n) complexity?",
"opts": ["Finding the middle of a linked list to split it requires an O(n) traversal (e.g., via a slow/fast pointer technique) rather than O(1) index arithmetic, but this Θ(n) cost per level is already subsumed by the existing Θ(n) merge cost at that level, so the total remains Θ(n log n)", "Linked-list merge sort is actually Θ(n&sup2;) because pointers cannot be indexed in constant time at all", "The divide step becomes free (Θ(1)) since linked lists don't require finding a midpoint", "Linked-list merge sort requires converting to an array first, adding an unavoidable Θ(n log n) overhead on top of the normal algorithm"],
"ans": 0,
"exp": "In an array, computing the midpoint index is O(1) arithmetic, but in a singly linked list, you must physically traverse to find the middle node (commonly via the slow/fast, or 'tortoise and hare,' pointer technique), which is an O(n) operation. However, since the merge step at each level of recursion is ALSO already Θ(n), adding another Θ(n) find-the-middle step per level doesn't change the per-level total beyond a constant factor — so the overall complexity remains Θ(n log n), a subtle but important point about how extra linear-time steps can be 'absorbed' without changing the recurrence's Θ-class. (B) is false; this reflects a misunderstanding of what actually changes — the complexity class is preserved, not degraded to quadratic. (C) is wrong; finding the midpoint is not free for linked lists, unlike arrays. (D) is a fabricated and unnecessary requirement; well-implemented linked-list merge sort operates directly on the list structure without ever converting to an array."
})

Q.append({
"q": "A recursive D&C algorithm for matrix transposition splits an n&times;n matrix into four (n/2)&times;(n/2) quadrants, recursively transposes each quadrant, then swaps the (already-transposed) off-diagonal quadrants. What is the recurrence, and what is a subtle correctness requirement for the swap step?",
"opts": ["T(n) = 4T(n/2) + Θ(n&sup2;) = Θ(n&sup2; log n) if implemented naively with an explicit swap-copy, but the swap of two already-transposed off-diagonal blocks can actually be done via in-place pointer/index swapping in Θ(1) 'bookkeeping' if the algorithm is designed carefully, giving Θ(n&sup2;) overall; the requirement is that recursive transposition must happen BEFORE the block swap, not after, or the wrong elements get swapped", "T(n) = 4T(n/2) + Θ(1) = Θ(n&sup2;) always, with no ordering requirement between transposition and swapping", "T(n) = T(n/2) + Θ(n&sup2;) = Θ(n&sup2;), since only one quadrant needs recursive processing", "T(n) = 4T(n/2) + Θ(n&sup3;) = Θ(n&sup3;), matching naive matrix multiplication's complexity by coincidence"],
"ans": 0,
"exp": "Transposing an n&times;n matrix inherently touches Θ(n&sup2;) elements, so the theoretically optimal complexity is Θ(n&sup2;) — achieved if the swap of the two off-diagonal quadrants (after each is individually transposed) is done efficiently rather than with wasteful extra copying, giving T(n) = 4T(n/2) + Θ(n&sup2;/4)-ish work that still totals Θ(n&sup2;) via the Master theorem's Case 1 boundary reasoning (careful accounting shows the geometric sum of Θ(n&sup2;) work across levels converges to Θ(n&sup2;), not Θ(n&sup2; log n), when implemented with in-place swaps). The subtle correctness point: each off-diagonal quadrant must be fully transposed internally BEFORE being swapped into its new position, otherwise you'd be swapping un-transposed data into the wrong place, corrupting the result. (B) incorrectly claims Θ(1) combine work, which cannot be right since swapping two (n/2)&times;(n/2) blocks inherently touches Θ(n&sup2;) elements. (C) incorrectly reduces to only one recursive call; transposition must recursively handle all four quadrants (two diagonal ones in place, two off-diagonal ones that get swapped). (D) fabricates a cubic complexity with no justification; transposition never requires more than touching each element a constant number of times."
})

Q.append({
"q": "Which statement correctly distinguishes 'divide-and-conquer' from 'dynamic programming' as paradigms, based on how each handles subproblems?",
"opts": ["D&C assumes subproblems are independent (non-overlapping), so results aren't cached; DP exploits overlapping subproblems and caches results (memoization/tabulation) to avoid redundant recomputation", "D&C always uses more memory than DP because it doesn't share subproblem solutions", "DP never uses recursion, only iteration, while D&C is purely recursive", "D&C and DP are identical paradigms with only naming differences from different textbook traditions"],
"ans": 0,
"exp": "The defining distinction (as CLRS emphasizes in the DP chapter's introduction) is that D&C algorithms like merge sort or quicksort partition into independent subproblems whose solutions don't overlap, so there is nothing to cache or reuse — while DP problems (like matrix-chain multiplication or Fibonacci) have overlapping subproblems, where naive recursion would redundantly recompute the same subproblem many times, motivating memoization (top-down caching) or tabulation (bottom-up table-filling) to achieve efficiency. (B) is not a defining or generally true characteristic; memory usage depends on the specific algorithm and problem, not the paradigm label itself. (C) is false; DP frequently uses recursion too (memoized/top-down DP is explicitly recursive), and the recursion-vs-iteration axis is orthogonal to the D&C-vs-DP distinction. (D) is false and elides an important conceptual distinction that CLRS explicitly draws out, precisely because failing to recognize overlapping subproblems and using naive D&C-style recursion (like naive Fibonacci) leads to exponential blowup where DP would give polynomial time."
})

Q.append({
"q": "For the Master theorem, why is the 'regularity condition' (a&middot;f(n/b) &le; c&middot;f(n) for some c&lt;1 and sufficiently large n) specifically required for Case 3 but not for Cases 1 or 2?",
"opts": ["Case 3 involves f(n) dominating the recursive term, and without the regularity condition, f(n) could oscillate or grow too irregularly across recursive levels such that the sum of costs across all levels doesn't actually converge to being dominated by the top level's cost (unlike Cases 1 and 2, where the polynomial comparison alone is sufficient due to the structure of geometric sums)", "The regularity condition is actually required for all three cases equally; it's just often omitted from casual statements of Cases 1 and 2 for brevity", "Case 3 requires it because a must be irrational in that case, and the condition compensates for rounding errors", "There is no real mathematical reason; it's a historical artifact from how the theorem was first published, not a technical necessity"],
"ans": 0,
"exp": "In Case 3, f(n) dominates, so intuitively the total cost should be Θ(f(n)) (dominated by the root's cost) — but this requires that the cost doesn't 'blow up' when descending into subproblems, i.e., that a&middot;f(n/b) (the total f-cost one level down) is boundedly smaller than f(n) itself by a constant factor c&lt;1; without this, pathological f(n) could cause the recursive levels to sum to more than Θ(f(n)), invalidating the clean 'top level dominates' conclusion. In Cases 1 and 2, the polynomial/exact-match comparison between f(n) and n<sup>log_b a</sup> is sufficient on its own because the underlying geometric series argument (either growing or staying constant across levels) works out without needing this extra regularity guarantee — the mathematics of those cases is more forgiving. (B) is incorrect; the standard CLRS statement of the Master theorem genuinely does not require regularity for Cases 1 and 2. (C) is a fabricated and nonsensical justification involving irrational numbers with no basis in the actual theorem. (D) dismisses a real mathematical necessity as a mere historical accident, which is false — the condition is essential to the proof's correctness for Case 3."
})

Q.append({
"q": "Consider a flawed 'proof' that P = NP using divide-and-conquer: 'Any NP problem of size n can be divided into 2 subproblems of size n/2, solved recursively, and combined in polynomial time, so by the Master theorem it runs in polynomial time.' What is the fundamental flaw?",
"opts": ["The claim that ANY NP problem can be divided into 2 independent half-size subproblems that can be combined in polynomial time is simply false for problems believed to be NP-hard; the Master theorem is a tool for solving KNOWN correct recurrences, not for establishing that such a decomposition exists in the first place", "The Master theorem only works for sorting algorithms, so it cannot be applied to general NP problems at all", "The flaw is a computational one: the Master theorem's case analysis was done incorrectly, not the underlying premise", "There is no flaw; this is actually a valid proof technique that complexity theorists have overlooked"],
"ans": 0,
"exp": "This question tests conceptual understanding of what the Master theorem actually proves: it solves a recurrence T(n) = aT(n/b) + f(n) GIVEN that such a recurrence correctly models an algorithm — it says nothing about whether a valid, correct, polynomial-time-combinable decomposition into independent half-size subproblems actually EXISTS for a given problem. For NP-hard problems (like 3-SAT or Hamiltonian cycle, believed not to have polynomial-time algorithms), no one has found such a decomposition, and the structure of these problems (e.g., subproblems are not independent, or combining partial solutions is itself intractable) resists this kind of clean splitting — the 'proof' simply assumes the hard part (finding the decomposition) is possible without justification, which is circular. (B) is factually wrong; the Master theorem is a general tool applicable to any divide-and-conquer recurrence, not restricted to sorting. (C) misdiagnoses the flaw as a computational/arithmetic error in applying cases, when the real flaw is a much deeper conceptual gap in the premise itself. (D) is absurd; this exact style of flawed reasoning is a classic 'proof' used to illustrate why the Master theorem cannot be used to establish the EXISTENCE of an efficient decomposition — only to analyze one that's already given."
})

Q.append({
"q": "In-place merge sort variants attempt to reduce the Θ(n) auxiliary space of standard merge sort. What is the time-complexity trade-off typically incurred by achieving O(1) extra space for the merge step (e.g., via block-based in-place merging techniques)?",
"opts": ["The merge step's time complexity typically increases (e.g., to O(n log n) for the merge alone in some techniques, or the constant factor increases substantially), so achieving O(1) space is not 'free' — there's a genuine time-space trade-off", "There is no trade-off; in-place merging achieves both Θ(n) time and O(1) space simultaneously with no downsides, which is why all modern implementations use it", "In-place merging is impossible for merge sort under any circumstances", "In-place merging always converts merge sort into an unstable sort with no time complexity change"],
"ans": 0,
"exp": "While the standard MERGE procedure achieves Θ(n) time using Θ(n) auxiliary space, true in-place variants (achieving O(1) or O(log n) extra space) generally incur increased time complexity for the merge step itself — some classical in-place merge techniques cost as much as O(n log n) for a single merge (making the WHOLE sort potentially O(n log&sup2; n)), or they retain O(n) merge time but with substantially larger constant factors and code complexity, illustrating a genuine space-time trade-off rather than a free lunch. (B) is false and represents a common misconception; if truly free in-place merging with no time cost existed, it would be the universal standard, but in practice most production sorts (like Timsort) accept Θ(n) auxiliary space for merging because the time trade-offs of true in-place merging are usually not worth it. (C) overstates the difficulty; in-place merge sort variants DO exist in the literature, just with more complex implementations and different complexity trade-offs. (D) incorrectly and unnecessarily ties space complexity to stability; a sort can be modified for lower space usage while remaining unrelated in principle to whether it preserves relative order of equal elements, though some specific in-place techniques do sacrifice stability as an additional (separate) trade-off, not an automatic consequence of the space reduction itself."
})

Q.append({
"q": "For the recurrence describing the number of leaves in the recursion tree of T(n) = 4T(n/2) + n (used e.g. in some matrix algorithms), how many leaves are there at the base of the tree, and how does this relate to the Θ(n&sup2;) final answer?",
"opts": ["n<sup>log&#8322;4</sup> = n&sup2; leaves, each contributing Θ(1) base-case work, so leaf-level work alone accounts for Θ(n&sup2;) — matching the Case-1 conclusion that the leaves (bottom level) dominate the total cost", "log&#8322;n leaves, since the tree has logarithmic depth", "4 leaves, since each internal node has exactly 4 children by definition", "n leaves, matching the linear f(n) term exactly"],
"ans": 0,
"exp": "The recursion tree for T(n)=4T(n/2)+n has branching factor a=4 and depth log&#8322;n, so the number of leaves is a<sup>log&#8322;n</sup> = 4<sup>log&#8322;n</sup> = n<sup>log&#8322;4</sup> = n&sup2; (using the identity a<sup>log_b n</sup> = n<sup>log_b a</sup>). Since each leaf does Θ(1) base-case work, the leaves alone contribute Θ(n&sup2;) total — and because this recurrence falls under Master theorem Case 1 (n<sup>log_b a</sup>=n&sup2; dominates f(n)=n), the leaf-level cost indeed dominates the entire tree's total cost, confirming the Θ(n&sup2;) answer via this alternative recursion-tree reasoning (rather than direct Master theorem application). (B) confuses the number of leaves with the tree's DEPTH; log&#8322;n is the depth, not the leaf count. (C) confuses the branching factor at each single node with the TOTAL leaf count across the whole tree, which compounds multiplicatively across all levels of depth. (D) incorrectly matches the leaf count to the driving function's coefficient, which is a coincidental-looking but incorrect connection — the leaf count comes from a<sup>depth</sup>, unrelated to the value of f(n)."
})

Q.append({
"q": "A hybrid sorting algorithm uses merge sort for large subarrays but switches to insertion sort once subarray size falls below a threshold k (a common real-world optimization). Why does this hybrid approach typically run FASTER in practice than pure merge sort, despite both being Θ(n log n) asymptotically for appropriate fixed thresholds?",
"opts": ["Insertion sort has a much smaller constant factor for small inputs (fewer overhead operations per element, better cache locality, no recursive call overhead), so replacing the bottom few levels of merge sort's recursion (which contribute a large fraction of total recursive CALLS, even if not asymptotic time) with insertion sort reduces real-world constant-factor overhead without changing the asymptotic class", "The hybrid approach is actually Θ(n) because insertion sort is faster than merge sort in all cases", "There is no real speedup; this is a common misconception perpetuated without empirical basis", "The hybrid approach changes the recurrence to T(n) = 2T(n/2) + Θ(log n), which is asymptotically faster than standard merge sort"],
"ans": 0,
"exp": "This reflects a genuinely important practical algorithm-engineering insight (used in real implementations like Timsort and many C++ STL sort implementations): while merge sort is asymptotically Θ(n log n) regardless of the threshold k (as long as k is a fixed constant, this doesn't change the Big-Θ class), insertion sort has very low constant-factor overhead for small inputs (simple loops, good cache behavior, no recursive call/stack overhead, and it's even adaptive — fast on nearly-sorted small runs), so eliminating the bottom several levels of merge sort's recursion (which involve a very large NUMBER of recursive calls, each with function-call overhead, even though their combined asymptotic contribution is still Θ(n) per level) yields a meaningful constant-factor speedup in practice without changing the asymptotic complexity class at all. (B) is false; insertion sort is Θ(n&sup2;) in general and is only used here for small, bounded-size subarrays specifically because its overhead is low in that narrow regime — it does not make the WHOLE algorithm Θ(n). (C) is incorrect; this is a well-documented, empirically validated optimization technique, not a myth. (D) fabricates a nonsensical recurrence; the combine (merge) step's cost is unaffected by this optimization and remains Θ(n) per level."
})

Q.append({
"q": "Which of the following correctly identifies why T(n) = T(n/2) + T(n/2) + O(1) is DIFFERENT from T(n) = T(n/2) + O(1), despite both having only 'n/2'-sized subproblems mentioned?",
"opts": ["The first has TWO independent recursive calls (each contributing separately to total work), giving T(n)=2T(n/2)+O(1)=Θ(n); the second has only ONE recursive call, giving T(n)=T(n/2)+O(1)=Θ(log n) — the coefficient 'a' (number of subproblems) matters enormously even when subproblem SIZE is identical", "They are identical; writing T(n/2) twice versus once is just a stylistic difference with no mathematical consequence", "The first is slower because O(1) is added twice, contributing O(2) total, which changes the growth rate to quadratic", "The second recurrence is invalid because a single recursive call cannot constitute 'divide-and-conquer'"],
"ans": 0,
"exp": "This directly tests whether students grasp that in aT(n/b)+f(n), the coefficient a (how MANY subproblems) is just as important as b (how much smaller each is) — T(n)=T(n/2)+T(n/2)+O(1) is literally 2T(n/2)+O(1) (two separate calls, e.g., processing left and right halves of a tree independently), which is Case 1 (n<sup>log&#8322;2</sup>=n dominates O(1)), giving Θ(n); whereas T(n)=T(n/2)+O(1) has only ONE recursive call (e.g., binary search discarding half the input), which is also technically Case 2 (n<sup>log&#8322;1</sup>=n&#8304;=1=Θ(f(n))=Θ(1)), giving Θ(log n) — a dramatically different growth rate from the same-looking 'n/2' term. (B) is a serious misconception; writing the recursive term once versus twice fundamentally changes 'a' in the Master theorem and produces different complexity classes (Θ(n) vs Θ(log n)) — this is not stylistic at all. (C) fundamentally misunderstands asymptotic notation; O(1)+O(1)=O(1) still (constant plus constant is still constant), that's not what differs between the two recurrences — what differs is the NUMBER of recursive calls, not the O(1) term. (D) is false; single-recursive-call algorithms like binary search are canonical, well-accepted, efficient divide-and-conquer algorithms."
})

Q.append({
"q": "In the classic D&C 'find peak element in an array' problem (an element greater than both neighbors, with boundary conventions), the algorithm compares the midpoint to its neighbor and recurses into the half guaranteed to contain a peak. What is the time complexity, and why is correctness guaranteed even though the array need not be sorted?",
"opts": ["Θ(log n); correctness follows because whichever direction has a strictly larger neighboring element is guaranteed to contain at least one peak, due to the array's finite length and boundary behavior (treating out-of-bounds as -&infin;), regardless of the array's overall ordering", "Θ(n); the array must be scanned entirely since it isn't sorted, so binary-search-style logic cannot apply", "Θ(log&sup2; n); an extra log factor arises from needing to verify both neighbors at every step", "This problem cannot be solved via divide-and-conquer since peaks can appear anywhere, so no informative decision is possible at the midpoint"],
"ans": 0,
"exp": "Despite the array not being sorted, this is a classic D&C application: at any midpoint, if the element to the right is larger, that side is guaranteed (by a simple argument treating positions beyond the array boundary as having value -&infin;) to contain at least one peak — because as you keep moving in the direction of increasing values, you either keep increasing (eventually forced to stop increasing at the boundary, creating a peak) or you find a local peak directly. This gives T(n)=T(n/2)+O(1)=Θ(log n). (B) incorrectly assumes sortedness is required for ANY logarithmic-time divide strategy; this problem is a canonical counterexample showing that a weaker structural guarantee (the existence of SOME peak in the chosen direction) suffices for halving the search space, without full sortedness. (C) fabricates an unnecessary extra log factor; only O(1) comparisons (comparing the midpoint to its immediate neighbors) are needed per level, not a nested logarithmic search. (D) is false and represents a failure to see the clever invariant that makes this problem solvable in logarithmic time despite the lack of global order."
})

Q.append({
"q": "Consider a buggy implementation of merge sort where the base case is written as 'if (high - low <= 1) return;' instead of the correct 'if (low >= high) return;'. For a 2-element subarray, what happens?",
"opts": ["The 2-element subarray is returned unsorted (the base case incorrectly triggers and skips sorting), producing an incorrectly sorted overall array for certain inputs", "The algorithm crashes immediately due to an index-out-of-bounds error", "The algorithm still works correctly because merge sort doesn't need to explicitly handle 2-element subarrays", "The algorithm runs correctly but in Θ(n&sup2;) time instead of Θ(n log n)"],
"ans": 0,
"exp": "With low and high as inclusive indices spanning a 2-element subarray, high&minus;low = 1, so the buggy condition 'high&minus;low &le; 1' incorrectly treats this AS a base case and returns WITHOUT sorting or recursing further — but a genuine base case should only be a single element (high==low, i.e., high&minus;low==0); a 2-element (or larger) subarray still needs to be divided/sorted. This means any 2-element subarray that happens to be out of order at that point in the recursion is never fixed, producing a final array that can be incorrectly sorted (specific adjacent pairs left unswapped). (B) is incorrect; this bug doesn't cause an indexing crash, it causes a silent logical/correctness error — arguably worse since it may go unnoticed. (C) is false; correctly implemented merge sort absolutely must recurse into (and correctly merge) 2-element subarrays; skipping this step breaks correctness. (D) misdiagnoses the bug's effect entirely; this isn't a performance bug, it's a correctness bug — the algorithm may run FASTER (since it does less work) but produces WRONG output, which is a far more serious flaw than a slowdown."
})

Q.append({
"q": "Which best explains why the D&C paradigm is particularly well-suited for PARALLEL computation, using merge sort as the canonical example?",
"opts": ["The two recursive calls on independent subarrays (left half, right half) have no data dependencies on each other, so they can be executed concurrently on separate processors/threads, with only the final merge step requiring synchronization/sequential combination of results", "D&C algorithms are inherently sequential and cannot be parallelized due to the recursive call stack", "Parallelizing D&C requires no synchronization at all, even during the combine/merge step", "Only iterative (non-recursive) algorithms can be parallelized effectively; D&C's recursive nature is a fundamental obstacle"],
"ans": 0,
"exp": "The defining property that makes D&C naturally parallelizable is precisely the independence of subproblems: in merge sort, sorting the left half and sorting the right half share no data and can genuinely run simultaneously on different cores/threads (this is the basis of practical parallel merge sort implementations), with the only necessarily sequential/synchronized part being the merge step where the two independently-computed results must be combined. (B) is factually backwards; the clean subproblem independence is exactly what ENABLES parallelism, not an obstacle — many high-performance parallel sorting libraries exploit exactly this structure. (C) is incorrect; the merge (combine) step genuinely does require its inputs (the two sorted halves) to be ready, so SOME synchronization is unavoidable at that point, even if the recursive calls themselves are parallel. (D) is false and overly broad; recursive algorithms are commonly and effectively parallelized (e.g., via fork-join frameworks specifically designed for exactly this recursive divide-and-conquer pattern), so recursion itself is not an obstacle to parallelism."
})

Q.append({
"q": "For T(n) = 8T(n/2) + Θ(n&sup2;) (the naive matrix-multiplication recurrence before Strassen's optimization), what is T(n), and how does it relate to the direct definition-based Θ(n&sup3;) matrix multiplication algorithm?",
"opts": ["Θ(n&sup3;), by Master theorem Case 1 (since n<sup>log&#8322;8</sup>=n&sup3; dominates Θ(n&sup2;)); this matches the standard triple-nested-loop matrix multiplication complexity exactly, confirming the recursive block-based decomposition is asymptotically equivalent to the direct method", "Θ(n&sup2; log n), by Case 2, strictly better than triple-nested loops", "Θ(n&sup2;), by Case 3, matching the combine step exactly", "Θ(n&sup2;.807), by accidentally applying Strassen's exponent to the wrong recurrence"],
"ans": 0,
"exp": "With a=8 (eight recursive submatrix multiplications in the naive block decomposition: splitting each of two n&times;n matrices into four (n/2)&times;(n/2) blocks requires 8 total submatrix multiplications to compute all four blocks of the result), b=2, we get n<sup>log&#8322;8</sup>=n&sup3;, which dominates the Θ(n&sup2;) combine/addition work (Case 1), giving Θ(n&sup3;) — exactly matching the complexity of the straightforward triple-nested-loop algorithm, confirming that this particular recursive decomposition offers no asymptotic advantage (which is precisely WHY Strassen's insight of reducing from 8 to 7 multiplications was such a significant breakthrough, since it broke this equivalence). (B) misapplies Case 2, which requires exact (not merely 'positive') matching between f(n) and n<sup>log_b a</sup>; here Θ(n&sup2;) is much smaller than Θ(n&sup3;), not equal to it. (C) misapplies Case 3, which requires f(n) to DOMINATE, but here f(n)=Θ(n&sup2;) is smaller than n<sup>log_b a</sup>=n&sup3;, the opposite of Case 3's requirement. (D) confuses this recurrence (with a=8, the naive approach) with Strassen's distinct recurrence (with a=7); the exponent n<sup>2.807</sup> specifically comes from log&#8322;7, not log&#8322;8, and applies only to the Strassen-optimized version."
})

Q.append({
"q": "A D&C algorithm to find the majority element (an element occurring &gt; n/2 times) works by recursively finding candidate majority elements in each half, then verifying by counting. If each half's candidate is found recursively and a final Θ(n) counting pass verifies the true majority, what is the recurrence and complexity, and what subtlety must the combine step handle?",
"opts": ["T(n) = 2T(n/2) + Θ(n) = Θ(n log n); the combine step must correctly recognize that a global majority element (if one exists) must be a majority element in AT LEAST ONE of the two halves, requiring both halves' candidates to be checked, not just one arbitrarily chosen candidate", "T(n) = 2T(n/2) + Θ(1) = Θ(n); no verification is needed since the recursive candidates are always correct", "T(n) = T(n/2) + Θ(n) = Θ(n); only one half needs to be searched since majority elements are always found in the first half by definition", "T(n) = 2T(n/2) + Θ(n&sup2;) = Θ(n&sup2;); verification requires comparing every pair of elements from both halves"],
"ans": 0,
"exp": "This is a classic and subtle D&C application: the key correctness insight is that if an element is a majority element (&gt;n/2 occurrences) in the WHOLE array, it must be a majority element in at least one of the two halves (a pigeonhole-style argument: if it weren't, it couldn't possibly reach a majority count when combined) — so the combine step must take BOTH candidates returned by the two recursive calls and verify each with a Θ(n) counting pass over the full array to determine the true overall majority (if any), giving T(n)=2T(n/2)+Θ(n)=Θ(n log n). (B) incorrectly skips the essential verification step; a candidate that's a local majority in one half is not guaranteed to be a GLOBAL majority without an explicit count. (C) incorrectly claims only one half needs searching and that majority elements always appear in 'the first half,' which has no basis — the majority element could be concentrated in either half or split across both. (D) drastically overestimates the verification cost; a single Θ(n) linear counting pass per candidate suffices, not a quadratic all-pairs comparison."
})

Q.append({
"q": "Which statement correctly captures a KEY limitation of applying the Master theorem to recurrences arising from randomized divide-and-conquer algorithms, such as randomized quicksort?",
"opts": ["The Master theorem, as classically stated, applies to WORST-CASE deterministic recurrences of the exact form T(n)=aT(n/b)+f(n) with fixed a and b; randomized algorithms like quicksort have recurrences that depend on a RANDOM split point (varying 'a' and subproblem sizes across runs), so their AVERAGE-CASE analysis typically requires different techniques (like the indicator random variable method) rather than a direct Master theorem application", "The Master theorem cannot be used for ANY algorithm that includes comparisons, since comparisons introduce implicit randomness", "Randomized algorithms are always analyzed using the Master theorem's Case 2 by convention, regardless of their actual structure", "There is no limitation; the Master theorem directly and rigorously handles randomized splits without modification"],
"ans": 0,
"exp": "The Master theorem as presented in CLRS is fundamentally built for the deterministic recurrence form T(n)=aT(n/b)+f(n), where every subproblem is guaranteed to be exactly size n/b; randomized quicksort's recurrence, by contrast, involves a RANDOM pivot that creates subproblems of varying (random) sizes across different executions, so its expected-case Θ(n log n) analysis is instead typically proven via other methods, such as defining indicator random variables for each pair of elements being compared and computing the expected number of comparisons directly — a fundamentally different (though related in spirit) analytical approach, not a literal application of the Master theorem's case-matching machinery. (B) is a nonsensical overgeneralization; comparisons themselves don't introduce randomness (only the RANDOM PIVOT CHOICE does, in the randomized variant specifically). (C) is fabricated; there's no such 'convention,' and applying Case 2 without justification would be mathematically unsound. (D) is false and directly contradicts the actual limitation being tested; the Master theorem, in its standard form, is simply not designed for random/varying subproblem sizes."
})

with open("/home/claude/mcq/dc_part_b.json", "w") as f:
    import json
    json.dump(Q, f)
print(len(Q))
