# -*- coding: utf-8 -*-
Q = []

Q.append({
"q": "What are the two key properties a problem must exhibit for dynamic programming to be applicable, as identified in CLRS?",
"opts": ["Optimal substructure and overlapping subproblems", "Greedy-choice property and matroid structure", "Convexity and monotonicity", "NP-hardness and polynomial reducibility"],
"ans": 0,
"exp": "CLRS identifies optimal substructure (an optimal solution to the problem contains within it optimal solutions to subproblems) and overlapping subproblems (the recursive algorithm revisits the same subproblems repeatedly, making caching worthwhile) as the two defining ingredients for DP applicability. (B) describes properties relevant to GREEDY algorithms, not DP specifically &mdash; while greedy problems also have optimal substructure, the matroid/greedy-choice property is a distinct, stronger condition that DP problems need not satisfy. (C) invents mathematical properties (convexity, monotonicity) that are sometimes relevant to specific DP problems' correctness proofs but are not the general defining criteria for DP applicability. (D) is a nonsensical pairing; DP is a technique for solving certain POLYNOMIAL-time-solvable problems, and has no direct connection to NP-hardness as a defining criterion."
})

Q.append({
"q": "In the rod-cutting problem, why does the naive recursive solution CUT-ROD (without memoization) run in Θ(2&#8319;) time despite there being only n distinct subproblems?",
"opts": ["Because the recursion tree revisits the same subproblems (e.g., cutting a rod of length k) exponentially many times without caching, since each call to CUT-ROD(n) branches into recursive calls for every smaller length independently, and those calls further re-branch", "Because the problem doesn't actually have only n distinct subproblems; there are exponentially many distinct rod configurations", "Because the recursion depth is exponential, not because of redundant recomputation", "Because each subproblem itself takes exponential time to solve, even without recursion"],
"ans": 0,
"exp": "CUT-ROD(n) tries every possible first-cut length i from 1 to n, recursively calling CUT-ROD(n&minus;i) for each &mdash; but critically, the SAME value of n&minus;i can be reached via many different paths through the recursion tree (e.g., CUT-ROD(5) might be called both directly from CUT-ROD(7) with a cut of 2, and indirectly via CUT-ROD(6) with a cut of 1, then CUT-ROD(5) again), and without memoization, each of these calls redundantly re-solves the same subproblem from scratch, leading to exponential blowup despite only n distinct subproblem VALUES existing. (B) is false; the number of distinct subproblems is exactly n (lengths 0 through n), which is precisely why memoization is so effective &mdash; the issue is redundant recomputation, not an actual explosion in distinct subproblems. (C) misattributes the cause; while recursion depth can be up to n, depth alone doesn't cause exponential time &mdash; it's the BRANCHING and overlap that causes it. (D) is false; each individual subproblem's 'own' work (excluding recursive calls) is O(n) at most (looping over cut choices), not exponential in itself."
})

Q.append({
"q": "For the CUT-ROD problem, what is the recurrence for the optimal revenue r(n), and how many 'choices' does each subproblem consider?",
"opts": ["r(n) = max over 1&le;i&le;n of (p&#7522; + r(n&minus;i)), with n choices considered per subproblem (one for each possible first-cut length i)", "r(n) = r(n/2) + r(n/2), with exactly 2 choices per subproblem", "r(n) = p&#8345; (the price of the whole uncut rod), with 1 choice per subproblem", "r(n) = max(r(n&minus;1), r(n&minus;2)), with 2 choices per subproblem, analogous to Fibonacci"],
"ans": 0,
"exp": "CLRS's rod-cutting recurrence is r(n) = max<sub>1&le;i&le;n</sub>(p&#7522; + r(n&minus;i)), reflecting the choice of where to make the FIRST cut (a piece of length i sold for p&#7522;, plus the optimally cut remainder of length n&minus;i); there are n possible values of i to consider for a rod of length n, giving n choices per subproblem, and Θ(n) subproblems overall, yielding the O(n&sup2;) total running time for the DP solution. (B) fabricates a halving recurrence that doesn't reflect the actual problem structure &mdash; rod cutting doesn't have a natural 'split in half' structure since cuts can be made at ANY length. (C) describes the degenerate 'sell the whole rod uncut' case, ignoring all other possible cutting strategies entirely. (D) invents a Fibonacci-like recurrence with no basis in the actual rod-cutting problem, which genuinely requires considering ALL possible first-cut lengths, not just two fixed offsets."
})

Q.append({
"q": "What is the crucial difference between the 'top-down with memoization' and 'bottom-up' (tabulation) approaches to dynamic programming, in terms of which subproblems get solved?",
"opts": ["Top-down memoization solves ONLY the subproblems that are actually needed (as determined by the recursive calls), potentially skipping some that bottom-up would compute; bottom-up systematically fills the entire table in a fixed order, computing every subproblem regardless of whether it's strictly necessary for the final answer", "Top-down and bottom-up always solve exactly the same set of subproblems, just in different orders", "Bottom-up always uses less memory than top-down, since it never uses recursion", "Top-down cannot be used for any problem that bottom-up can solve, and vice versa"],
"ans": 0,
"exp": "A subtle but real distinction: top-down memoization follows the natural recursive call structure and only computes/caches subproblems that are actually reached from the original call, which can sometimes save work if certain subproblems in the 'full' table are never actually needed for the specific top-level query; bottom-up tabulation, by contrast, typically fills the ENTIRE table in a systematic order (e.g., smallest to largest), computing every entry even if some end up unused by the final answer. In many classic DP problems (like rod cutting, matrix-chain, LCS) all subproblems ARE eventually needed, making this difference moot in practice, but the distinction is real and occasionally matters (e.g., in some graph or game-tree DP where pruning naturally occurs top-down). (B) overstates the equivalence; while they solve the same subproblems in many textbook examples, this is not a general guarantee. (C) is an overgeneralization; while bottom-up often avoids recursion-stack overhead, memory usage depends heavily on the specific problem and implementation, and top-down with memoization can sometimes use LESS memory if many subproblems are skipped. (D) is false; both approaches are generally interchangeable for problems with well-defined optimal substructure and overlapping subproblems, differing mainly in implementation style and sometimes constant-factor performance."
})

Q.append({
"q": "In the matrix-chain multiplication problem, m[i,j] denotes the minimum number of scalar multiplications to compute the matrix chain product A&#7522;A<sub>i+1</sub>...A&#7527;. What is the recurrence for m[i,j] when i&lt;j, and why must ALL split points k be tried?",
"opts": ["m[i,j] = min over i&le;k&lt;j of (m[i,k] + m[k+1,j] + p<sub>i-1</sub>p&#8342;p&#7527;); all split points must be tried because the optimal split location isn't known in advance, and different splits can yield vastly different total multiplication counts due to how matrix dimensions interact", "m[i,j] = m[i,j&minus;1] + m[j,j], with only one split point needed (the last matrix)", "m[i,j] = p&#7522;&middot;p&#7527;, computed directly without any recursive split", "m[i,j] = min(m[i+1,j], m[i,j&minus;1]), trying only two options: remove the first or last matrix"],
"ans": 0,
"exp": "The correct recurrence considers splitting the chain A&#7522;...A&#7527; at every possible position k (between A&#8342; and A<sub>k+1</sub>), computing the cost of the left sub-chain (m[i,k]), the right sub-chain (m[k+1,j]), plus the cost of multiplying the two resulting matrices together (p<sub>i-1</sub>p&#8342;p&#7527;, based on the dimensions) &mdash; and since the optimal parenthesization's split point is not known ahead of time (different splits can lead to drastically different total costs depending on the specific dimension sequence), ALL j&minus;i possible values of k must be examined and the minimum taken, which is precisely why this subproblem has 'j&minus;i choices' as CLRS notes. (B) incorrectly restricts to only ONE specific split (removing just the last matrix), which is only one of many possible parenthesizations and generally not optimal. (C) is the base case formula (technically m[i,i]=0 for a single matrix, not p&#7522;&middot;p&#7527;), not the general recursive case for a chain of 2+ matrices. (D) incorrectly restricts the choices to only 2 fixed options (first or last), ignoring the fact that the optimal split could occur at ANY internal position, which is exactly why the actual recurrence needs to try all j&minus;i candidates."
})

Q.append({
"q": "For matrix-chain multiplication with n matrices, what is the total running time of the standard bottom-up DP algorithm, and where does this complexity come from?",
"opts": ["Θ(n&sup3;): Θ(n&sup2;) subproblems (all pairs i&le;j), each requiring up to Θ(n) choices of split point k to minimize over", "Θ(n&sup2;): Θ(n) subproblems, each requiring Θ(n) choices", "Θ(n log n): Θ(n) subproblems solved via a divide-and-conquer-style recursive split", "Θ(2&#8319;): exponential, since every possible full parenthesization must be enumerated"],
"ans": 0,
"exp": "There are Θ(n&sup2;) distinct subproblems m[i,j] (since i and j range independently over roughly n values each, subject to i&le;j), and for each subproblem, up to Θ(n) split points k must be tried to find the minimum &mdash; multiplying subproblem count by choices-per-subproblem gives Θ(n&sup2;)&times;Θ(n) = Θ(n&sup3;) total time, exactly matching CLRS's stated complexity for this algorithm. (B) undercounts the number of subproblems; matrix-chain multiplication's subproblems are indexed by PAIRS (i,j), not single indices, giving Θ(n&sup2;) subproblems, not Θ(n). (C) is false; there's no logarithmic speedup available here via simple divide-and-conquer, since (unlike, say, merge sort) the optimal split point isn't fixed at the midpoint and must be searched over. (D) describes the naive brute-force enumeration of all parenthesizations (related to the Catalan number of parenthesizations, which IS exponential), which is exactly what DP avoids by exploiting overlapping subproblems &mdash; the whole point of using DP here is to avoid this exponential blowup."
})

Q.append({
"q": "Why does the matrix-chain multiplication problem require filling the DP table m[i,j] in order of increasing CHAIN LENGTH (j&minus;i), rather than simply row-by-row or column-by-column?",
"opts": ["Because computing m[i,j] requires m[i,k] and m[k+1,j] for all valid k, both of which represent STRICTLY SHORTER sub-chains than [i,j]; filling by increasing chain length guarantees these shorter-chain values are already computed when needed", "Because row-by-row filling is computationally impossible for this specific recurrence", "Because chain length order minimizes the total number of table entries needed", "There's no such requirement; any fill order produces correct results as long as all cells are eventually filled"],
"ans": 0,
"exp": "The dependency structure of m[i,j] = min over k of (m[i,k]+m[k+1,j]+...) means m[i,j] depends on m[i,k] and m[k+1,j], both of which correspond to sub-chains STRICTLY SHORTER than the chain from i to j (since k&lt;j and k+1&gt;i within the range) &mdash; so filling the table in order of increasing chain length (l=1,2,...,n&minus;1, computing all m[i,i+l] for each l) guarantees that whenever m[i,j] is computed, all the shorter sub-chain values it depends on are already available, avoiding the use of uninitialized/incorrect data. (B) is false; row-by-row filling isn't 'impossible,' but it would visit cells in an order that doesn't respect the dependency structure, leading to using not-yet-computed values. (C) is a fabricated and false justification; the fill order doesn't change how many table entries exist &mdash; that's fixed by the problem's Θ(n&sup2;) subproblem space regardless of order. (D) is incorrect and represents a serious misunderstanding; the specific dependency structure here means an ARBITRARY fill order (like naive row-major without considering chain length) would very likely access table entries that haven't been computed yet, producing wrong (garbage/uninitialized) results."
})

Q.append({
"q": "In the Longest Common Subsequence (LCS) problem, the recurrence for c[i,j] (LCS length of prefixes X[1..i] and Y[1..j]) is: c[i,j] = c[i&minus;1,j&minus;1]+1 if x&#7522;=y&#7527;, else max(c[i&minus;1,j], c[i,j&minus;1]). What subtle case does this recurrence handle when x&#7522;=y&#7527;, and why is it NOT simply max(c[i&minus;1,j], c[i,j&minus;1], c[i&minus;1,j&minus;1]+1)?",
"opts": ["When x&#7522;=y&#7527;, the matching character MUST be included in an optimal LCS ending at these positions (proven via a cut-and-paste/exchange argument), so only c[i&minus;1,j&minus;1]+1 is needed &mdash; including the other two terms would be redundant since they can never exceed c[i&minus;1,j&minus;1]+1 when characters match", "Because computing all three terms would be too slow, so the algorithm sacrifices correctness for speed", "Because c[i&minus;1,j] and c[i,j&minus;1] are undefined when x&#7522;=y&#7527;", "There's no real difference; both formulations always give identical results in every case, so the simpler one is just stylistic preference"],
"ans": 0,
"exp": "CLRS proves (via an exchange/cut-and-paste argument in Theorem 14.1) that when x&#7522;=y&#7527;, EVERY optimal LCS of X[1..i] and Y[1..j] must end with this matching character (otherwise, you could always extend a non-matching-ending LCS by this match to get a strictly longer common subsequence, contradicting optimality) &mdash; so the recurrence correctly restricts to ONLY c[i&minus;1,j&minus;1]+1 in this case; it is mathematically guaranteed that c[i&minus;1,j]&le;c[i&minus;1,j&minus;1]+1 and c[i,j&minus;1]&le;c[i&minus;1,j&minus;1]+1 always hold, so including them in a max() would never change the result &mdash; they're provably redundant, not merely omitted for convenience. (B) is false and represents a serious misconception; this isn't a correctness-for-speed tradeoff, it's a PROVEN optimization based on the problem's structure. (C) is false; c[i&minus;1,j] and c[i,j&minus;1] are always well-defined table entries regardless of whether x&#7522; equals y&#7527; &mdash; they're simply not NEEDED in this particular case. (D) is misleading; while the simpler formula IS always correct, it's not merely 'stylistic' &mdash; it reflects a genuine, provable mathematical fact about the problem's optimal substructure that a naive three-way max wouldn't obviously reveal without the underlying proof."
})

Q.append({
"q": "What is the time and space complexity of the standard LCS DP algorithm for two strings of length m and n, and what technique can reduce the space complexity if only the LCS LENGTH (not the actual subsequence) is needed?",
"opts": ["Θ(mn) time and Θ(mn) space for the full table; space can be reduced to Θ(min(m,n)) by keeping only the current and previous row/column, since each cell only depends on the immediately preceding row and column", "Θ(mn) time and Θ(m+n) space always, with no further reduction possible", "Θ(m+n) time and Θ(mn) space, since only the diagonal needs to be filled", "Θ(mn&sup2;) time and Θ(mn) space, due to needing all three predecessor cells at every step"],
"ans": 0,
"exp": "The standard LCS algorithm fills an (m+1)&times;(n+1) table with Θ(1) work per cell, giving Θ(mn) time and Θ(mn) space for the full table &mdash; but since c[i,j] depends ONLY on c[i&minus;1,j&minus;1], c[i&minus;1,j], and c[i,j&minus;1] (i.e., only the immediately preceding row, or the current and previous row), the space can be reduced to O(min(m,n)) by only keeping two rows (or columns) at a time, a classic and important space-optimization technique &mdash; though this reduction sacrifices the ability to RECONSTRUCT the actual subsequence via backtracking, since the full table (or an alternative reconstruction method like Hirschberg's algorithm) is needed for that. (B) correctly states the reducible space bound is achievable but incorrectly claims 'no further reduction possible,' when in fact Θ(min(m,n)) (not just Θ(m+n)) is achievable and is the tighter, more standard answer. (C) is factually wrong on both counts; the time complexity is Θ(mn), not Θ(m+n) (every cell must be visited), and space is reducible below Θ(mn), not requiring the full table if only the length is needed. (D) fabricates a higher time complexity with no justification; only 3 predecessor cells are ever examined per cell (O(1) work), not requiring any additional per-cell factor of n."
})

Q.append({
"q": "Given two strings 'ABCBDAB' and 'BDCABA', a student computes an LCS DP table but makes an off-by-one error, treating c[i,j] as comparing X[i] to Y[j] directly (0-indexed) while still using a table sized (m+1)&times;(n+1) with 1-indexed CLRS-style recurrence logic. What is the most likely resulting bug?",
"opts": ["An index-shift mismatch causing comparisons between the WRONG characters (e.g., comparing X[0] when the logic assumes X[1] was intended), leading to an incorrect LCS length or subsequence due to systematically comparing shifted character pairs", "The algorithm will crash immediately with an array-index-out-of-bounds exception on the very first comparison", "The bug has no effect because 0-indexing and 1-indexing are mathematically equivalent for this recurrence", "The LCS length will always come out exactly one character too long due to a double-counting effect"],
"ans": 0,
"exp": "This is one of the most common real implementation bugs in LCS: CLRS's mathematical formulation is naturally 1-indexed (c[i,j] considers the first i characters of X and first j characters of Y, with X[i] referring to the i-th character in 1-indexed terms), but many programming languages use 0-indexed arrays, so directly translating 'X[i]' in the pseudocode to 'X[i]' in 0-indexed code (instead of the correct 'X[i&minus;1]') causes a systematic off-by-one shift, comparing the WRONG pair of characters at every cell &mdash; this typically doesn't crash (since indices usually stay in bounds due to the table being sized (m+1)&times;(n+1)) but silently produces incorrect results. (B) is unlikely for THIS specific bug pattern; because the table is still sized with the extra row/column buffer, indices generally remain in bounds even with the shift, though the comparisons are simply wrong. (C) is false; 0- and 1-indexing are NOT mathematically interchangeable without adjusting the indexing formula, precisely because the recurrence's meaning of X[i] depends on which convention is used. (D) fabricates a specific, incorrect prediction about the exact nature of the error; an indexing bug like this can cause various incorrect LCS lengths depending on the specific input strings, not a predictable 'always one too long' pattern."
})

Q.append({
"q": "What is the key insight that allows the 0/1 Knapsack problem to be solved via dynamic programming in pseudo-polynomial O(nW) time (n items, capacity W), and why is this NOT considered truly polynomial time?",
"opts": ["The DP table is indexed by (item index, remaining capacity), exploiting the fact that the optimal solution for a given capacity only depends on optimal solutions for smaller capacities and fewer items; it's pseudo-polynomial because W appears as a NUMBER in the input (its magnitude, not the number of bits needed to represent it), so runtime is technically exponential in the BIT-LENGTH of W", "The DP achieves true polynomial time because W is always bounded by a small constant in practice", "The insight is sorting items by value-to-weight ratio, which is what makes it polynomial", "0/1 Knapsack cannot actually be solved by dynamic programming; only the fractional variant can"],
"ans": 0,
"exp": "The 0/1 Knapsack DP defines dp[i][w] = the maximum value achievable using the first i items with capacity exactly (or at most) w, and the recurrence dp[i][w] = max(dp[i&minus;1][w], dp[i&minus;1][w&minus;weight&#7522;]+value&#7522;) (if item i fits) exploits optimal substructure over both dimensions, giving O(nW) time and space &mdash; but this is called PSEUDO-polynomial because W's CONTRIBUTION to the running time scales with its numeric VALUE, not the number of BITS needed to encode it in the input (which would be log&#8322;W); if W is given as, say, a 64-bit number representing a huge capacity, the algorithm's actual running time in terms of INPUT SIZE (which counts bits, per complexity theory convention) is exponential, not polynomial &mdash; this is precisely why 0/1 Knapsack is NP-hard (in the weak sense) despite having this seemingly efficient DP solution. (B) is false as a general statement; W is not always small in practice, and the complexity classification doesn't depend on assumptions about typical W values. (C) confuses 0/1 Knapsack's DP with the GREEDY algorithm used for the FRACTIONAL Knapsack variant, where sorting by value-to-weight ratio IS the key technique &mdash; but that greedy approach does NOT work correctly for 0/1 Knapsack. (D) is factually wrong; 0/1 Knapsack absolutely CAN be solved via DP (as described), it's simply pseudo-polynomial rather than polynomial in the strict complexity-theoretic sense."
})

Q.append({
"q": "A common student error in 0/1 Knapsack DP is iterating over capacity w in the WRONG order when using a 1D space-optimized array (instead of a full 2D table). What specific bug results from iterating w from LOW to HIGH (ascending) instead of HIGH to LOW (descending) in the space-optimized version?",
"opts": ["Items get counted MULTIPLE times (effectively turning it into an UNBOUNDED knapsack, where each item can be reused), because updating dp[w] using dp[w&minus;weight&#7522;] with ascending order means dp[w&minus;weight&#7522;] may have ALREADY been updated to include item i earlier in the same pass", "The algorithm crashes due to negative array indices", "There is no difference; both iteration orders always produce identical, correct results for 0/1 Knapsack", "The algorithm undercounts value by skipping every other item due to index parity issues"],
"ans": 0,
"exp": "This is a very well-known, subtle DP bug: in the 1D space-optimized 0/1 Knapsack (dp[w] = max(dp[w], dp[w&minus;weight&#7522;]+value&#7522;) for each item i, iterating w in some order), the CORRECT approach iterates w from HIGH to LOW so that dp[w&minus;weight&#7522;] still refers to the value from the PREVIOUS item's pass (i.e., NOT yet including item i), correctly enforcing the 0/1 constraint (each item used at most once); iterating LOW to HIGH instead means that by the time you reach a higher w, dp[w&minus;weight&#7522;] may ALREADY reflect item i being included (from an earlier, smaller-w update within the SAME item's pass), effectively allowing item i to be counted multiple times, which silently transforms the problem into UNBOUNDED knapsack (where item reuse is allowed) &mdash; a completely different problem with a different (and generally higher) optimal answer. (B) is false; this bug doesn't cause negative indices or crashes, it causes a silent semantic change to a different problem. (C) is dangerously wrong; this iteration-order bug is one of the most commonly tested 'gotcha' details in DP courses precisely because the difference is completely invisible unless you understand WHY the order matters. (D) is a fabricated and unrelated failure mode with no connection to the actual bug mechanism (which is about incorrect item-reuse, not skipped indices)."
})

Q.append({
"q": "For the Longest Increasing Subsequence (LIS) problem, the O(n&sup2;) DP defines dp[i] = length of the LIS ending exactly at index i. What is the recurrence, and why must the algorithm take the MAXIMUM over ALL dp[i] values at the end (rather than just returning dp[n&minus;1])?",
"opts": ["dp[i] = 1 + max(dp[j] for all j&lt;i where A[j]&lt;A[i]), defaulting to 1 if no such j exists; the overall LIS could END at ANY index, not necessarily the last one, so the final answer requires scanning all dp[i] values to find the true maximum", "dp[i] = dp[i&minus;1] + 1 always, since the LIS must include every element in order", "dp[i] = max(dp[i&minus;1], dp[i&minus;2]), analogous to a Fibonacci-style recurrence", "dp[n&minus;1] alone always gives the correct answer, since the LIS by definition must end at the last element of the array"],
"ans": 0,
"exp": "The correct recurrence considers, for each index i, all PRIOR indices j&lt;i where A[j]&lt;A[i] (meaning A[i] can validly extend an increasing subsequence ending at j), taking the best (longest) such extension and adding 1 for A[i] itself; since dp[i] specifically represents subsequences ENDING at index i, and the true LIS of the whole array could end at ANY position (not necessarily the last one &mdash; e.g., in [10,9,2,5,3,7,101,18], the LIS [2,3,7,101] ends at index 6, not index 7), the final answer must be max(dp[0], dp[1], ..., dp[n&minus;1]), not simply dp[n&minus;1]. (B) incorrectly assumes the LIS must be contiguous/include every element, which contradicts the very definition of a SUBSEQUENCE (elements need not be contiguous, and not all elements need be included). (C) fabricates an unrelated Fibonacci-style recurrence with no connection to the actual LIS problem's dependency structure, which requires comparing A[i] against ALL valid prior elements, not just the immediately preceding one or two. (D) is a common and serious misconception; nothing guarantees the overall longest increasing subsequence ends at the LAST array position &mdash; that assumption is simply false in general."
})

Q.append({
"q": "What is the improved O(n log n) algorithm for LIS, and what is the key data structure / invariant it maintains that the naive O(n&sup2;) DP doesn't exploit?",
"opts": ["It maintains an auxiliary array 'tails' where tails[k] stores the SMALLEST possible tail value of an increasing subsequence of length k+1 found so far, using binary search to find and update the correct position in O(log n) per element, exploiting the fact that this tails array is always sorted", "It uses a hash table to store all previously seen elements for O(1) lookup, making each step O(1) instead of O(n)", "It sorts the array first in O(n log n) time, then the LIS is trivially the entire sorted array", "It uses a segment tree to answer range-maximum queries, achieving O(log n) per element but requiring O(n&sup2;) preprocessing"],
"ans": 0,
"exp": "The key insight behind the O(n log n) LIS algorithm is maintaining an array (often called 'tails') where tails[k] represents the smallest possible tail value among all increasing subsequences of length k+1 discovered so far; this array is provably always sorted (a non-obvious but crucial invariant), which allows using BINARY SEARCH to find where each new element should be placed (either extending the LIS or replacing an existing tail with a smaller value to keep future extensions more flexible), giving O(log n) work per element and O(n log n) total &mdash; this exploits a MONOTONICITY property (the sorted tails array) that the naive O(n&sup2;) DP's structure (all-pairs comparison) doesn't directly leverage. (B) is a fabricated and incorrect mechanism; a simple hash table lookup doesn't capture the ORDERING information needed to correctly determine increasing subsequence lengths &mdash; LIS fundamentally requires comparison-based reasoning about relative order, not just presence/absence. (C) is deeply flawed; sorting the array destroys the original ORDER information that defines what counts as a valid subsequence in the first place &mdash; the LIS problem is about subsequences of the ORIGINAL array order, not a sorted version. (D) fabricates a segment-tree-based approach with an internally inconsistent complexity claim (O(n&sup2;) preprocessing would defeat the purpose of an O(n log n) algorithm) that doesn't match any standard LIS algorithm."
})

Q.append({
"q": "Consider the DP recurrence for counting the number of distinct ways to make change for amount V using coin denominations c&#8321;,...,c&#8345; (unlimited supply of each, order doesn't matter &mdash; i.e., combinations, not permutations). Why does iterating coins in the OUTER loop and amount in the INNER loop produce a DIFFERENT (correct, combination-counting) result than iterating amount in the outer loop and coins in the inner loop (which counts permutations)?",
"opts": ["With coins in the outer loop, each coin denomination is 'fully processed' (potentially used any number of times) before moving to the next denomination, which enforces a canonical ORDER on how coins are combined (preventing the same SET of coins used in different orders from being double-counted); with amount in the outer loop, every amount reconsiders ALL coins fresh at each step, allowing the same combination to be counted once for each ORDERING of its coins, giving a permutation count instead", "There is no actual difference; both loop orders always produce identical counts for this problem", "The coins-outer version is simply a performance optimization with no effect on which value is computed, only how fast it's computed", "Amount-outer counting is always wrong and produces negative numbers due to integer underflow"],
"ans": 0,
"exp": "This is one of the most conceptually important 'gotcha' distinctions in introductory DP courses: making COINS the outer loop variable means that when processing coin c&#8342;, you build upon a state that has ALREADY decided how many times coins c&#8321;,...,c<sub>k-1</sub> are used, establishing an implicit canonical order (e.g., 'always consider coin types in a fixed order, deciding how many of each to use before moving to the next type'), which naturally counts each COMBINATION (unordered multiset of coins) exactly once; making AMOUNT the outer loop instead means at every amount value, ALL coin types are reconsidered without regard to a fixed processing order, so a combination like {1,2} can be reached via the sequence 'first use a 1, then a 2' AND 'first use a 2, then a 1,' double-counting it as if order mattered &mdash; correctly computing the number of PERMUTATIONS (ordered sequences) instead of combinations. (B) is a serious and common misconception; the two loop orders provably give DIFFERENT final answers for the counting variant of coin change (though they give the SAME answer for the simpler 'minimum number of coins' or 'can it be made' variants, which is often why students are surprised the counting case differs). (C) mischaracterizes a genuine semantic/correctness difference as merely a performance detail; both orders can have similar time complexity, but they compute mathematically DIFFERENT quantities for the counting problem. (D) is a fabricated and nonsensical failure mode with no basis; there's no integer underflow issue here, the amount-outer version simply computes a different (larger, generally) but still valid non-negative count &mdash; it's just answering a different question (permutations vs. combinations)."
})

Q.append({
"q": "For the 'minimum edit distance' (Levenshtein distance) DP problem between strings of length m and n, allowing insertion, deletion, and substitution (each cost 1), what is the recurrence for dp[i][j], and what does each of the three terms in the min() represent?",
"opts": ["dp[i][j] = min(dp[i&minus;1][j]+1, dp[i][j&minus;1]+1, dp[i&minus;1][j&minus;1] + (0 if X[i]=Y[j] else 1)), representing deletion from X, insertion into X (to match Y), and substitution (or match) respectively", "dp[i][j] = dp[i&minus;1][j&minus;1] + 1 always, since edit distance only ever requires substitution operations", "dp[i][j] = min(dp[i&minus;1][j], dp[i][j&minus;1]) only, ignoring the diagonal case entirely since substitution is never optimal", "dp[i][j] = |i&minus;j|, computed directly via a closed-form formula without any recursive table-filling"],
"ans": 0,
"exp": "The classic edit-distance recurrence considers three operations at each step: deleting a character from X (moving from dp[i&minus;1][j], costing 1), inserting a character into X to match Y (moving from dp[i][j&minus;1], costing 1), and either substituting X[i] for Y[j] or matching them if already equal (moving from the diagonal dp[i&minus;1][j&minus;1], costing 1 if they differ or 0 if they already match) &mdash; taking the minimum of these three options correctly captures the cheapest way to transform one prefix into another. (B) incorrectly assumes only substitution is ever needed, completely ignoring insertion and deletion, which are frequently necessary (e.g., transforming 'cat' to 'cats' requires an insertion, not a substitution). (C) incorrectly discards the diagonal (substitution/match) option entirely, which is frequently the OPTIMAL choice, especially when characters already match (giving a free 0-cost move) &mdash; omitting it would make the algorithm systematically overestimate the true edit distance. (D) is a fabricated closed-form that is simply incorrect in general; edit distance genuinely depends on the specific CONTENT of the two strings (how many characters match at various alignments), not merely their length difference &mdash; |i&minus;j| only provides a LOWER BOUND, not the exact answer."
})

Q.append({
"q": "In the edit-distance DP table, what do the FIRST ROW and FIRST COLUMN (base cases) represent, and why are they initialized as dp[0][j]=j and dp[i][0]=i?",
"opts": ["dp[0][j]=j represents transforming an EMPTY string into the first j characters of Y, requiring exactly j insertions; dp[i][0]=i represents transforming the first i characters of X into an EMPTY string, requiring exactly i deletions", "dp[0][j] and dp[i][0] are arbitrary initialization values with no semantic meaning, chosen only to avoid undefined table lookups", "dp[0][j]=j and dp[i][0]=i because the empty string always has edit distance 0 to any string, and the formula is a typo/convention rather than a meaningful cost", "These base cases represent the WORST-CASE edit distance, used only as safety upper bounds that get overwritten during the main computation"],
"ans": 0,
"exp": "The base cases have precise semantic meaning grounded in the problem definition: dp[0][j] represents the edit distance between an EMPTY prefix of X and the first j characters of Y, which can ONLY be achieved by inserting all j characters of Y one at a time (since there's nothing in X to delete, substitute, or match against), giving a cost of exactly j; symmetrically, dp[i][0] represents transforming the first i characters of X into an empty string, requiring exactly i deletions, giving cost i. These are not arbitrary values but are directly derivable from the problem's definition applied to the degenerate empty-string case. (B) is false; far from being arbitrary, these values are mathematically FORCED by the problem's semantics &mdash; there is exactly one way to transform an empty string into a j-character string using only insertions (or vice versa with deletions), so the cost is uniquely determined. (C) is factually incorrect and conflates a DIFFERENT concept (the trivial fact that a string has distance 0 to ITSELF) with the actual base case here (distance from EMPTY to a non-empty string, which is NOT zero in general). (D) is a fabricated and incorrect description; these are not merely 'safety' placeholder values to be overwritten &mdash; they are genuine, correct, final answers for the (0,j) and (i,0) subproblems, used directly by the recurrence to build up the rest of the table."
})

Q.append({
"q": "Which of the following is the BEST argument for why the Longest Common Subsequence problem exhibits optimal substructure, matching the formal proof style CLRS uses (via 'cut-and-paste' contradiction)?",
"opts": ["Suppose Z is a longest common subsequence (LCS) of X and Y, but its prefix Z' (with the last character removed) is NOT the longest common subsequence of the corresponding prefixes of X and Y; then there would exist a STRICTLY LONGER common subsequence Z'' of those prefixes, and appending the removed final character to Z'' would produce a common subsequence of X and Y strictly longer than Z &mdash; contradicting that Z was the LCS", "LCS trivially has optimal substructure because all dynamic programming problems automatically have this property by definition, with no proof needed", "LCS has optimal substructure only when X and Y are sorted alphabetically, otherwise the property fails", "The optimal substructure of LCS follows directly from the fact that strings are finite in length, with no need to consider prefixes or subsequences at all"],
"ans": 0,
"exp": "This is precisely the cut-and-paste argument style CLRS Theorem 14.1 formalizes: assuming for contradiction that a proper prefix of an optimal solution is NOT itself optimal for the corresponding subproblem, you show that substituting in a better subproblem solution ('pasting in' the improvement) yields a strictly better solution to the original problem, contradicting the original solution's assumed optimality &mdash; this rigorously establishes that optimal solutions to subproblems must be used within optimal solutions to the larger problem, which is the definition of optimal substructure. (B) is a dangerous oversimplification; NOT all algorithmic problems automatically have optimal substructure (the longest SIMPLE PATH problem is a classic CLRS counterexample where it FAILS), so it must be proven for each specific problem, not assumed axiomatically. (C) is a fabricated and false restriction; LCS's optimal substructure holds for ANY two strings, regardless of whether their characters happen to be in alphabetical order &mdash; sortedness is irrelevant to this proof. (D) is a non-sequitur; finiteness of the strings alone says nothing about whether optimal solutions to subproblems compose into optimal solutions to the whole problem &mdash; that requires the specific structural argument given in option A."
})

Q.append({
"q": "CLRS presents the 'longest simple path' problem as a case WITHOUT clean optimal substructure (unlike shortest path). Why does decomposing an optimal longest simple path through an intermediate vertex w NOT guarantee that the two sub-paths are themselves optimal (longest) simple paths between their respective endpoints?",
"opts": ["Because the two 'optimal' sub-paths, if chosen independently to each be the longest simple path between their endpoints, might SHARE vertices with each other, violating the SIMPLICITY (no-repeated-vertex) constraint of the combined path &mdash; so the pieces can't always be selected independently and then combined", "Because longest simple path never has any valid decomposition through intermediate vertices at all", "Because edge weights in longest-path problems are always negative, breaking the substructure argument used for shortest paths", "Because the longest simple path problem is always solvable in polynomial time, making the substructure question moot"],
"ans": 0,
"exp": "This is the exact subtlety CLRS highlights: for SHORTEST paths, if you decompose an optimal path through an intermediate vertex, the sub-paths are guaranteed to be optimal (shortest) BECAUSE shortest paths (with appropriately non-negative structure or no negative cycles) can be freely combined without conflict &mdash; but for LONGEST SIMPLE paths, the simplicity constraint (no vertex repeated) means that if you pick the longest simple path from u to w and separately the longest simple path from w to v, these two sub-paths might overlap at some vertex OTHER than w, which would make the combined path invalid (not simple) &mdash; so you cannot simply combine independently-optimal sub-paths, and the greedy 'solve subproblems optimally and combine' strategy that works for DP breaks down. (B) is false; decompositions through intermediate vertices certainly exist for longest simple paths (any path has intermediate vertices) &mdash; the issue is that these decompositions don't have the needed OPTIMAL SUBSTRUCTURE property, not that they don't exist. (C) is a fabricated and irrelevant explanation; the failure of optimal substructure here has nothing to do with edge weight signs &mdash; it's purely about the SIMPLICITY (vertex non-repetition) constraint interacting badly with independent sub-path optimization. (D) is factually false and backwards; longest simple path is actually NP-hard in general (related to the Hamiltonian path problem), which is CONSISTENT with (and indeed partially explained by) its lack of clean optimal substructure &mdash; it is emphatically not polynomial-time solvable in general."
})

Q.append({
"q": "In the Optimal Binary Search Tree (OBST) problem, given keys with access probabilities, the DP recurrence for e[i,j] (expected cost of optimal BST containing keys k&#7522;..k&#7527;) involves a term w(i,j) = sum of probabilities from i to j. Why is this w(i,j) term ADDED at every recursive split, rather than just used once?",
"opts": ["Because whichever key k&#7523; is chosen as the root of the subtree spanning i to j, EVERY key in that range has its depth increased by 1 compared to if it were the root itself, so the TOTAL additional cost across all these keys (weighted by their probabilities) is exactly w(i,j), and this must be added at EVERY level of the recursion where the subtree is 're-rooted' deeper in the overall tree", "The w(i,j) term is added multiple times purely due to a formatting convention in CLRS with no real mathematical necessity", "w(i,j) represents the total number of keys in the range, unrelated to depth or cost considerations", "The term is added because OBST always requires exactly log&#8322;n levels of recursion, and w(i,j) compensates for this fixed depth"],
"ans": 0,
"exp": "This reflects a genuinely important and often confusing aspect of the OBST recurrence: e[i,j] = min over r of (e[i,r&minus;1] + e[r+1,j] + w(i,j)), where the reasoning is that when you build a subtree spanning keys i to j with root k&#8393;, every key OTHER than k&#8393; in that range sits ONE LEVEL DEEPER than it would if it were somehow at the 'root position' of just its own sub-subtree &mdash; specifically, when a subtree becomes a CHILD of another node (rather than the overall root), every key within it incurs one additional comparison/depth level in the full tree, and since this happens recursively at every level of nesting, the w(i,j) term (sum of probabilities in the range, representing the TOTAL weighted cost of that extra depth increment for ALL keys in the range) must be added at every level where a subtree gets nested one level deeper &mdash; this cumulative addition across all recursive levels correctly captures the TOTAL expected search cost, which inherently depends on the DEPTH of each key, not just which keys are grouped together. (B) is false; this is a mathematically necessary term derivable from the definition of expected search cost as (probability &times; depth) summed over all keys, not a stylistic or formatting choice. (C) is incorrect; w(i,j) is a sum of PROBABILITIES (weighted by access frequency), not a raw count of keys, and it directly relates to the cost consequences of depth. (D) is a fabricated and false claim; OBST trees are not constrained to have exactly log&#8322;n depth (they can be, and often are for OBST specifically, quite unbalanced if that minimizes expected cost given non-uniform probabilities), so this explanation has no basis."
})

Q.append({
"q": "What is the time complexity of the standard OBST dynamic programming algorithm for n keys, and how does it compare structurally to matrix-chain multiplication's complexity?",
"opts": ["Θ(n&sup3;), structurally analogous to matrix-chain multiplication: Θ(n&sup2;) subproblems (pairs i,j) each requiring O(n) choices of root to minimize over", "Θ(n&sup2;), since OBST only needs to consider each key once as a potential root across the whole algorithm", "Θ(n log n), since OBST can be solved via a balanced-tree-construction shortcut", "Θ(2&#8319;), since all possible binary tree SHAPES must be enumerated exhaustively"],
"ans": 0,
"exp": "OBST shares the exact same complexity STRUCTURE as matrix-chain multiplication: there are Θ(n&sup2;) subproblems e[i,j] (for all valid ranges i&le;j), and for each one, up to O(n) choices of root r must be tried to find the minimum expected cost, giving Θ(n&sup2;)&times;O(n) = O(n&sup3;) total time (and this is indeed tight, Θ(n&sup3;), matching CLRS's stated bound) &mdash; this deep structural similarity (both are 'choose a split/root point over a range' DP problems) is a commonly tested conceptual connection between these two classic DP examples. (B) drastically undercounts the choices needed; while there are 'only' n keys overall, EACH of the Θ(n&sup2;) different ranges independently requires trying multiple possible roots, not just considering each key a single time globally. (C) is false; there's no known Θ(n log n) algorithm for general OBST with arbitrary probabilities (though various optimized variants like using Knuth's optimization on the choice of optimal root CAN reduce it to Θ(n&sup2;) &mdash; but not Θ(n log n)). (D) describes the naive brute-force enumeration of ALL possible tree shapes (related to the Catalan numbers, hence exponential), which is exactly the inefficiency that the DP formulation with overlapping subproblems avoids."
})

Q.append({
"q": "For the classic 'coin change: minimum number of coins' DP problem with denominations {1,3,4} and target amount 6, a GREEDY approach (always take the largest denomination that fits) gives 4+1+1=3 coins. What does the correct DP approach give, and why does greedy fail here?",
"opts": ["DP gives 3+3=2 coins, strictly better than greedy's 3-coin solution; greedy fails because it makes locally optimal choices (largest coin first) without considering how that choice affects the REMAINING amount's own optimal decomposition, and for this particular denomination set, greedy's early commitment to '4' forecloses the better '3+3' option", "DP and greedy always agree for coin change problems, so both would give 3 coins", "DP gives 6 coins (six 1s), which is worse than greedy, proving greedy is actually better in this case", "The problem has no valid DP solution since 4 doesn't evenly divide 6"],
"ans": 0,
"exp": "This is a canonical counterexample used to teach WHY greedy algorithms don't always work even when a problem has optimal substructure: with denominations {1,3,4}, greedy's rule 'always take the largest fitting coin' picks 4 first (since 4&le;6), leaving 2, which then requires two more 1-coins (since 3&gt;2), for a total of 4+1+1=3 coins; but true DP examines ALL possibilities (not just the locally-largest choice) and discovers that 3+3=6 achieves the same target with only 2 coins, which is strictly better &mdash; greedy's failure specifically stems from its irrevocable early commitment to using a 4, which then constrains the remaining sub-problem (amount=2) to a worse outcome than if a different first choice had been made. (B) is a dangerous overgeneralization; while greedy DOES happen to work correctly for certain 'nice' denomination sets (like standard currency systems: 1,5,10,25), it is NOT guaranteed to work for ARBITRARY denomination sets, and {1,3,4} targeting 6 is a standard textbook counterexample proving this. (C) is simply computationally wrong; using six 1-coins is a valid but clearly suboptimal solution, and correctly reflects neither the optimal DP answer (2 coins) nor even the greedy answer (3 coins) &mdash; it doesn't correspond to any of the algorithms described. (D) is a non-sequitur; there's no requirement that denominations evenly divide the target amount for a DP (or any correct) solution to exist &mdash; DP handles arbitrary denominations and targets, as long as making the target is possible using coins of value 1 (guaranteeing solvability here)."
})

Q.append({
"q": "In bitmask DP for the Traveling Salesman Problem (TSP), the state is typically dp[mask][i] = minimum cost to visit exactly the set of cities in 'mask', ending at city i. What is the time complexity of this approach for n cities, and why is it considered a significant improvement over brute-force despite still being exponential?",
"opts": ["Θ(n&sup2;&middot;2&#8319;) time; while still exponential, this is a massive improvement over the brute-force Θ(n!) approach (trying every permutation of cities), since 2&#8319; grows dramatically slower than n! for even moderately large n", "Θ(n log n), since bitmask DP is fundamentally a divide-and-conquer optimization technique", "Θ(2&#8319;) alone, since the number of states is the only factor that matters, with no per-state transition cost", "Θ(n!), identical to brute force, since bitmask DP still must consider every possible tour"],
"ans": 0,
"exp": "The bitmask DP approach has 2&#8319; possible subsets (masks) times n possible ending cities, giving Θ(n&middot;2&#8319;) STATES, and for each state, transitioning requires trying up to n possible 'previous city' options, giving an additional factor of n, for a total of Θ(n&sup2;&middot;2&#8319;) &mdash; while this remains exponential in n (since 2&#8319; is exponential), it represents an enormous practical improvement over the brute-force Θ(n!) approach of trying every permutation, since for even modest n (like n=20), 2&sup2;&#8304; &asymp; 10&#8310; is vastly more tractable than 20! &asymp; 2.4&times;10&#185;&#8312;, extending the practically solvable problem size considerably (this exemplifies how DP can convert an intractable brute-force exponential into a 'smaller' but still exponential complexity via avoiding REDUNDANT recomputation across overlapping subsets/states). (B) is false; bitmask DP is a DP technique exploiting overlapping subproblems (indexed by subsets), fundamentally different from divide-and-conquer's independent-subproblem structure, and it is absolutely NOT polynomial (Θ(n log n)) &mdash; TSP remains NP-hard. (C) undercounts the per-state work; simply having 2&#8319; (or n&middot;2&#8319;) states doesn't account for the WORK done to compute each state's value, which requires trying up to n transition options per state. (D) is false and misses the entire point of using DP here; while both are technically 'exponential,' 2&#8319; and n! have vastly different growth rates (n! grows much faster), and this difference is exactly why bitmask DP is a meaningful, valuable improvement, not merely a reformulation of the same brute-force complexity."
})

with open("/home/claude/mcq/dp_part_a.json", "w") as f:
    import json
    json.dump(Q, f)
print(len(Q))
