# -*- coding: utf-8 -*-
Q = []

Q.append({
"q": "For a code-tracing question: given the recursive memoized function `def f(n, memo={}): if n in memo: return memo[n]; if n<=1: return n; memo[n]=f(n-1,memo)+f(n-2,memo); return memo[n]`, what subtle Python bug exists regarding the mutable default argument `memo={}`, and what is its practical consequence?",
"opts": ["The default dictionary `memo={}` is created ONCE when the function is DEFINED (not each time it's called), so it PERSISTS across separate top-level calls to f() unless a fresh memo is explicitly passed each time &mdash; this can cause STALE or unexpectedly shared cached results across logically distinct invocations, though for a pure function like Fibonacci this happens to be harmless (even beneficial for caching) but would be dangerous if memo needed to be reset between independent uses", "This code has no bugs; mutable default arguments are always recreated fresh on each call in Python", "The code will throw a RecursionError immediately on any input due to the memo dictionary being empty", "The bug causes the function to always return 0 regardless of input, due to the memo dictionary overriding the base case"],
"ans": 0,
"exp": "This tests a classic, famous Python 'gotcha': default argument values (like `memo={}`) are evaluated exactly ONCE at function DEFINITION time, not fresh on every call, so the SAME dictionary object persists across ALL calls to f() that don't explicitly pass their own memo &mdash; for a pure, input-only-dependent function like Fibonacci, this accidental persistence is actually harmless or even a free optimization (results from previous calls remain valid and get reused), but this pattern is a well-known DANGEROUS bug in general Python code whenever the mutable default is intended to be fresh per call (e.g., if the memo needed to be cleared between uses, or if the function had side effects depending on a clean state) &mdash; this question tests recognition of the underlying Python semantics regardless of whether it happens to cause a problem in this SPECIFIC benign case. (B) is factually wrong about Python's actual default-argument evaluation semantics, which is precisely the well-documented gotcha being tested. (C) is false; the code runs correctly and does NOT crash &mdash; empty memo is a valid starting state, and the function correctly falls through to compute base cases as needed. (D) is a fabricated and incorrect failure mode with no grounding in how the code actually executes; there's no mechanism by which the memo would override the return value to always be 0."
})

Q.append({
"q": "Trace through this recursive code: `def mystery(n): if n==0: return 0; return n + mystery(n-1)`. If called with a large n WITHOUT memoization, and this were mistakenly assumed to require exponential time due to 'looking recursive like Fibonacci,' what is the ACTUAL time complexity, and why does it differ fundamentally from naive Fibonacci despite both being unmemoized recursion?",
"opts": ["Θ(n), because this function makes only ONE recursive call per invocation (not two, like Fibonacci), so there is no branching/overlap at all &mdash; it's simply a linear chain of calls, structurally nothing like the exponential-blowup pattern of naive Fibonacci", "Θ(2&#8319;), identical to naive Fibonacci, since both are recursive and unmemoized", "Θ(n&sup2;), because each call does O(n) work summing up all previous results", "Θ(log n), because recursive functions are always logarithmic unless explicitly stated otherwise"],
"ans": 0,
"exp": "This function makes exactly ONE recursive call per invocation (mystery(n&minus;1)), forming a simple linear CHAIN of n calls (mystery(n) &rarr; mystery(n&minus;1) &rarr; ... &rarr; mystery(0)), each doing O(1) additional work (the addition), giving Θ(n) total time &mdash; there is no branching, no overlapping subproblems, and no redundant recomputation, fundamentally different from Fibonacci's TWO-way branching recursive structure (F(n)=F(n&minus;1)+F(n&minus;2)) which creates an exponentially-sized call tree due to massive subproblem overlap. This question specifically tests whether students can distinguish 'this is recursive' from 'this must be exponential' &mdash; NOT all unmemoized recursion is exponential; the KEY factor is whether the recursion BRANCHES into multiple calls that overlap. (B) reflects a common but serious misconception that ALL naive recursion is automatically exponential; the branching factor and subproblem overlap are what matter, not merely 'being recursive.' (C) fabricates an incorrect complexity with no basis; each individual call does only O(1) work (a single addition), not O(n) work. (D) is a nonsensical blanket generalization; there is no such universal rule, and this specific function is clearly linear, not logarithmic, by direct inspection of its single-decrement recursive structure."
})

Q.append({
"q": "Given the matrix-chain multiplication dimension array p = [30, 35, 15, 5, 10, 20, 25] (for 6 matrices A&#8321;...A&#8326;), what is the dimension of matrix A&#8323; specifically, and how many total scalar multiplications would a NAIVE left-to-right (fully left-associative) parenthesization require, versus the true optimal (which CLRS computes as 15,125)?",
"opts": ["A&#8323; has dimensions 15&times;5 (using p[2]&times;p[3]); left-to-right naive multiplication would require substantially MORE than 15,125 multiplications (the specific naive total for this exact sequence, computable by summing p[i-1]&middot;p[i]&middot;p[6] style costs along a fixed left-associative order, is known to be significantly higher, illustrating why the choice of parenthesization dramatically affects efficiency even though the FINAL matrix product is identical regardless of association", "A&#8323; has dimensions 5&times;10, and left-to-right is always optimal for any matrix chain by definition", "A&#8323; has dimensions 35&times;15, and the naive approach always matches the optimal exactly, making DP unnecessary", "There is not enough information to determine A&#8323;'s dimensions from the array p alone"],
"ans": 0,
"exp": "By the standard convention, matrix A&#8342; has dimensions p[i&minus;1]&times;p[i], so A&#8323; (with i=3) has dimensions p[2]&times;p[3] = 15&times;5 &mdash; this dimension-indexing convention (where consecutive matrices share a 'linking' dimension, p[i], ensuring A&#8342; and A<sub>i+1</sub> are compatible for multiplication) is foundational to the entire matrix-chain DP formulation. Regarding the naive left-to-right approach: CLRS's own worked example for this EXACT dimension sequence demonstrates that different parenthesizations can require dramatically different total multiplication counts (this is literally the motivating example in CLRS Chapter 14, illustrating why finding the optimal parenthesization matters immensely for efficiency, even though mathematically every valid parenthesization computes the IDENTICAL final product due to matrix multiplication's associativity) &mdash; the optimal here is stated as 15,125, and a naive fixed-order approach can require substantially more multiplications for unfavorable dimension sequences. (B) gives a wrong dimension calculation (misindexing the p array) and additionally makes the false, sweeping claim that left-to-right is 'always optimal,' directly contradicting the entire motivating point of the matrix-chain problem. (C) gives yet another incorrect dimension pairing and falsely claims naive always matches optimal, which would make the entire DP algorithm pointless &mdash; contradicting the well-established fact that parenthesization choice matters significantly. (D) is incorrect; the dimension array p directly and completely determines every matrix's dimensions via the standard convention, so A&#8323;'s dimensions ARE fully determined by the given information."
})

Q.append({
"q": "For the Fibonacci sequence computed via BOTTOM-UP tabulation (an array fib[0..n] filled iteratively), what is the space complexity if implemented naively with a full array versus the OPTIMIZED version using just two variables, and why does this optimization NOT generalize easily to problems like LCS's full table reconstruction?",
"opts": ["Naive: Θ(n) space; optimized: Θ(1) space, since fib[i] only depends on fib[i&minus;1] and fib[i&minus;2] &mdash; this two-variable trick works because Fibonacci's dependency is on a FIXED, small, constant number of previous states, whereas problems needing full BACKTRACKING (like reconstructing the actual LCS string, not just its length) require retaining more of the table's history to trace the solution path, which the O(1)-space version discards", "Both versions always require Θ(n) space; there is no possible space optimization for Fibonacci", "The optimized version requires Θ(log n) space due to the recursive call stack, even in the iterative version", "Space optimization is impossible for any DP problem that has more than one state variable"],
"ans": 0,
"exp": "The naive bottom-up array stores all n+1 Fibonacci values, using Θ(n) space, but since fib[i] depends ONLY on the two immediately preceding values (fib[i&minus;1] and fib[i&minus;2]), you can discard older values and keep just two rolling variables, achieving Θ(1) space &mdash; however, this space-reduction trick fundamentally works because you only need the FINAL value, not any INTERMEDIATE path/choice information; problems like LCS, when the goal is to reconstruct the actual optimal SEQUENCE (not just its length), require tracing BACK through the choices made at each step, which necessitates retaining (at least) enough of the table's history to perform this backtracking &mdash; simply keeping the 'last couple of rows' as in space-optimized LENGTH-only LCS doesn't preserve the information needed to recover the actual subsequence without additional techniques (like Hirschberg's algorithm, which cleverly achieves both reconstruction AND reduced space via a divide-and-conquer approach on the DP table itself). (B) is false; Fibonacci's rolling-variable optimization is one of the most standard, well-known space optimizations in introductory DP teaching. (C) is a fabricated and internally inconsistent claim; an ITERATIVE bottom-up implementation, by definition, does not use a recursive call stack at all &mdash; conflating this with a different (top-down recursive) implementation style is a category error. (D) is an overly broad and false generalization; MANY multi-state-variable DP problems (like certain grid-based DPs, or even 2D DPs like LCS's LENGTH-only computation) DO admit space optimizations by keeping only a limited number of previous rows/columns, when the dependency structure allows it."
})

Q.append({
"q": "Consider a 2D grid DP problem: 'count the number of distinct paths from top-left to bottom-right of an m&times;n grid, moving only RIGHT or DOWN.' What is the recurrence, and how does its solution relate to the BINOMIAL COEFFICIENT C(m+n&minus;2, m&minus;1)?",
"opts": ["dp[i][j] = dp[i&minus;1][j] + dp[i][j&minus;1] (with dp[0][0]=1 and appropriate boundary handling), and the closed-form answer equals C(m+n&minus;2, m&minus;1), since any path consists of exactly (m&minus;1) DOWN moves and (n&minus;1) RIGHT moves in SOME order, and choosing WHICH positions (out of the total m+n&minus;2 moves) are DOWN moves is a combinatorial selection problem", "dp[i][j] = dp[i&minus;1][j&minus;1] + 1, with no combinatorial interpretation possible for grid path counting", "dp[i][j] = i&times;j directly, without any recursive relationship or need for a DP table at all", "The recurrence dp[i][j] = dp[i&minus;1][j] + dp[i][j&minus;1] is correct, but there is NO closed-form combinatorial equivalent; it must always be computed via the full DP table"],
"ans": 0,
"exp": "The number of ways to reach cell (i,j) is the sum of ways to reach it from ABOVE (dp[i&minus;1][j], then move down) or from the LEFT (dp[i][j&minus;1], then move right), correctly captured by dp[i][j]=dp[i&minus;1][j]+dp[i][j&minus;1] &mdash; and this DP recurrence has a beautiful and well-known CLOSED-FORM equivalent: since every valid path from top-left to bottom-right requires EXACTLY (m&minus;1) down-moves and (n&minus;1) right-moves (in some interleaved order) out of a TOTAL of (m+n&minus;2) moves, the number of distinct paths equals the number of ways to choose WHICH (m&minus;1) of those (m+n&minus;2) total move-slots are 'down' moves (the rest being 'right' by elimination), which is EXACTLY the binomial coefficient C(m+n&minus;2, m&minus;1) &mdash; this is a classic and important illustration of how DP solutions can sometimes be verified against, or even replaced by, elegant closed-form combinatorial formulas when such a formula exists. (B) fabricates an incorrect, overly simplistic recurrence that doesn't correctly model the actual TWO-WAY (from-above OR from-left) path-counting structure of the problem. (C) is a nonsensical direct-multiplication formula with no grounding in the actual combinatorics of path-counting (i&times;j does not equal the number of grid paths in general). (D) is factually incorrect; while the recurrence IS correct as stated, this is precisely a case where a clean closed-form DOES exist (the binomial coefficient), demonstrating that DP and combinatorial closed-forms are often two equivalent ways of solving the same underlying counting problem, not mutually exclusive approaches."
})

Q.append({
"q": "For the same grid-path-counting DP, if certain cells are marked as OBSTACLES (impassable), how must the recurrence be modified, and why does this modification BREAK the clean binomial-coefficient closed form from the unobstructed case?",
"opts": ["dp[i][j] = 0 if cell (i,j) is an obstacle, else dp[i&minus;1][j] + dp[i][j&minus;1] (with appropriate boundary handling); this breaks the closed form because the binomial-coefficient formula assumed EVERY possible interleaving of moves was a VALID path, but obstacles selectively INVALIDATE specific paths in a way that generally has no simple combinatorial closed-form expression, especially when obstacle positions are arbitrary", "Obstacles have no effect on the recurrence; the same binomial coefficient formula still applies regardless of obstacle placement", "dp[i][j] must be multiplied by &minus;1 for obstacle cells, preserving the closed-form solution exactly", "Obstacles make the problem unsolvable by dynamic programming; only exhaustive path enumeration works"],
"ans": 0,
"exp": "The natural and correct modification sets dp[i][j]=0 for any obstacle cell (since no valid path can pass through it, contributing zero ways to reach further cells via that position), while non-obstacle cells still sum contributions from above and left (using the now-corrected zeroed-out values for blocked neighbors) &mdash; this modification is precisely why the elegant closed-form binomial coefficient (which counts ALL possible move-orderings without regard to obstacles) no longer applies: the combinatorial formula fundamentally assumed every interleaving of down/right moves traces a VALID path, but once certain grid cells are forbidden, SPECIFIC move-orderings become invalid (those that would pass through a blocked cell), and there's no simple, general closed-form expression for 'count binomial arrangements EXCLUDING those that hit an arbitrary set of forbidden points' &mdash; this beautifully illustrates a broader principle in DP: adding CONSTRAINTS to a problem can destroy an existing closed-form solution while the DP recurrence itself remains easily adaptable (just add a conditional check), which is exactly why DP's flexibility is often preferred over closed-form combinatorics for problems with irregular constraints. (B) is false and represents a serious misunderstanding of how obstacles fundamentally change which paths are valid, hence changing the resulting COUNT. (C) is a fabricated and mathematically nonsensical modification (multiplying by &minus;1 would produce meaningless negative path counts, and doesn't correspond to any correct handling of obstacles). (D) is false; the modified DP approach (setting obstacle cells to 0) is a well-known, efficient, and entirely standard solution &mdash; exhaustive enumeration is unnecessary and dramatically less efficient."
})

Q.append({
"q": "In subset-sum DP (determine if some subset of a given set sums to exactly target T), the boolean DP table is dp[i][s] = True if some subset of the first i elements sums to exactly s. What is the base case dp[i][0] for ALL i (including i=0), and why is this seemingly 'trivial' base case actually crucial for correctness?",
"opts": ["dp[i][0] = True for all i, including i=0, because the EMPTY subset (choosing NONE of the available elements) always sums to exactly 0, regardless of how many elements are available to choose from; this must be correctly initialized, or the recurrence (which builds on dp[i-1][s] and dp[i-1][s-a_i]) would incorrectly propagate False for achievable sums that rely on 'not including' certain elements to reach 0 partway through a larger sum calculation", "dp[i][0] = False for all i, since a sum of exactly 0 is impossible to achieve with any nonempty or empty subset", "dp[i][0] is undefined and must be explicitly excluded from the table entirely", "dp[i][0] = True only when i=0, and False for all i&gt;0, since larger subsets can never sum to 0"],
"ans": 0,
"exp": "The base case dp[i][0]=True for EVERY i (not just i=0) reflects the simple but crucial fact that the EMPTY subset (selecting zero elements from whatever pool of i elements is available) always achieves a sum of exactly 0, no matter how many elements you have access to &mdash; this must be correctly set as a TRUE base case across the entire first column of the table, because the general recurrence dp[i][s] = dp[i&minus;1][s] OR (dp[i&minus;1][s&minus;a&#7522;] if s&ge;a&#7522;) relies on being able to correctly look up dp[i&minus;1][0]=True whenever a partial sum calculation needs to confirm that 'sum=0 is achievable using a subset of the first i&minus;1 elements' (which is always trivially true via the empty selection) &mdash; getting this base case wrong (e.g., only setting dp[0][0]=True and leaving dp[i][0] for i&gt;0 uninitialized or False) would cause the recurrence to incorrectly report FALSE for various achievable sums that depend on this lookup. (B) is factually incorrect and reflects a serious misunderstanding; a sum of exactly 0 is ALWAYS trivially achievable via the empty subset, for any i, making this a TRUE base case, not False. (C) is an evasive non-answer; the base case is both well-defined and essential to state explicitly for the recurrence to function correctly. (D) incorrectly restricts the True base case to ONLY i=0, but the recurrence's correctness for i&gt;0 typically depends on ALSO having dp[i][0]=True (not just dp[0][0]) readily available at each row, since the empty-subset-sums-to-zero fact holds independently of how many elements are available to potentially include."
})

Q.append({
"q": "What is the time and space complexity of the subset-sum DP for n elements and target sum T, and why is this considered PSEUDO-polynomial (similar to 0/1 Knapsack)?",
"opts": ["Θ(nT) time and Θ(nT) space (reducible to Θ(T) space via rolling rows); pseudo-polynomial because T's numeric MAGNITUDE (not its bit-length, log&#8322;T) directly determines the running time, so for exponentially large T (relative to its bit representation), the algorithm's true runtime relative to INPUT SIZE becomes exponential", "Θ(n log T) time, fully polynomial, since T only contributes a logarithmic factor", "Θ(2&#8319;) time always, since subset-sum inherently requires trying all 2&#8319; possible subsets", "Θ(n&sup2;) time, independent of T entirely, since T only affects space, not time"],
"ans": 0,
"exp": "Subset-sum's DP table has dimensions (n+1)&times;(T+1), with O(1) work per cell, giving Θ(nT) time and space (reducible to Θ(T) space via the same rolling-row/careful-iteration-order techniques discussed for 0/1 Knapsack) &mdash; and exactly like Knapsack, this is PSEUDO-polynomial because T contributes to the running time based on its VALUE, not the number of BITS needed to represent it (which would be Θ(log T)); if T is specified as an extremely large number requiring only a modest number of bits to encode (e.g., a 128-bit integer representing an astronomically large target), the Θ(nT) algorithm becomes impractically slow despite the INPUT SIZE (in bits) being small, which is the technical definition of pseudo-polynomial time and directly relates to subset-sum's status as NP-complete in the weak sense. (B) fabricates an incorrect, overly optimistic polynomial time bound; there's no known algorithm achieving Θ(n log T) for exact subset-sum in general (that would imply a truly polynomial algorithm for an NP-complete problem, which is not known/believed to exist). (C) describes the naive brute-force approach (trying all subsets), which is exactly what the pseudo-polynomial DP AVOIDS via exploiting overlapping subproblems &mdash; conflating the two approaches misses the entire point of using DP here. (D) incorrectly claims independence from T for the TIME complexity; T directly and substantially affects both time and space in this DP formulation, since the table's width scales with T."
})

Q.append({
"q": "Which of these statements about the WEIGHTED INTERVAL SCHEDULING DP problem is CORRECT regarding why a greedy 'earliest finish time first' approach (which works for the UNWEIGHTED version) fails once weights are introduced?",
"opts": ["With weights, a job with a very high weight but a slightly later finish time might be far more valuable to include than several lower-weight jobs with earlier finish times, so greedily prioritizing EARLIEST FINISH alone (ignoring weight entirely) can lead to a SUBOPTIMAL total weight, whereas the correct DP approach (sorting by finish time, then using p(j) = the last job compatible with j, with recurrence OPT(j)=max(OPT(j&minus;1), w&#7527;+OPT(p(j)))) correctly considers BOTH options (include or exclude each job) at every step", "Greedy earliest-finish-time still works perfectly even with weights, since finish time alone always determines optimal scheduling regardless of value", "The weighted version cannot be solved by DP at all; it requires integer linear programming instead", "Weights only affect the FINAL total sum reported, not which specific jobs are selected, so greedy selection remains correct with weights simply summed at the end"],
"ans": 0,
"exp": "The unweighted interval scheduling problem is a classic case where greedy (earliest finish time) provably achieves the optimal MAXIMUM NUMBER of non-overlapping jobs, but once JOB WEIGHTS (values) are introduced, this greedy strategy is no longer guaranteed optimal, since it's entirely possible for a single high-weight job to be worth MORE than several lower-weight jobs combined, even if greedy would have selected those several smaller jobs first due to their earlier finish times &mdash; the correct approach uses DP: after sorting jobs by finish time and precomputing p(j) (the index of the latest job that doesn't conflict with job j), the recurrence OPT(j) = max(OPT(j&minus;1), w&#7527;+OPT(p(j))) correctly considers, for EACH job in sorted order, both the option of EXCLUDING it (inheriting OPT(j&minus;1)) and INCLUDING it (adding its weight to the best compatible solution before it, OPT(p(j))), guaranteeing the true optimal total weight is found by exhaustively (but efficiently, via DP) considering all relevant combinations. (B) is false and represents a serious failure to recognize that weight fundamentally changes the OPTIMALITY criterion away from simple job COUNT, breaking the guarantees that made the unweighted greedy approach correct. (C) is false; this is one of the most standard and classic DP problems taught specifically to illustrate how DP EXTENDS a simpler greedy-solvable problem to handle a more general (weighted) version &mdash; it absolutely does NOT require abandoning DP for integer linear programming. (D) is deeply incorrect; weights fundamentally change WHICH SPECIFIC set of jobs is optimal to select, not merely how the final numeric total is computed &mdash; the actual selected job set can be entirely different once weights are considered."
})

Q.append({
"q": "For the weighted interval scheduling recurrence OPT(j) = max(OPT(j&minus;1), w&#7527;+OPT(p(j))), what determines whether job j is INCLUDED in an optimal solution, based on comparing the two terms, and what does p(j) precisely represent?",
"opts": ["Job j is included if and only if w&#7527;+OPT(p(j)) &gt; OPT(j&minus;1) (strictly better to include it, given the best achievable using only jobs compatible with j); p(j) is the LARGEST index i&lt;j such that job i's finish time is &le; job j's start time (i.e., the latest job that doesn't overlap/conflict with job j)", "Job j is always included if its weight w&#7527; is positive, regardless of any comparison with other options", "p(j) represents the total number of jobs that conflict with job j, used purely for counting purposes", "Job j is included based on a coin flip in the randomized version of this algorithm, since the deterministic version doesn't exist"],
"ans": 0,
"exp": "The recurrence's max() directly encodes the fundamental DP decision at each job j: EXCLUDE job j (yielding OPT(j&minus;1), the best solution considering only the first j&minus;1 jobs) versus INCLUDE job j (yielding w&#7527; PLUS the best solution among jobs compatible with j, which is OPT(p(j)) since p(j) is defined as the latest-indexed job that finishes before j starts, i.e., doesn't conflict with j) &mdash; whichever term is larger determines the optimal choice for that specific subproblem, and p(j) is precisely this 'latest non-conflicting predecessor' index, typically precomputed via binary search (since jobs are sorted by finish time) in O(log n) per job, contributing to an overall O(n log n) algorithm. (B) is a naive and incorrect greedy-style rule that ignores the actual comparison needed; a job should NOT be automatically included just because its weight is positive &mdash; it might conflict with an even MORE valuable combination of other jobs. (C) is a fabricated and incorrect definition; p(j) is specifically about finding the ONE latest compatible predecessor job (a single index), not a count of conflicting jobs. (D) is absurd and irrelevant; this is a standard DETERMINISTIC DP algorithm with a well-defined, provably correct decision rule at each step, with no randomization involved."
})

Q.append({
"q": "Consider the 'palindrome partitioning: minimum cuts' DP problem (find minimum number of cuts to partition a string into palindromic substrings). Why does this problem typically require a TWO-PHASE DP approach (first precomputing which substrings ARE palindromes, then computing minimum cuts), rather than a single unified DP pass?",
"opts": ["Checking whether an arbitrary substring is a palindrome naively takes O(length) time, and doing this check REPEATEDLY inside the minimum-cuts recurrence (without precomputation) would multiply the overall complexity unnecessarily; precomputing a 2D boolean table isPalin[i][j] in O(n&sup2;) time upfront allows each subsequent palindrome-check during the cuts-DP to be an O(1) lookup instead, keeping the overall complexity at O(n&sup2;) instead of a worse O(n&sup3;)", "A two-phase approach is used purely for code readability, with no actual effect on time complexity", "Single-phase DP is mathematically impossible for this problem due to a logical contradiction in the recurrence", "The two phases are needed because palindrome-checking and cut-counting are unrelated problems that happen to share the same input string by coincidence"],
"ans": 0,
"exp": "This reflects a genuinely important DP OPTIMIZATION TECHNIQUE (precomputation/preprocessing to avoid redundant repeated sub-computations): if you tried to check palindrome status NAIVELY (via a direct character-by-character comparison, itself an O(length) operation) EVERY time it's needed within the minimum-cuts DP recurrence (which itself considers O(n&sup2;) substring possibilities, and for EACH one might need a palindrome check), you'd get an overall complexity multiplied by this extra factor, potentially reaching O(n&sup3;); by first precomputing a table isPalin[i][j] (indicating whether the substring from i to j is a palindrome) using ITS OWN efficient DP recurrence (isPalin[i][j] = (s[i]==s[j]) AND isPalin[i+1][j&minus;1], itself just O(n&sup2;) states with O(1) work each), all SUBSEQUENT lookups during the cuts-computation phase become O(1), keeping the combined two-phase approach at a better overall O(n&sup2;) time complexity &mdash; this pattern (precompute one DP table, then use it to accelerate a second DP) is a common and valuable technique across many DP problems. (B) drastically understates the significance; this genuinely affects the TIME COMPLEXITY (potentially O(n&sup2;) versus O(n&sup3;)), not merely code organization/style. (C) is false; there is no logical contradiction preventing a single-phase approach &mdash; it's simply LESS EFFICIENT (or would require inlining an O(n) check at every step, degrading complexity), not impossible. (D) is incorrect and misses the crucial DEPENDENCY between the two phases; the cuts-DP explicitly RELIES ON the palindrome-check results as a necessary INPUT/subroutine, they are not merely coincidentally related problems sharing input."
})

Q.append({
"q": "In a code-tracing scenario, given the recurrence isPalin[i][j] = (s[i]==s[j]) AND isPalin[i+1][j&minus;1] for the palindrome-precomputation table, what critical base/edge cases must be handled SEPARATELY, and why does naive application of this formula fail for very short substrings?",
"opts": ["Substrings of length 1 (i==j) are trivially palindromes (isPalin[i][i]=True) and substrings of length 2 (j==i+1) require checking ONLY s[i]==s[j] (since isPalin[i+1][j-1] would reference an INVALID range where i+1&gt;j&minus;1, i.e., an empty or nonsensical range); without handling these separately, the formula would either access out-of-bounds/undefined table entries or incorrectly require satisfying a condition on a non-existent inner substring", "No special handling is needed; the general formula works correctly for all substring lengths including length 1 and 2 without modification", "Only length-1 substrings need special handling; length-2 substrings are automatically handled correctly by the general formula", "The formula is entirely wrong and should instead just check s[i]==s[j] without any recursive inner-substring dependency at any length"],
"ans": 0,
"exp": "The general recurrence isPalin[i][j]=(s[i]==s[j]) AND isPalin[i+1][j&minus;1] implicitly assumes a well-defined 'inner' substring from i+1 to j&minus;1 exists to check &mdash; but for LENGTH-1 substrings (i==j), there's no meaningful comparison to make (a single character is trivially a palindrome), and for LENGTH-2 substrings (j=i+1), the 'inner' range i+1 to j&minus;1 becomes i+1 to i, which is an EMPTY (and thus invalid/out-of-bounds if not handled) range since i+1&gt;i; these cases must be explicitly special-cased (isPalin[i][i]=True always, and isPalin[i][i+1]=(s[i]==s[i+1]) directly, without recursing into a nonexistent inner substring) before the general formula can be safely applied for longer substrings (length&ge;3), where the inner range i+1 to j&minus;1 is guaranteed to be valid and well-defined. (B) is factually incorrect and represents a failure to recognize a genuinely necessary edge case; without this special handling, table lookups for these short lengths would be undefined/incorrect. (C) is incomplete; BOTH length-1 AND length-2 cases require special handling, not just one of them, since both involve degenerate or non-existent 'inner' substring references. (D) is an overly simplistic and INCORRECT alternative that discards the genuinely necessary recursive structure needed for longer palindromes (checking only the endpoints, without the AND isPalin[i+1][j-1] condition, would incorrectly classify strings like 'abca' as palindromic based on endpoints alone, when the middle characters must also form a palindrome)."
})

Q.append({
"q": "For the 'Egg Drop Puzzle' (find minimum number of trials needed in the worst case to determine the critical floor, given k eggs and n floors), the classic DP recurrence is dp[k][n] = 1 + min over x of max(dp[k&minus;1][x&minus;1], dp[k][n&minus;x]). What do the two terms inside max() represent, and why is MAX (not min) used between them?",
"opts": ["dp[k&minus;1][x&minus;1] represents the WORST CASE if the egg BREAKS when dropped from floor x (using one fewer egg, searching the x&minus;1 floors below); dp[k][n&minus;x] represents the WORST CASE if the egg SURVIVES (same number of eggs, searching the n&minus;x floors above); MAX is used because you must plan for the WORST-CASE outcome of the drop (you don't control whether it breaks or survives, so you must guarantee success regardless of which happens)", "Both terms represent the BEST case, and MAX is a typo; it should be MIN, representing optimistic planning", "dp[k&minus;1][x&minus;1] and dp[k][n&minus;x] are always equal by symmetry, so the choice between max and min never actually matters", "The two terms represent trying the SAME floor twice with different eggs, and MAX ensures redundant verification"],
"ans": 0,
"exp": "This recurrence directly encodes the two possible OUTCOMES of dropping an egg from floor x: either the egg BREAKS (in which case you've learned the critical floor is BELOW x, and must continue searching the x&minus;1 floors below using one FEWER egg, since one just broke &mdash; giving dp[k&minus;1][x&minus;1]), or the egg SURVIVES (in which case the critical floor is AT or ABOVE x, and you continue searching the remaining n&minus;x floors above, still with all k eggs since none broke &mdash; giving dp[k][n&minus;x]); since you cannot control or predict which outcome occurs on any given drop, you must plan for the WORST CASE (whichever outcome requires MORE additional trials), hence taking the MAX of the two &mdash; and then, since you get to CHOOSE which floor x to drop from, you take the MIN over all possible choices of x to find the best (minimum worst-case) strategy, giving the full recurrence's outer min-over-x combined with the inner max-of-outcomes structure. (B) is factually incorrect; you don't get to assume optimistic outcomes &mdash; the adversarial/worst-case framing of the problem (guaranteeing success regardless of when the egg breaks) is exactly why MAX (not MIN) is used for the two branch outcomes. (C) is false in general; dp[k&minus;1][x&minus;1] and dp[k][n&minus;x] are generally NOT equal (they depend on different remaining floor counts and different numbers of remaining eggs), and the specific VALUE of x is deliberately chosen (via the outer min) partly to balance/minimize this max, which would be meaningless if the two terms were always trivially equal. (D) is a fabricated and nonsensical interpretation with no connection to the actual mechanics of the egg-drop problem, which involves a SINGLE drop's binary outcome (break or survive), not two separate drops from the same floor."
})

Q.append({
"q": "What is the time complexity of the direct DP implementation of the Egg Drop recurrence for k eggs and n floors (dp[k][n] = 1+min over x of max(dp[k&minus;1][x&minus;1], dp[k][n&minus;x])), and what alternative formulation (reframing the DP state) achieves a better complexity?",
"opts": ["Direct implementation: O(k&middot;n&sup2;) time, due to trying every floor x (O(n) choices) for each of the O(kn) states; an alternative formulation using dp[k][trials] = MAXIMUM floors distinguishable with k eggs and a given number of trials achieves O(kn) or better, by reframing the problem to avoid the inner search over x entirely", "Both formulations are always O(kn) with no meaningful complexity difference between them", "The direct implementation is O(k+n), since it only considers linear factors", "There is only one possible formulation of this problem; no alternative DP state definition exists"],
"ans": 0,
"exp": "The direct recurrence, as stated, has O(kn) distinct (k,n) states, and for EACH state, must try up to O(n) different floor choices x to find the minimizing option, giving O(k&middot;n&sup2;) total time (this can be improved to O(kn log n) using binary search on x, since dp[k&minus;1][x&minus;1] increases and dp[k][n&minus;x] decreases as x increases, making the max of the two roughly unimodal/searchable) &mdash; but a cleverer REFRAMING of the DP state entirely avoids this inner search: instead of asking 'minimum trials for n floors,' define dp[k][t] = the MAXIMUM number of floors distinguishable using k eggs and AT MOST t trials, with the recurrence dp[k][t] = dp[k&minus;1][t&minus;1] + dp[k][t&minus;1] + 1 (combining the floors coverable if the egg breaks, if it survives, plus the current floor itself), which requires only O(kn) (or O(k&middot; the actual max needed trials, often much smaller than n) states with O(1) work each, then finding the smallest t such that dp[k][t]&ge;n, achieving a SIGNIFICANTLY better overall complexity &mdash; this exemplifies a broader and important DP technique of REFRAMING what the DP state represents to expose a more efficient recurrence. (B) is false; the alternative formulation provides a genuine and substantial complexity improvement, not a negligible difference. (C) drastically and incorrectly underestimates the direct approach's complexity, ignoring the necessary inner search over floor choices entirely. (D) is false and reflects a limited view of DP problem-solving; REFRAMING what the DP state represents (here, switching from 'floors&rarr;trials' to 'trials&rarr;max floors') is a genuinely powerful and commonly used technique across many DP problems, not a nonexistent option."
})

Q.append({
"q": "Which statement BEST explains why Dijkstra's shortest-path algorithm is generally classified as GREEDY rather than dynamic programming, despite shortest-path problems having optimal substructure (a property DP relies on)?",
"opts": ["Dijkstra's algorithm makes an irrevocable GREEDY choice at each step (permanently finalizing the shortest distance to the closest unvisited vertex, without reconsidering that choice later) rather than exploring/combining multiple possible subproblem solutions and choosing the best AFTER solving them, which is the hallmark DP approach; Dijkstra works correctly as greedy specifically because non-negative edge weights guarantee that once a vertex's shortest distance is finalized, it can never be improved by a LATER-discovered path", "Dijkstra's algorithm doesn't actually use optimal substructure at all, unlike DP algorithms", "The classification is arbitrary and historically inconsistent; Dijkstra's could equally correctly be called a DP algorithm with no meaningful distinction", "Dijkstra's algorithm is actually a DP algorithm, and calling it 'greedy' is simply an outdated or incorrect naming convention"],
"ans": 0,
"exp": "This tests the nuanced relationship between greedy algorithms and DP: BOTH rely on optimal substructure, but they differ in HOW they exploit it &mdash; DP-style approaches (like Bellman-Ford, which handles negative edges) explore MULTIPLE possible ways to reach each vertex and relax/update distances repeatedly as better paths are discovered, essentially computing and comparing several subproblem solutions; Dijkstra's, by contrast, makes a single GREEDY, IRREVOCABLE commitment at each step (permanently finalizing the shortest-known distance to whichever unvisited vertex currently has the smallest tentative distance), never reconsidering that choice &mdash; this greedy strategy is PROVABLY correct specifically because non-negative edge weights guarantee that no future-discovered path could ever provide a SHORTER route to an already-finalized vertex (a path through unvisited vertices can only ADD non-negative weight, never reduce total distance), which is precisely the 'greedy-choice property' that justifies never revisiting a decision. (B) is false; shortest-path problems (including those Dijkstra's solves) absolutely DO exhibit optimal substructure (a shortest path's sub-paths are themselves shortest paths) &mdash; that's not what distinguishes greedy from DP here. (C) dismisses a genuinely meaningful and well-established algorithmic distinction (greedy vs. DP) that CLRS and the broader algorithms community carefully and consistently draws, based on precisely the mechanism described in option A. (D) is factually incorrect; while greedy and DP are related (both exploit optimal substructure), Dijkstra's specific ALGORITHM STRUCTURE (irrevocable, single-choice-per-step) is the defining characteristic of greedy algorithms, not DP's characteristic approach of exploring/comparing multiple subproblem solutions."
})

Q.append({
"q": "Consider Bellman-Ford's DP-style relaxation-based shortest path algorithm, which (unlike Dijkstra's) correctly handles NEGATIVE edge weights. Why does Bellman-Ford need to perform relaxation passes exactly |V|&minus;1 times (not more, not fewer, in the standard formulation) to guarantee correctness for graphs without negative cycles?",
"opts": ["Any shortest path in a graph with V vertices (and no negative cycles) contains AT MOST |V|&minus;1 edges (since a simple path can visit each of the V vertices at most once, using at most V&minus;1 edges to connect them); each full relaxation PASS guarantees correctly computing all shortest paths using AT MOST one additional edge compared to the previous pass, so |V|&minus;1 passes suffice to correctly propagate information across the longest possible shortest path", "The number |V|&minus;1 is an arbitrary heuristic choice with no mathematical justification, chosen simply because it tends to work well in practice", "Bellman-Ford actually requires exactly |E| passes (number of edges), not |V|&minus;1 passes, and the standard textbook description is a simplification that happens to work by coincidence", "|V|&minus;1 passes are needed because that's exactly how many vertices need to be individually removed from consideration during the algorithm's execution"],
"ans": 0,
"exp": "This is a precise, provable mathematical guarantee (proven via induction in CLRS): since a SIMPLE shortest path in any graph (with no negative-weight cycles, which would otherwise make 'shortest path' undefined by allowing arbitrarily negative totals via repeated cycling) can use AT MOST |V|&minus;1 edges (because a simple path visits each of the |V| vertices at most once, and connecting k vertices in sequence requires at most k&minus;1 edges), Bellman-Ford's relaxation process is proven (by induction on the number of passes) to correctly compute the shortest distance using paths of AT MOST i edges after the i-th pass &mdash; so after |V|&minus;1 complete passes, ALL shortest paths (which use at most |V|&minus;1 edges, per the argument above) are guaranteed to have been correctly computed, making further passes UNNECESSARY (though a |V|-th pass is often added specifically as a NEGATIVE-CYCLE DETECTION mechanism: if distances STILL improve on this extra pass, a negative cycle must exist, since otherwise convergence would have already occurred). (B) is false; this is a precisely PROVEN bound via a rigorous inductive argument about the maximum possible length of simple shortest paths, not an empirical heuristic. (C) is factually incorrect; the standard, provably correct formulation is |V|&minus;1 passes, not |E| passes &mdash; conflating these two different graph-size parameters reflects a misunderstanding of the actual complexity/correctness argument. (D) is a fabricated and incorrect mechanism; the algorithm doesn't 'remove' vertices from consideration in this sense &mdash; it repeatedly relaxes ALL edges across the ENTIRE graph in each pass, and the |V|&minus;1 count relates to maximum SIMPLE PATH LENGTH, not vertex removal."
})

Q.append({
"q": "For the 'Word Break' DP problem (determine if a string can be segmented into space-separated dictionary words), the recurrence is dp[i] = True if there exists some j&lt;i such that dp[j]=True AND s[j..i&minus;1] is in the dictionary. What is the WORST-CASE time complexity, assuming O(1) dictionary lookup (via a hash set) but accounting for substring EXTRACTION cost?",
"opts": ["O(n&sup3;) in a naive implementation, because there are O(n) values of i, each requiring trying O(n) values of j, and EACH such (i,j) pair requires an O(n) substring extraction (e.g., s[j:i] in many languages creates a NEW string of length up to n) before the O(1) hash lookup can even occur &mdash; this substring-copying cost, often overlooked, can dominate the complexity", "O(n&sup2;) always, since substring extraction is universally an O(1) operation in all programming languages", "O(n), since dictionary lookup is O(1) and there's no other significant cost", "O(2&#8319;), since Word Break requires checking all possible ways to segment the string exhaustively without any DP structure"],
"ans": 0,
"exp": "This tests a subtle but practically important complexity trap: while the DP STATE SPACE is O(n) (positions i) and the TRANSITION considers O(n) choices of j per state (giving a naively expected O(n&sup2;) DP structure), many implementations OVERLOOK that extracting a substring s[j:i] in languages where strings are immutable and substring operations COPY the underlying characters (common in Python, Java, and others, unless specific optimizations/views are used) itself costs O(i&minus;j) time, which can be up to O(n) in the worst case &mdash; multiplying this into the O(n&sup2;) DP structure gives a WORST-CASE O(n&sup3;) TOTAL complexity if this substring-extraction cost isn't carefully accounted for or optimized away (e.g., via using string hashing, or a Trie-based dictionary check that avoids full substring materialization). This question specifically tests whether students recognize that 'the dictionary lookup is O(1)' does NOT automatically mean 'the whole operation involving that lookup is O(1)' &mdash; the cost of PREPARING the input to the lookup (substring extraction) must also be counted. (B) is factually wrong about substring extraction being universally O(1); this depends heavily on the specific language/data structure (e.g., some specialized string-view or rope-based implementations CAN achieve O(1) or O(log n) substring access, but this is NOT the default/universal case, especially for standard string types in common languages). (C) drastically underestimates the complexity by ignoring BOTH the O(n) choices of j per state AND the substring extraction cost entirely. (D) incorrectly claims Word Break has no DP structure at all, contradicting the explicitly given DP recurrence in the question itself, and fabricates an unrelated exponential complexity that doesn't match the actual (polynomial, if properly analyzed) nature of this classic DP problem."
})

Q.append({
"q": "In the 'Maximum Product Subarray' DP problem, why must the recurrence track BOTH the maximum AND minimum product ending at each position (maxEnd[i] and minEnd[i]), rather than just tracking the maximum (as would suffice for Kadane's maximum SUM subarray)?",
"opts": ["Because multiplying by a NEGATIVE number can turn the current MINIMUM (most negative) product into the new MAXIMUM (by flipping its sign to positive), so failing to track the running minimum means potentially missing the optimal solution when a negative number appears; this is a fundamental structural difference from the SUM version, where multiplying (which doesn't apply to sums) never causes this sign-flipping interaction", "Tracking the minimum is an unnecessary optimization with no effect on correctness, only on performance", "The minimum is tracked purely for reporting purposes at the end, not because it affects the recurrence's correctness during computation", "Products can never be negative in this problem, so 'minimum' always just refers to the smallest positive value, unrelated to sign considerations"],
"ans": 0,
"exp": "This is THE defining insight that distinguishes Maximum Product Subarray from the simpler Maximum SUM Subarray (Kadane's algorithm): because MULTIPLICATION (unlike addition) can flip signs, a sequence like [..., large_negative, negative_number] can produce a LARGE POSITIVE product when the negative_number multiplies with the large_negative value &mdash; meaning the BEST maximum-product-ending-here might actually come from extending the WORST (most negative) product-ending-at-the-previous-position, not the best one; therefore the correct recurrence must maintain BOTH maxEnd[i] and minEnd[i] at every step, computing maxEnd[i] = max(A[i], A[i]&times;maxEnd[i&minus;1], A[i]&times;minEnd[i&minus;1]) (and similarly minEnd[i] considering the same three candidates but taking the min), since you genuinely cannot know in advance which of maxEnd[i&minus;1] or minEnd[i&minus;1], when multiplied by a potentially-negative A[i], will yield the better result &mdash; this sign-flipping phenomenon has NO analog in the pure-SUM version, where adding a negative number simply decreases the value without ever converting a 'worst' running sum into a 'best' one via multiplication's sign-inversion property. (B) is false and represents a serious misunderstanding; omitting the minimum tracking can cause the algorithm to produce an INCORRECT (too low) answer, not merely a slower one &mdash; specific test cases with negative numbers would fail without this tracking. (C) is incorrect; the minimum is used ACTIVELY DURING the recurrence's computation at every step (as a potential source for the NEXT maximum, via sign-flipping), not merely reported passively at the end. (D) is factually wrong; products in this problem absolutely CAN be negative (whenever an odd number of negative factors are multiplied together), and the entire point of tracking the minimum relates directly to this sign consideration, not merely finding 'the smallest positive value.'"
})

Q.append({
"q": "For 'Regular Expression Matching' via DP (supporting '.' for any single character and '*' for zero-or-more of the preceding element), what makes the handling of the '*' character SIGNIFICANTLY more complex than the '.' character in the DP recurrence?",
"opts": ["'.' simply means 'match any single character,' requiring a straightforward diagonal-style dependency (dp[i][j] depends on dp[i&minus;1][j&minus;1]); '*' means 'zero or more of the PRECEDING character,' requiring the recurrence to consider BOTH the possibility of using ZERO occurrences (skip the preceding-char+* pattern entirely, dp[i][j&minus;2]) AND the possibility of using ONE OR MORE occurrences (which requires the preceding pattern character to match the current text character, then recursively checking dp[i&minus;1][j], allowing the '*' to consume MULTIPLE text characters via this same-column recursive reference)", "Both '.' and '*' are handled with the exact same complexity; there is no meaningful difference between them in the recurrence's structure", "'*' is actually SIMPLER than '.' because it always matches everything, requiring no conditional logic at all", "The recurrence cannot handle '*' at all; regex matching with '*' requires abandoning DP entirely in favor of a different algorithmic paradigm like NFA simulation"],
"ans": 0,
"exp": "The '.' character has simple, LOCAL semantics (match exactly one arbitrary character), fitting naturally into a straightforward diagonal DP dependency similar to basic string matching; the '*' character, by contrast, has fundamentally more complex semantics tied to REPETITION of the PRECEDING pattern element, requiring the recurrence to branch into two genuinely different cases: (1) treat the preceding-element+* combination as matching ZERO times (effectively SKIPPING both characters in the pattern, referencing dp[i][j&minus;2]), or (2) treat it as matching ONE OR MORE times, which requires the preceding pattern element to successfully match the CURRENT text character (via '.' or exact match), and then recursively check dp[i&minus;1][j] (NOT dp[i&minus;1][j&minus;1] or dp[i][j-2]) &mdash; crucially staying at the SAME pattern position j (since '*' can be reused to match ADDITIONAL text characters), which is what allows this recurrence to correctly handle patterns like 'a*' matching 'aaaa' (repeatedly consuming text characters while remaining at the same point in the pattern). This dual-case branching (zero vs. one-or-more, with the one-or-more case having a same-column self-referential dependency) is precisely what makes '*' handling substantially trickier than '.'  handling. (B) is false and understates the genuine additional complexity that '*' introduces via its repetition semantics, which '.' entirely lacks. (C) is factually backwards and incorrect; '*' does NOT 'always match everything' &mdash; it specifically means repetition of the PRECEDING element, requiring careful conditional handling, not a trivial universal match. (D) is false; DP-based regex matching (for this specific restricted subset of regex features: '.' and '*') IS a well-established, correct, and standard technique &mdash; it does not require abandoning DP for NFA simulation, though NFA-based approaches are an alternative valid technique for MORE GENERAL regex features."
})

Q.append({
"q": "Which of the following best describes the relationship between DYNAMIC PROGRAMMING and MEMOIZED RECURSION in terms of implementation, using CLRS's own framing?",
"opts": ["Memoized recursion IS a form of dynamic programming (specifically, the 'top-down' variant), maintaining the natural recursive structure of the problem while adding a cache/table to avoid recomputing already-solved subproblems, in contrast to 'bottom-up' DP, which iteratively fills the table in a carefully chosen dependency-respecting order without explicit recursive calls", "Memoized recursion and dynamic programming are entirely unrelated techniques that happen to solve similar-looking problems by coincidence", "Dynamic programming NEVER uses recursion under any circumstances; all DP algorithms must be purely iterative by definition", "Memoized recursion is strictly FASTER than bottom-up DP in all cases, which is why CLRS recommends always preferring it"],
"ans": 0,
"exp": "CLRS explicitly presents memoization (top-down) and tabulation (bottom-up) as the TWO standard ways of implementing dynamic programming, both exploiting the same underlying optimal-substructure and overlapping-subproblems properties &mdash; memoized recursion preserves the problem's natural top-down recursive formulation but adds a cache (memo table) checked at the start of each call to avoid redoing work for previously-solved subproblems, while bottom-up tabulation instead builds the solution iteratively from smaller subproblems upward, in an explicitly chosen order that guarantees dependencies are satisfied before they're needed; both are legitimate, standard DP IMPLEMENTATION STRATEGIES, not distinct paradigms. (B) is false and represents a fundamental misunderstanding; memoized recursion is not merely 'similar' to DP by coincidence &mdash; it IS one of the two standard, textbook-recognized ways of implementing dynamic programming. (C) is factually incorrect; PLENTY of DP algorithms are implemented via memoized recursion, which explicitly and necessarily uses recursion &mdash; DP is defined by the underlying algorithmic STRATEGY (exploiting optimal substructure/overlapping subproblems), not by whether the implementation happens to be iterative or recursive. (D) is an overgeneralization not supported by CLRS or general algorithmic practice; while top-down CAN sometimes save work by skipping genuinely unnecessary subproblems, bottom-up often has LOWER constant-factor overhead (no recursive call/stack management cost) and CLRS does not make a blanket claim that one is always strictly faster &mdash; the choice often depends on the specific problem and implementation context."
})

with open("/home/claude/mcq/dp_part_b.json", "w") as f:
    import json
    json.dump(Q, f)
print(len(Q))
