# -*- coding: utf-8 -*-
Q = []

Q.append({
"q": "In the Floyd-Warshall algorithm, d<sub>ij</sub><sup>(k)</sup> is defined as the weight of a shortest path from i to j with all INTERMEDIATE vertices restricted to the set {1,2,...,k}. What is the base case d<sub>ij</sub><sup>(0)</sup>, and why?",
"opts": ["d<sub>ij</sub><sup>(0)</sup> = w<sub>ij</sub> (the direct edge weight, or &infin; if no edge exists), because with k=0 (no intermediate vertices allowed at all), a path from i to j can have AT MOST one edge &mdash; i.e., it must be the direct edge itself, if one exists", "d<sub>ij</sub><sup>(0)</sup> = 0 always, since k=0 means the path hasn't started yet", "d<sub>ij</sub><sup>(0)</sup> = &infin; always, since zero intermediate vertices means no path can possibly exist", "d<sub>ij</sub><sup>(0)</sup> is undefined and must be computed via the general recurrence even for k=0"],
"ans": 0,
"exp": "As CLRS directly states, with k=0, a path from i to j whose intermediate vertices are restricted to the empty set {1,...,0}=&empty; has NO intermediate vertices at all, meaning it consists of AT MOST ONE EDGE &mdash; the direct edge from i to j; hence d<sub>ij</sub><sup>(0)</sup> = w<sub>ij</sub>, the direct edge weight (using the convention that w<sub>ij</sub>=&infin; if no direct edge exists, and w<sub>ii</sub>=0 for the trivial self-loop case). This base case is foundational to the entire recursive definition, serving as the starting point (k=0) before intermediate vertices 1,2,...,n are progressively allowed. (B) is factually wrong; setting all base-case distances to 0 would incorrectly claim every pair of vertices has zero distance regardless of actual edge weights, destroying the algorithm's correctness from the start. (C) is also wrong and overly pessimistic; DIRECT edges (paths with zero intermediate vertices) certainly CAN exist and should be captured, not universally treated as infinite/nonexistent. (D) is false; the base case is explicitly and directly defined by the direct edge weights, not derived from the general min-based recurrence (which specifically applies for k&ge;1)."
})

Q.append({
"q": "What is the Floyd-Warshall recurrence for d<sub>ij</sub><sup>(k)</sup> when k&ge;1, and what does each of the two terms inside the min() represent?",
"opts": ["d<sub>ij</sub><sup>(k)</sup> = min(d<sub>ij</sub><sup>(k&minus;1)</sup>, d<sub>ik</sub><sup>(k&minus;1)</sup> + d<sub>kj</sub><sup>(k&minus;1)</sup)); the first term represents NOT using vertex k as an intermediate vertex (reusing the best path found with only {1,...,k&minus;1} available), the second represents USING vertex k as an intermediate vertex (combining the best i-to-k and k-to-j paths, each restricted to {1,...,k&minus;1} as intermediates)", "d<sub>ij</sub><sup>(k)</sup> = d<sub>ik</sub><sup>(k)</sup> + d<sub>kj</sub><sup>(k)</sup> always, unconditionally using vertex k as an intermediate on every path", "d<sub>ij</sub><sup>(k)</sup> = max(d<sub>ij</sub><sup>(k&minus;1)</sup>, d<sub>ik</sub><sup>(k&minus;1)</sup>+d<sub>kj</sub><sup>(k&minus;1)</sup>), taking the MAXIMUM of the two options rather than minimum", "d<sub>ij</sub><sup>(k)</sup> = w<sub>ij</sub> unconditionally, ignoring all previously computed values entirely"],
"ans": 0,
"exp": "This is the CENTRAL recurrence of the Floyd-Warshall algorithm, directly grounded in the case analysis of whether vertex k IS or IS NOT an intermediate vertex of the true shortest path from i to j (restricted to intermediates in {1,...,k}): if k is NOT used, the shortest such path is exactly the shortest path with intermediates restricted to {1,...,k&minus;1}, giving d<sub>ij</sub><sup>(k&minus;1)</sup>; if k IS used, the path decomposes into a sub-path from i to k and a sub-path from k to j, each of which (crucially, by the optimal substructure argument) must ITSELF be a shortest path using only intermediates from {1,...,k&minus;1} (since k itself, appearing only once as the 'peak'/connector vertex in a SIMPLE path, cannot be an intermediate vertex of either sub-path), giving d<sub>ik</sub><sup>(k&minus;1)</sup>+d<sub>kj</sub><sup>(k&minus;1)</sup>; taking the MINIMUM of these two mutually exclusive cases correctly captures the true shortest path once vertex k becomes available as a potential intermediate. (B) incorrectly forces every path to use k, ignoring the case where NOT using k might be better, which is one of the two essential cases the recurrence must consider. (C) uses MAX instead of MIN, completely inverting the optimization goal (shortest PATHS require minimizing weight, not maximizing). (D) discards all recursive structure entirely, ignoring the whole point of building up the solution incrementally as k increases from 0 to n."
})

Q.append({
"q": "The bottom-up FLOYD-WARSHALL procedure computes D<sup>(k)</sup> matrices for k=1 to n using a TRIPLY NESTED loop (over k, then i, then j). Why must the OUTERMOST loop be over k specifically, rather than i or j?",
"opts": ["Because computing d<sub>ij</sub><sup>(k)</sup> for ANY pair (i,j) requires d<sub>ik</sub><sup>(k&minus;1)</sup> and d<sub>kj</sub><sup>(k&minus;1)</sup> to ALREADY be fully finalized from the PREVIOUS value of k; making k the outermost loop guarantees that the ENTIRE D<sup>(k&minus;1)</sup> matrix is complete before any D<sup>(k)</sup> entries are computed, correctly respecting this dependency across ALL (i,j) pairs simultaneously", "The loop order doesn't actually matter for correctness; any of the six possible orderings of i, j, k produces the same correct result", "k must be outermost purely for performance reasons (cache locality), with no correctness implications", "i must always be the outermost loop for any triply-nested dynamic programming algorithm, as a general rule"],
"ans": 0,
"exp": "This is a critical correctness requirement (and a very commonly tested 'trick' in Floyd-Warshall specifically, since many students ASSUME loop order doesn't matter, unlike simpler doubly-nested DP loops): computing d<sub>ij</sub><sup>(k)</sup> for any (i,j) pair fundamentally requires knowing d<sub>ik</sub><sup>(k&minus;1)</sup> and d<sub>kj</sub><sup>(k&minus;1)</sup> from the PREVIOUS iteration (k&minus;1) &mdash; and different (i,j) pairs may depend on DIFFERENT (ik) and (kj) entries, all of which must be from the SAME, fully-completed D<sup>(k&minus;1)</sup> matrix; making k the OUTERMOST loop ensures the entire D<sup>(k&minus;1)</sup> matrix (across ALL i,j pairs) is finalized before ANY D<sup>(k)</sup> computation begins, correctly respecting this global dependency; if i or j were outermost instead, you could end up using a MIX of already-updated D<sup>(k)</sup> values and not-yet-updated D<sup>(k&minus;1)</sup> values within the same 'k iteration,' which (perhaps surprisingly) doesn't actually break Floyd-Warshall's specific correctness due to a subtle mathematical property (using D<sup>(k)</sup> values 'early' for the SAME k can't make things WORSE, since d<sub>ik</sub><sup>(k)</sup>=d<sub>ik</sub><sup>(k&minus;1)</sup> and d<sub>kj</sub><sup>(k)</sup>=d<sub>kj</sub><sup>(k&minus;1)</sup> always hold, a special self-referential property unique to Floyd-Warshall) &mdash; BUT this is a delicate, algorithm-specific exception, and the STANDARD, textbook-safe, always-correct implementation strictly requires k as the outer loop precisely to avoid needing to reason through this subtlety. (B) is a dangerous oversimplification for an exam context; while Floyd-Warshall happens to have this specific tolerance for SOME reordering due to its unique self-referential property, this is NOT true in general for arbitrary triply-nested DP algorithms, and asserting 'any of the six orderings works' without the specific justification is not a safe, general claim to test. (C) understates the correctness implications; while cache locality IS a real secondary consideration, the PRIMARY and non-negotiable reason for k being outermost is the fundamental dependency-respecting correctness argument. (D) is a false, overly broad generalization with no general basis; the correct loop nesting order depends entirely on the SPECIFIC dependency structure of whatever particular DP recurrence is being implemented, not a universal rule about which variable position is always 'i'."
})

Q.append({
"q": "What is the time complexity of the Floyd-Warshall algorithm for a graph with n vertices, and how does this compare structurally to running Bellman-Ford from EVERY single vertex as an alternative all-pairs shortest-path approach?",
"opts": ["Floyd-Warshall: &Theta;(n&sup3;), from the triply-nested loop with O(1) work per innermost iteration; running Bellman-Ford (O(VE)=O(n&sup3;) for dense graphs) from every one of the n vertices gives O(n&middot;VE) = O(n&sup4;) for dense graphs, making Floyd-Warshall asymptotically BETTER for dense graphs specifically", "Floyd-Warshall is &Theta;(n&sup2;), always strictly faster than any Bellman-Ford-based approach regardless of graph density", "Floyd-Warshall is &Theta;(n&#8308;), making it always WORSE than running Bellman-Ford from every vertex", "Both approaches have identical &Theta;(n&sup3;) complexity in all cases, so the choice between them never matters"],
"ans": 0,
"exp": "As explicitly stated in CLRS, the Floyd-Warshall algorithm's triply-nested loop structure (over k, i, j, with O(1) work at line 6 per innermost iteration) directly gives &Theta;(n&sup3;) time; comparing this to running Bellman-Ford (itself O(VE) time, which for a DENSE graph with E=&Theta;(V&sup2;)=&Theta;(n&sup2;) edges becomes O(n&sup3;)) from EACH of the n vertices as sources gives a TOTAL of O(n)&times;O(n&sup3;)=O(n&#8308;) for dense graphs &mdash; making Floyd-Warshall's SINGLE &Theta;(n&sup3;) pass strictly more efficient than this alternative 'run single-source Bellman-Ford from everywhere' approach specifically for dense graphs, which is one of the key motivations CLRS gives for Floyd-Warshall's practical value (though for SPARSE graphs, running Dijkstra's, if weights permit, or a more carefully optimized approach from every vertex might actually be competitive with or better than Floyd-Warshall's fixed &Theta;(n&sup3;), since Dijkstra's with a good heap implementation can be much faster than O(n&sup3;) for sparse graphs). (B) drastically understates Floyd-Warshall's actual complexity; &Theta;(n&sup2;) would be WAY too fast for an ALL-PAIRS shortest path algorithm that needs to consider all n&sup2; pairs AND intermediate vertex possibilities. (C) incorrectly computes Floyd-Warshall's complexity as n&#8308; (that's the BELLMAN-FORD-FROM-EVERY-VERTEX alternative's complexity for dense graphs, not Floyd-Warshall's own complexity) and then draws the exact opposite (backwards) conclusion about which approach is better. (D) is false; the two approaches have DIFFERENT complexities as computed above (n&sup3; vs n&#8308; for dense graphs), directly contradicting the premise that they're 'identical in all cases.'"
})

Q.append({
"q": "Why does the Floyd-Warshall algorithm, as presented in CLRS, work correctly even in the presence of NEGATIVE-weight edges, but explicitly requires the ABSENCE of negative-weight CYCLES?",
"opts": ["The algorithm's correctness proof relies only on the existence of well-defined SHORTEST (simple) paths between vertex pairs, which negative EDGES alone don't prevent; but a negative-weight CYCLE would allow a 'path' to repeatedly loop through the cycle, decreasing total weight WITHOUT BOUND, making 'shortest path' UNDEFINED (no finite minimum exists) for any pair of vertices reachable via that cycle", "Negative-weight edges are actually NOT permitted by Floyd-Warshall at all; the algorithm requires strictly non-negative weights, identical to Dijkstra's requirement", "Negative-weight cycles are permitted as long as there are an EVEN number of negative edges within the cycle", "The algorithm handles negative cycles correctly by simply ignoring them and returning the best result found before encountering the cycle"],
"ans": 0,
"exp": "As explicitly noted in the CLRS text, Floyd-Warshall (like the related approach in Section 23.1) permits negative-weight EDGES, but explicitly assumes NO negative-weight CYCLES exist &mdash; the fundamental reason is that the notion of a 'SHORTEST PATH' is only well-defined if there's a finite minimum achievable weight; with a negative-weight cycle reachable from i and able to reach j, you could construct paths that traverse the cycle an ARBITRARY number of times, each traversal further DECREASING the total path weight without any lower bound, making the INFIMUM of possible path weights negative infinity &mdash; there is NO actual shortest (finite, simple) path in this scenario, and the entire mathematical framework of the algorithm (defined in terms of computing finite shortest-path weights) breaks down. Individual negative EDGES, by contrast, don't cause this issue as long as they don't form an exploitable cycle, since any SIMPLE path (visiting each vertex at most once) is finite in length and has a well-defined finite total weight regardless of individual edge signs. (B) is factually incorrect and conflates Floyd-Warshall's requirements with a DIFFERENT algorithm's (Dijkstra's) requirements; Floyd-Warshall (unlike Dijkstra's) explicitly CAN handle negative EDGES correctly, that's one of its notable strengths as a DP-based (rather than greedy-based) approach. (C) is a fabricated and mathematically nonsensical condition; the PARITY (even/odd count) of negative edges within a cycle has no bearing on whether the CYCLE ITSELF has negative total weight, which is the actual relevant condition, and even a single sufficiently negative edge combined with other edges can create a negative-weight cycle regardless of edge count parity. (D) is false; the STANDARD Floyd-Warshall algorithm does NOT automatically detect or gracefully handle negative cycles by 'ignoring' them &mdash; if negative cycles are present, the algorithm's output becomes MEANINGLESS/incorrect (potentially the diagonal entries d<sub>ii</sub> would go negative, which is a KNOWN post-hoc detection technique, but the algorithm doesn't 'ignore' the cycle during its normal execution)."
})

Q.append({
"q": "Post-hoc negative cycle DETECTION using Floyd-Warshall's output: after running the standard algorithm, how can you determine whether the input graph contained a negative-weight cycle, purely by examining the FINAL D<sup>(n)</sup> matrix?",
"opts": ["Check the DIAGONAL entries d<sub>ii</sub><sup>(n)</sup> for any i; if ANY diagonal entry is NEGATIVE (d<sub>ii</sub><sup>(n)</sup> &lt; 0), this indicates vertex i lies on a negative-weight cycle, since a legitimate shortest 'path' from a vertex to ITSELF (with no cycling) should have weight exactly 0, and a negative value can only arise if the algorithm found a way to 'return' to i via a net-negative-weight cycle", "Check if ANY off-diagonal entry equals exactly 0; this always indicates a negative cycle exists somewhere in the graph", "Negative cycles can never be detected from the OUTPUT matrix alone; a separate, completely different algorithm must be run from scratch", "Check if the matrix is symmetric; asymmetry in the final D matrix always indicates a negative cycle"],
"ans": 0,
"exp": "This is a well-known and elegant POST-HOC detection technique directly exploitable from Floyd-Warshall's own output structure: under NORMAL circumstances (no negative cycles), the shortest 'path' from any vertex i to ITSELF should have weight exactly 0 (the trivial empty path, doing nothing), so ALL diagonal entries d<sub>ii</sub><sup>(n)</sup> should equal 0 in a well-behaved graph; however, if a negative-weight cycle passing through vertex i exists, the algorithm (even though technically its underlying assumptions are violated) would still MECHANICALLY compute increasingly negative values by chaining through this exploitable cycle, resulting in d<sub>ii</sub><sup>(n)</sup> becoming NEGATIVE &mdash; so a simple O(n) post-processing scan of just the diagonal entries after running the standard O(n&sup3;) algorithm can definitively detect the PRESENCE of at least one negative cycle (though not necessarily pinpoint every affected vertex/cycle precisely without further work) with minimal additional computational cost. (B) is a fabricated and incorrect detection criterion; ZERO off-diagonal entries are entirely NORMAL and expected in many graphs (e.g., if there happen to be two DIFFERENT vertices with a genuinely zero-weight shortest path between them via some combination of positive and compensating negative edges, without ANY cycling issue at all) and have no reliable connection to negative cycle presence. (C) is false and unnecessarily pessimistic; this exact diagonal-checking technique IS a legitimate, efficient, well-known way to detect negative cycles using Floyd-Warshall's ALREADY-COMPUTED output, without needing an entirely separate algorithm (like Bellman-Ford's own negative-cycle detection mechanism, though that's an alternative valid approach for different scenarios). (D) is a fabricated and irrelevant criterion; matrix SYMMETRY relates to whether the underlying graph is UNDIRECTED (or has symmetric edge weights) versus DIRECTED with differing i-to-j and j-to-i weights &mdash; it has no direct, reliable connection to negative cycle detection."
})

Q.append({
"q": "For the TRANSITIVE CLOSURE computation via Floyd-Warshall-style DP (using boolean logical operations instead of arithmetic min/+), the recurrence is t<sub>ij</sub><sup>(k)</sup> = t<sub>ij</sub><sup>(k&minus;1)</sup> OR (t<sub>ik</sub><sup>(k&minus;1)</sup> AND t<sub>kj</sub><sup>(k&minus;1)</sup>). What is the PRECISE structural correspondence between this and the standard Floyd-Warshall recurrence?",
"opts": ["OR directly replaces MIN (both select the 'better'/broader of two options: minimum weight, or logical truth if EITHER path-existence option holds), and AND directly replaces + (both COMBINE two sub-results into a single joint result: summing weights along a path, or requiring BOTH sub-paths to exist for the combined path to exist)", "The two recurrences are entirely unrelated; transitive closure requires a fundamentally different, unrelated algorithmic approach with no structural connection to shortest paths", "OR replaces +, and AND replaces MIN, which is the OPPOSITE (swapped) correspondence from the correct one", "Transitive closure cannot be computed via any Floyd-Warshall-style DP approach; it requires a completely different graph traversal method like repeated BFS/DFS from every vertex"],
"ans": 0,
"exp": "As CLRS explicitly derives, the transitive closure recurrence is STRUCTURALLY ISOMORPHIC to the shortest-path recurrence, with a precise algebraic correspondence: MIN (which selects the smaller/better of two WEIGHT options in the shortest-path context) corresponds to OR (which selects TRUE if EITHER of two path-existence options holds, capturing 'is there SOME way to get from i to j, either without using k or by using k'); and + (which COMBINES two path segments' weights by SUMMING them) corresponds to AND (which combines two path-existence facts by requiring BOTH the i-to-k AND k-to-j sub-paths to exist for the combined i-to-k-to-j path to exist) &mdash; this beautiful correspondence (sometimes formalized via the mathematical concept of a SEMIRING, where different algebraic structures like (min,+) versus (OR,AND) can be plugged into the SAME underlying recursive algorithmic template) explains why the SAME O(n&sup3;) triply-nested-loop STRUCTURE directly solves both problems, just with different operators substituted in. (B) is false and misses this elegant, well-established, and pedagogically important structural connection that CLRS specifically highlights as a direct analogy. (C) describes the EXACT OPPOSITE (incorrectly swapped) correspondence from the genuinely correct one; MIN corresponds to OR (not AND), and + corresponds to AND (not MIN) &mdash; getting this backwards would produce a nonsensical, incorrect recurrence. (D) is factually wrong; the WHOLE POINT of CLRS's presentation of transitive closure immediately AFTER Floyd-Warshall is to demonstrate that the identical algorithmic template DOES directly apply, with only the algebraic operators changed, avoiding the need for a completely different approach."
})

Q.append({
"q": "What is the practical ADVANTAGE of the boolean-based TRANSITIVE-CLOSURE algorithm over simply running standard Floyd-Warshall with all edge weights set to 1 and checking if d<sub>ij</sub> &lt; n (as an alternative way to compute transitive closure)?",
"opts": ["The direct boolean approach can be more space- and potentially time-efficient in practice, since boolean (single-bit) values typically require less STORAGE than full integer/numeric weights, and on many computer architectures, logical operations (AND/OR) on single bits execute FASTER than arithmetic operations (addition, comparison) on full integer words", "There is no practical advantage whatsoever; both approaches always have identical performance characteristics in every conceivable implementation", "The boolean approach is asymptotically faster, achieving O(n&sup2;) instead of O(n&sup3;)", "The weight-based approach (setting weights to 1) is mathematically INCORRECT and doesn't actually compute transitive closure at all, making the boolean approach the only valid option"],
"ans": 0,
"exp": "As CLRS explicitly notes, while BOTH approaches achieve the same asymptotic &Theta;(n&sup3;) time complexity, the DIRECT boolean-based transitive closure algorithm offers PRACTICAL (constant-factor) advantages: since it uses only BOOLEAN values (existence/non-existence of a path) rather than full numeric weights, its SPACE requirement is smaller by a factor corresponding to the size of a machine word (e.g., using 1 bit per entry instead of 32 or 64 bits for a full integer), and on many computer architectures, LOGICAL operations (bitwise AND/OR) on single-bit values can execute FASTER than ARITHMETIC operations (addition, comparison) on full-width integers &mdash; making the direct boolean approach a genuinely useful practical optimization even though it doesn't change the asymptotic complexity CLASS. (B) is false; while asymptotically IDENTICAL, there ARE meaningful practical (constant-factor) differences in space usage and potentially execution speed, as explicitly discussed in the textbook. (C) is factually incorrect; BOTH the boolean transitive-closure algorithm and the weight-based Floyd-Warshall-with-unit-weights approach share the SAME &Theta;(n&sup3;) asymptotic time complexity &mdash; there's no achievable O(n&sup2;) speedup being described here. (D) is false; setting all edge weights to 1 and checking d<sub>ij</sub>&lt;n IS a mathematically VALID (if less elegant/efficient in practice) way to compute transitive closure, as CLRS itself explicitly describes as 'one way' to solve this problem &mdash; it's not incorrect, just potentially less practically efficient than the direct boolean approach."
})

Q.append({
"q": "In the predecessor matrix &Pi; construction for Floyd-Warshall (used to reconstruct actual shortest PATHS, not just their weights), the recurrence for &pi;<sub>ij</sub><sup>(k)</sup> when k&ge;1 depends on comparing d<sub>ij</sub><sup>(k&minus;1)</sup> to d<sub>ik</sub><sup>(k&minus;1)</sup>+d<sub>kj</sub><sup>(k&minus;1)</sup>. What does &pi;<sub>ij</sub><sup>(k)</sup> represent, and how is it updated in each of the two cases?",
"opts": ["&pi;<sub>ij</sub><sup>(k)</sup> is the PREDECESSOR of vertex j on a shortest path from i, restricted to intermediates in {1,...,k}; if k IS used as an intermediate (i.e., d<sub>ij</sub><sup>(k&minus;1)</sup> &gt; d<sub>ik</sub><sup>(k&minus;1)</sup>+d<sub>kj</sub><sup>(k&minus;1)</sup>), then &pi;<sub>ij</sub><sup>(k)</sup> = &pi;<sub>kj</sub><sup>(k&minus;1)</sup> (inheriting the predecessor from the k-to-j sub-path, since j's immediate predecessor on the FULL path is the same as its predecessor on just the final leg from k to j); otherwise, &pi;<sub>ij</sub><sup>(k)</sup> = &pi;<sub>ij</sub><sup>(k&minus;1)</sup> (predecessor unchanged, since the best path doesn't route through k)", "&pi;<sub>ij</sub><sup>(k)</sup> always equals k directly, regardless of whether k actually lies on the optimal path", "&pi;<sub>ij</sub><sup>(k)</sup> represents the TOTAL NUMBER of edges in the shortest path, not an actual vertex reference", "&pi;<sub>ij</sub><sup>(k)</sup> is computed completely independently of the D matrix, using an entirely separate recurrence with no relationship to the distance computations"],
"ans": 0,
"exp": "This directly mirrors CLRS's precise formal definition (equation 23.8): &pi;<sub>ij</sub><sup>(k)</sup> tracks the PREDECESSOR of j (the vertex immediately before j) on the current best-known shortest path from i to j, restricted to intermediates in {1,...,k}; when vertex k becomes a BETTER intermediate choice (i.e., the path THROUGH k, with cost d<sub>ik</sub><sup>(k&minus;1)</sup>+d<sub>kj</sub><sup>(k&minus;1)</sup>, is STRICTLY better than the previous best d<sub>ij</sub><sup>(k&minus;1)</sup>), the predecessor of j on this NEW, improved path is INHERITED from the k-to-j SUB-PATH specifically (since the overall path is now i&rarr;...&rarr;k&rarr;...&rarr;j, and j's IMMEDIATE predecessor is determined entirely by how the k-to-j portion reaches j, which is exactly &pi;<sub>kj</sub><sup>(k&minus;1)</sup>); when k is NOT a better choice, the predecessor simply CARRIES OVER unchanged from the previous iteration (&pi;<sub>ij</sub><sup>(k&minus;1)</sup>), since the best path itself hasn't changed. This precise predecessor-tracking mechanism allows full path RECONSTRUCTION (not just weight computation) by following predecessor pointers backward from j to i after the algorithm completes. (B) is factually wrong; &pi;<sub>ij</sub><sup>(k)</sup> represents the predecessor of J specifically (the vertex whose predecessor we're tracking), NOT simply k itself &mdash; k is only relevant as an intermediate 'connector' vertex, and the true predecessor of j could be some vertex much closer to j along the k-to-j sub-path, not necessarily k directly (unless j happens to be immediately adjacent to k on that sub-path). (C) misunderstands the entire PURPOSE of the predecessor matrix; it explicitly represents VERTEX REFERENCES for path RECONSTRUCTION, not edge counts. (D) is false; the &pi; recurrence is DIRECTLY and INTIMATELY tied to the D matrix's own computations (comparing d<sub>ij</sub><sup>(k&minus;1)</sup> to d<sub>ik</sub><sup>(k&minus;1)</sup>+d<sub>kj</sub><sup>(k&minus;1)</sup> is EXACTLY the same comparison driving the D matrix's own update decision), not an independent, unrelated computation."
})

Q.append({
"q": "Given the base case &pi;<sub>ij</sub><sup>(0)</sup> = NIL if i=j or w<sub>ij</sub>=&infin;, and &pi;<sub>ij</sub><sup>(0)</sup> = i if i&ne;j and w<sub>ij</sub>&lt;&infin;, what is the intuition behind these TWO distinct sub-cases?",
"opts": ["If i=j (trivial self-path) or there's NO direct edge (w<sub>ij</sub>=&infin;), there's no meaningful predecessor to record, so NIL correctly signals 'no path/predecessor exists at this base level'; if a DIRECT edge from i to j exists (i&ne;j and w<sub>ij</sub>&lt;&infin;), then the immediate predecessor of j on this single-edge path is simply i itself (the path is just the one edge i&rarr;j, so j's predecessor is trivially i)", "Both cases are set to NIL universally, since predecessors are always only defined for k&ge;1, never for the base case k=0", "The value i (in the second case) is a labeling ERROR and should actually be j, referring to the destination vertex instead of the source", "These base cases are entirely arbitrary/placeholder values with no real semantic meaning, used only to prevent runtime errors during table initialization"],
"ans": 0,
"exp": "These base cases directly and sensibly reflect the SIMPLEST possible path scenarios at k=0 (no intermediates allowed): when i=j, there's no meaningful 'path' to speak of (a vertex trivially 'reaches' itself with zero edges), so there's no predecessor to record, hence NIL; when w<sub>ij</sub>=&infin; (no direct edge exists between DISTINCT i and j), there's similarly NO valid path at all at this base level, so again NIL correctly indicates 'undefined/no path'; but when a genuine DIRECT edge exists (i&ne;j specifically, AND w<sub>ij</sub> is finite), the path consists of EXACTLY that single edge i&rarr;j, and by the very definition of 'predecessor of j on this path,' the vertex immediately preceding j is i itself (there's nothing else on this minimal one-edge path) &mdash; hence &pi;<sub>ij</sub><sup>(0)</sup>=i correctly captures this. (B) is factually wrong; the predecessor matrix IS meaningfully defined even at the base case k=0, as explicitly shown by the two distinct sub-cases given in the question itself &mdash; NIL is not universal across both sub-cases. (C) is incorrect; setting the value to i (the SOURCE vertex) is precisely correct for representing 'the predecessor of j is i' when the path is the single direct edge i&rarr;j &mdash; using j instead would nonsensically claim j is its own predecessor, which is logically wrong. (D) is a serious misunderstanding; these values are NOT arbitrary placeholders but carry precise, meaningful semantic content directly derived from the definition of what a 'predecessor' represents at the simplest possible path length (zero or one edges)."
})

Q.append({
"q": "Consider tracing Floyd-Warshall by hand on a SPECIFIC small graph: vertices {1,2,3}, edges with weights w&#8321;&#8322;=3, w&#8322;&#8323;=&minus;2, w&#8323;&#8321;=2, and all other non-diagonal entries &infin; (no direct edge), diagonal entries 0. After the k=1 iteration (allowing vertex 1 as an intermediate), does d<sub>23</sub><sup>(1)</sup> change from its base value d<sub>23</sub><sup>(0)</sup>?",
"opts": ["No, d<sub>23</sub><sup>(1)</sup> remains &minus;2 (unchanged from d<sub>23</sub><sup>(0)</sup>=&minus;2, the direct edge weight), because checking the alternative path 2&rarr;1&rarr;3 would require d<sub>21</sub><sup>(0)</sup>+d<sub>13</sub><sup>(0)</sup>, and d<sub>21</sub><sup>(0)</sup>=&infin; (no direct edge from 2 to 1 exists in this graph), so this alternative path is not viable, leaving the direct edge as the best (and only) option", "Yes, d<sub>23</sub><sup>(1)</sup> becomes 5, by incorrectly using w&#8321;&#8322;+w&#8323;&#8321; instead of properly checking the path THROUGH vertex 1 in the correct direction (2 to 1, then 1 to 3)", "Yes, d<sub>23</sub><sup>(1)</sup> becomes 0, by incorrectly assuming all shortest paths must eventually reduce to 0 after passing through any intermediate vertex", "This cannot be determined without additional information about the graph beyond what's given"],
"ans": 0,
"exp": "Let's carefully trace this: d<sub>23</sub><sup>(0)</sup>=w&#8322;&#8323;=&minus;2 (the given direct edge). Checking whether vertex 1 improves this at k=1: the recurrence requires comparing d<sub>23</sub><sup>(0)</sup> against d<sub>21</sub><sup>(0)</sup>+d<sub>13</sub><sup>(0)</sup> (the potential path 2&rarr;1&rarr;3, using vertex 1 as the intermediate connector) &mdash; critically, d<sub>21</sub><sup>(0)</sup> represents the DIRECT edge weight from vertex 2 TO vertex 1 specifically (respecting DIRECTIONALITY, since this is presumably a DIRECTED graph, as is standard for Floyd-Warshall problems), and based on the given edges (only w&#8321;&#8322;, w&#8322;&#8323;, w&#8323;&#8321; are specified as finite; there's no mention of an edge FROM 2 TO 1), d<sub>21</sub><sup>(0)</sup>=&infin;, making the alternative path's cost &infin;+d<sub>13</sub><sup>(0)</sup>=&infin; (regardless of d<sub>13</sub><sup>(0)</sup>'s specific value), which is certainly NOT better than the existing d<sub>23</sub><sup>(0)</sup>=&minus;2 &mdash; so d<sub>23</sub><sup>(1)</sup> correctly remains &minus;2, UNCHANGED from the base case. (B) makes a critical DIRECTIONALITY error, incorrectly using w&#8321;&#8322; (the edge FROM 1 TO 2) instead of correctly checking for an edge FROM 2 TO 1 (which doesn't exist in this specific graph) &mdash; a very common student mistake when working with DIRECTED graphs, where edge direction matters critically and A&rarr;B does NOT imply B&rarr;A exists or has the same weight. (C) reflects a fundamental misunderstanding of the recurrence; there's no rule stating shortest paths 'reduce to 0' after passing through intermediates &mdash; path weights are determined by SUMMING actual edge weights along the path, not some arbitrary reset-to-zero convention. (D) is incorrect; the given information (the three specific edge weights, with the explicit statement that all OTHER entries are &infin;) IS fully sufficient to definitively trace through this specific step of the algorithm."
})

Q.append({
"q": "For the same graph as the previous question (vertices {1,2,3}, w&#8321;&#8322;=3, w&#8322;&#8323;=&minus;2, w&#8323;&#8321;=2), what is d<sub>12</sub><sup>(3)</sup> (the final shortest distance from vertex 1 to vertex 2, using ALL vertices as potential intermediates)?",
"opts": ["3, unchanged from the direct edge d<sub>12</sub><sup>(0)</sup>=3, since NO alternative path from 1 to 2 (via 3 as an intermediate, i.e., 1&rarr;3&rarr;2, requiring an edge FROM 3 TO 2, which is not given/is &infin;) provides an improvement", "1, computed incorrectly by summing all three given edge weights and dividing by 3", "0, since the algorithm always eventually converges all distances to 0 once every vertex is used as an intermediate", "&minus;2, incorrectly using the value of w&#8322;&#8323; (a completely different edge) instead of correctly computing d<sub>12</sub>"],
"ans": 0,
"exp": "Tracing carefully: d<sub>12</sub><sup>(0)</sup>=w&#8321;&#8322;=3 (the given direct edge). At k=1 (using vertex 1 as intermediate): checking d<sub>11</sub><sup>(0)</sup>+d<sub>12</sub><sup>(0)</sup>=0+3=3, no improvement (this check is actually somewhat trivial/redundant when k=i, but doesn't cause incorrect results). At k=2: checking d<sub>12</sub><sup>(1)</sup> vs d<sub>12</sub><sup>(1)</sup>... (using vertex 2 as an intermediate to improve i=1,j=2 doesn't make sense since j=2=k here, another trivial/non-improving case). At k=3 (using vertex 3 as intermediate): checking d<sub>12</sub><sup>(2)</sup>=3 against d<sub>13</sub><sup>(2)</sup>+d<sub>32</sub><sup>(2)</sup> &mdash; we'd need to know d<sub>32</sub><sup>(2)</sup> (edge/path FROM 3 TO 2), but the given edges are w&#8321;&#8322;=3, w&#8322;&#8323;=&minus;2 (2 TO 3), and w&#8323;&#8321;=2 (3 TO 1) &mdash; there is NO specified edge FROM 3 TO 2 directly, and no INDIRECT path from 3 to 2 either (3's only outgoing edge goes to 1, and 1's only outgoing edge goes to 2, so 3&rarr;1&rarr;2 IS actually a valid path with weight w&#8323;&#8321;+w&#8321;&#8322;=2+3=5, meaning d<sub>32</sub> is actually 5, not &infin;) &mdash; but checking d<sub>13</sub><sup>(2)</sup>+d<sub>32</sub><sup>(2)</sup>: we need d<sub>13</sub><sup>(2)</sup> too (is there a path from 1 to 3? Only via 1&rarr;2&rarr;3, weight 3+(&minus;2)=1), so d<sub>13</sub><sup>(2)</sup>=1, giving d<sub>13</sub><sup>(2)</sup>+d<sub>32</sub><sup>(2)</sup>=1+5=6, which is WORSE than the existing d<sub>12</sub><sup>(2)</sup>=3, so NO improvement occurs, and the final d<sub>12</sub><sup>(3)</sup> remains 3. (B), (C), and (D) all represent various computational/conceptual errors (incorrect averaging, a false convergence-to-zero belief, and directly substituting an unrelated edge's weight) with no grounding in the actual recurrence-based computation traced above."
})

Q.append({
"q": "What is the SPACE complexity of the STRAIGHTFORWARD Floyd-Warshall implementation that explicitly stores ALL n+1 matrices D<sup>(0)</sup>, D<sup>(1)</sup>, ..., D<sup>(n)</sup> (as literally described by the superscripted recurrence), and how can this be reduced?",
"opts": ["&Theta;(n&sup3;) space for storing all n+1 separate n&times;n matrices; this can be reduced to &Theta;(n&sup2;) by OBSERVING that the recurrence for d<sub>ij</sub><sup>(k)</sup> only ever needs values from the IMMEDIATELY PRECEDING matrix D<sup>(k&minus;1)</sup>, so a SINGLE matrix can be reused/overwritten in place (dropping the superscripts entirely) across iterations, as explicitly discussed in a CLRS exercise (23.2-4)", "The space complexity is always exactly &Theta;(n&sup2;), with no possibility of using more space even in a naive implementation, since matrices are inherently n&times;n regardless of implementation choice", "Space complexity cannot be reduced below &Theta;(n&sup3;) under any circumstances, since all n+1 matrices are mathematically necessary and cannot be discarded", "The space complexity is &Theta;(1), since Floyd-Warshall only tracks a single running total, not any matrices"],
"ans": 0,
"exp": "As explicitly given in CLRS Exercise 23.2-4 (directly referenced in the source material), the STRAIGHTFORWARD reading of the recurrence (with explicit superscripts d<sub>ij</sub><sup>(k)</sup> for k=0,1,...,n) suggests needing &Theta;(n&sup3;) space to store ALL n+1 separate matrices &mdash; but the exercise specifically asks students to show that the simplified procedure FLOYD-WARSHALL', which 'simply DROPS all the superscripts' (i.e., uses a SINGLE matrix D that gets overwritten/updated IN PLACE across iterations, rather than maintaining n+1 distinct matrices), is STILL CORRECT, requiring only &Theta;(n&sup2;) space; this works because, crucially, when computing the update for d<sub>ij</sub> at iteration k, even though you're technically supposed to use ONLY values from D<sup>(k&minus;1)</sup>, the specific structure of the recurrence means that using the 'new' (already-updated-this-iteration) values for d<sub>ik</sub> and d<sub>kj</sub> specifically doesn't cause incorrect results, since d<sub>ik</sub><sup>(k)</sup>=d<sub>ik</sub><sup>(k&minus;1)</sup> and d<sub>kj</sub><sup>(k)</sup>=d<sub>kj</sub><sup>(k&minus;1)</sup> ALWAYS hold (updating row/column k using vertex k itself as an intermediate never actually CHANGES those specific values, a special self-referential mathematical property unique to this exact recurrence structure) &mdash; making the space-efficient single-matrix implementation both CORRECT and the STANDARD, practically-used version of the algorithm. (B) is false; a NAIVE, literal implementation storing ALL matrices explicitly WOULD indeed require &Theta;(n&sup3;) space, and recognizing this reducibility to &Theta;(n&sup2;) is precisely the valuable insight this question tests, not an assumption that space is 'always' minimal. (C) is factually incorrect and directly contradicts the well-established, standard optimization explicitly discussed in CLRS itself (Exercise 23.2-4). (D) drastically understates the necessary space; Floyd-Warshall fundamentally needs to track PAIRWISE distances between ALL vertex pairs, requiring at least &Theta;(n&sup2;) space for this information, not merely a single running total."
})

Q.append({
"q": "A buggy implementation of Floyd-Warshall INITIALIZES the diagonal entries d<sub>ii</sub> to &infin; instead of the CORRECT value of 0. What is the most likely CONSEQUENCE of this bug on the algorithm's final output?",
"opts": ["The algorithm may incorrectly compute LONGER (or entirely incorrect/infinite) shortest paths for various vertex pairs, since paths that legitimately should be able to 'pass through' a vertex back to a point that connects back to itself (weight 0 contribution) would instead be treated as requiring an INFINITE-cost detour, potentially causing valid, genuinely shorter paths to be missed or miscalculated during the min() comparisons throughout the algorithm's execution", "This bug has absolutely no effect on the algorithm's correctness, since diagonal entries are never actually used or referenced during the computation", "The algorithm will crash immediately with a division-by-zero-style error due to the infinite diagonal values", "This bug only affects the SPACE complexity of the algorithm, not the correctness of the computed distances"],
"ans": 0,
"exp": "This is a subtle but genuinely impactful correctness bug: the diagonal entries d<sub>ii</sub> (representing the trivial 'distance from a vertex to itself') are used throughout the algorithm's min() comparisons whenever i=k or j=k in various sub-computations (e.g., when k happens to equal i or j during certain iterations, the recurrence implicitly references d<sub>ii</sub> or d<sub>jj</sub>-style entries as part of the broader computation) &mdash; incorrectly setting these to &infin; instead of the mathematically correct 0 could cause the algorithm to WRONGLY REJECT or fail to properly consider certain valid path combinations that legitimately rely on this zero-cost self-loop baseline, potentially leading to INCORRECT (too large, or even erroneously infinite) final shortest-path distances for various vertex pairs, since the min() operations throughout the algorithm would be comparing against artificially inflated (infinite) diagonal values instead of the correct zero baseline in relevant sub-computations. (B) is factually wrong; while the diagonal entries might seem 'trivial' at first glance, they DO play a genuine role in the broader matrix computation's correctness, particularly in edge cases and specific intermediate calculations throughout the n&sup3; triply-nested loop structure. (C) is incorrect; using &infin; as a value (assuming it's represented as, e.g., a very large sentinel number or a proper infinity representation in the specific programming language/environment) doesn't inherently cause a division-by-zero or crash-style error &mdash; Floyd-Warshall's core operations are addition, comparison, and min-selection, none of which inherently require division. (D) is false; this is fundamentally a CORRECTNESS bug affecting the computed VALUES in the distance matrix, not merely a space/memory-related issue &mdash; the bug doesn't change how much memory is used, it changes what VALUES end up stored there."
})

Q.append({
"q": "Consider a DENSE graph (E close to V&sup2;) versus a SPARSE graph (E close to V) for the ALL-PAIRS shortest path problem. Why does Floyd-Warshall's FIXED &Theta;(n&sup3;) complexity make it PARTICULARLY well-suited (relatively speaking) for DENSE graphs specifically, compared to running Dijkstra's from every vertex?",
"opts": ["Running Dijkstra's (with a Fibonacci heap) from every vertex gives O(V&sup2;logV + VE) total time; for a DENSE graph where E approaches V&sup2;, this becomes O(V&sup3;), essentially MATCHING Floyd-Warshall's complexity (making Floyd-Warshall's simplicity and ability to handle negative edges an attractive, comparably-efficient choice), whereas for a SPARSE graph where E is much smaller (closer to V), the Dijkstra-from-every-vertex approach becomes substantially FASTER than Floyd-Warshall's FIXED n&sup3; bound, which doesn't improve/adapt based on sparsity", "Floyd-Warshall is ALWAYS faster than any Dijkstra-based approach, regardless of graph density, making this comparison moot", "Dijkstra's algorithm cannot be run multiple times from different sources under any circumstances, making this comparison technically invalid", "Floyd-Warshall's complexity actually DECREASES for dense graphs specifically, unlike its complexity for sparse graphs"],
"ans": 0,
"exp": "This reflects an important PRACTICAL/comparative complexity consideration frequently tested in courses covering all-pairs shortest paths: Dijkstra's algorithm (with an efficient Fibonacci-heap-based priority queue implementation) runs in O(VlogV+E) per single-source execution; running it from ALL V vertices gives O(V&sup2;logV+VE) total &mdash; for a DENSE graph (E&asymp;V&sup2;), this becomes O(V&sup2;logV+V&sup3;)&asymp;O(V&sup3;) (since the V&sup3; term dominates for large V), essentially MATCHING Floyd-Warshall's fixed O(V&sup3;) bound, meaning Floyd-Warshall's algorithmic SIMPLICITY (no complex heap data structure needed) and its ADDITIONAL capability of correctly handling NEGATIVE edge weights (which Dijkstra's fundamentally CANNOT do) make it an attractive, comparably-efficient choice for dense graphs specifically; but for a SPARSE graph (E much smaller, e.g., E=&Theta;(V)), the Dijkstra-based approach's complexity DROPS substantially (closer to O(V&sup2;logV), much better than O(V&sup3;)), making it the CLEARLY SUPERIOR choice for sparse graphs, SPECIFICALLY BECAUSE Floyd-Warshall's complexity remains FIXED at &Theta;(n&sup3;) regardless of how sparse the actual graph is (it doesn't 'adapt' or improve for sparse inputs, unlike Dijkstra's-based approaches whose complexity DIRECTLY depends on E). (B) is false and directly contradicts the nuanced density-dependent tradeoff being tested; Floyd-Warshall is NOT universally faster &mdash; for sparse graphs specifically, Dijkstra-based approaches become substantially better. (C) is a fabricated and incorrect claim; running a single-source algorithm like Dijkstra's REPEATEDLY from every vertex as a source is a well-established, valid, and commonly-used technique for solving the ALL-PAIRS problem, explicitly discussed and compared against Floyd-Warshall in CLRS and virtually every algorithms course. (D) is factually incorrect; Floyd-Warshall's complexity is a FIXED &Theta;(n&sup3;) REGARDLESS of the actual number of edges E (dense or sparse) &mdash; it does not decrease for dense graphs; rather, dense graphs are exactly where its FIXED complexity happens to be COMPETITIVE with alternatives, not where its own complexity improves."
})

Q.append({
"q": "Which statement correctly explains why Floyd-Warshall is classified as a DYNAMIC PROGRAMMING algorithm specifically, connecting this classification to the recurrence's structure?",
"opts": ["Floyd-Warshall exhibits BOTH optimal substructure (a shortest path's SUB-PATHS, when decomposed at the highest-numbered intermediate vertex k, are themselves provably shortest paths using only smaller-numbered intermediates, as directly proven via the CLRS optimal-substructure argument) AND overlapping subproblems (the SAME d<sub>ik</sub><sup>(k&minus;1)</sup> and d<sub>kj</sub><sup>(k&minus;1)</sup> values get REUSED across MANY different (i,j) pairs at each iteration of k, making memoization/tabulation via the D matrix genuinely valuable rather than redundant recomputation)", "Floyd-Warshall is classified as DP purely by historical convention/naming tradition, with no actual structural justification connecting it to the formal DP criteria", "Floyd-Warshall is NOT actually a DP algorithm; it's more accurately classified as a GREEDY algorithm, similar to Dijkstra's", "Floyd-Warshall qualifies as DP solely because it uses a MATRIX data structure, and any matrix-based algorithm is automatically classified as DP"],
"ans": 0,
"exp": "Floyd-Warshall genuinely and structurally satisfies BOTH of the two defining DP criteria discussed extensively in the DP chapter: OPTIMAL SUBSTRUCTURE is directly established by the careful case-analysis proof (whether k is or isn't an intermediate vertex of the optimal path), showing that optimal solutions to the sub-paths (i-to-k and k-to-j, restricted to smaller intermediate sets) must themselves be optimal, precisely mirroring the general DP optimal-substructure pattern; OVERLAPPING SUBPROBLEMS is evident from the algorithm's very structure, since for a SPECIFIC value of k, the SAME values d<sub>ik</sub><sup>(k&minus;1)</sup> (for various j) and d<sub>kj</sub><sup>(k&minus;1)</sup> (for various i) get referenced REPEATEDLY across the n&sup2; different (i,j) pairs being updated at that iteration, making it genuinely valuable to have these values PRECOMPUTED and stored in the D matrix (rather than naively recomputed from scratch for each pair), directly matching the 'overlapping subproblems, worth caching' hallmark of DP. (B) is false and represents a serious misunderstanding of algorithmic classification; the DP label is NOT arbitrary/historical &mdash; it's grounded in genuine, provable structural properties (optimal substructure + overlapping subproblems) that Floyd-Warshall demonstrably satisfies. (C) is factually incorrect; Floyd-Warshall's ENTIRE algorithmic approach (building up the D matrix incrementally via k=1,2,...,n, comparing MULTIPLE possible options via min() at each step) is fundamentally DIFFERENT from Dijkstra's GREEDY, irrevocable-choice-based approach (finalizing one vertex's distance at a time, never reconsidering) &mdash; conflating these two fundamentally different algorithmic PARADIGMS is a significant conceptual error. (D) is a nonsensical, fabricated classification criterion; MANY algorithms use matrices for entirely different reasons (e.g., representing adjacency information) without being DP algorithms, and the mere PRESENCE of a matrix data structure has no bearing on whether an algorithm exhibits the actual defining DP properties."
})

Q.append({
"q": "For a graph where Floyd-Warshall is run and it's later discovered that a NEGATIVE-weight cycle exists (violating the algorithm's stated assumptions), what specifically happens to the computed d<sub>ij</sub> values for vertex pairs (i,j) where BOTH i and j can reach and be reached by that negative cycle?",
"opts": ["The computed distances for such pairs become MEANINGLESS/INCORRECT (the true 'shortest path' is undefined, being negative infinity in principle, since the cycle could be traversed arbitrarily many times), though the algorithm will still MECHANICALLY produce SOME finite numeric output (not necessarily an explicit error), which is WHY the post-hoc diagonal-checking technique is a valuable, necessary safeguard when negative edges are present and cycle-freedom isn't otherwise guaranteed", "The algorithm automatically detects the negative cycle DURING execution and immediately halts with a clear, explicit error message, requiring no additional post-processing", "The computed distances remain PERFECTLY CORRECT and meaningful even with negative cycles present, since Floyd-Warshall's min() operations inherently handle this case correctly with no special consideration needed", "Negative cycles only affect the PREDECESSOR matrix &Pi;, leaving the DISTANCE matrix D completely unaffected and reliably correct"],
"ans": 0,
"exp": "As established earlier, when a negative-weight cycle exists and is reachable from/can reach a given vertex pair (i,j), the TRUE 'shortest path weight' between i and j is mathematically UNDEFINED (there's no finite minimum, since traversing the cycle repeatedly drives the weight toward negative infinity) &mdash; but Floyd-Warshall, as a MECHANICAL, finite-iteration algorithm (running for exactly a fixed n iterations of k, without any explicit awareness of or special-casing for negative cycles during its core execution), will STILL produce SOME specific finite numeric value in d<sub>ij</sub> at the end (NOT an explicit error, infinity symbol, or crash) &mdash; this computed value is simply INCORRECT/MEANINGLESS relative to the true (undefined) shortest path, since the algorithm's underlying mathematical assumptions (no negative cycles) have been violated, even though it doesn't 'know' this internally and will happily proceed producing seemingly normal-looking output; this is PRECISELY why the earlier-discussed post-hoc diagonal-checking technique (looking for d<sub>ii</sub><sup>(n)</sup>&lt;0) serves as a valuable, NECESSARY safeguard specifically when negative edges are present and cycle-freedom cannot otherwise be guaranteed a priori. (B) is factually incorrect; the STANDARD Floyd-Warshall algorithm, as typically presented and implemented, does NOT include automatic negative-cycle detection/halting logic built into its core execution &mdash; it simply runs its fixed triply-nested loop structure regardless, which is precisely why the SEPARATE post-hoc check is needed as an additional safeguard. (C) is dangerously wrong and represents a fundamental misunderstanding of why the negative-cycle assumption matters in the first place; the computed values are NOT meaningful/correct when this assumption is violated, even though the algorithm doesn't inherently signal this issue during its normal execution. (D) is false; the negative cycle issue fundamentally corrupts the underlying DISTANCE values themselves (which is exactly what makes 'shortest path' undefined in the first place), and any predecessor-matrix issues would be a DOWNSTREAM consequence of this same fundamental problem, not an independent, isolated issue affecting only &Pi; while leaving D reliable."
})

Q.append({
"q": "A student claims: 'Floyd-Warshall can be trivially parallelized across the OUTER loop (over k) since each iteration is independent, just like the inner (i,j) loops can be parallelized.' Evaluate this specific claim about the OUTER (k) loop's parallelizability.",
"opts": ["This claim is FALSE; the outer k-loop iterations are FUNDAMENTALLY SEQUENTIAL (NOT independent), since computing D<sup>(k)</sup> REQUIRES the FULLY COMPLETED D<sup>(k&minus;1)</sup> matrix as input &mdash; you cannot correctly compute results for k=5 before k=4 is finished, unlike the INNER (i,j) pairs at a FIXED k, which genuinely CAN be computed independently/in parallel with each other since they only depend on the (already complete) PREVIOUS iteration's matrix, not on each other", "This claim is entirely TRUE; all n iterations of the k-loop can be run simultaneously on separate processors with no synchronization needed whatsoever", "Neither the k-loop NOR the inner (i,j) loops can EVER be parallelized in any implementation of Floyd-Warshall", "Parallelization of Floyd-Warshall is only theoretically possible but has never been practically implemented or studied in real systems"],
"ans": 0,
"exp": "This question specifically and importantly distinguishes between the parallelizability of the OUTER (k) loop versus the INNER (i,j) loops, a genuinely important structural/practical distinction: the OUTER k-loop iterations are STRICTLY SEQUENTIAL because D<sup>(k)</sup> is DEFINED IN TERMS OF the FULLY COMPLETED D<sup>(k&minus;1)</sup> matrix (every entry of D<sup>(k)</sup> potentially depends on ANY entry of D<sup>(k&minus;1)</sup>, via the d<sub>ik</sub><sup>(k&minus;1)</sup> and d<sub>kj</sub><sup>(k&minus;1)</sup> terms for VARYING i and j across the whole matrix) &mdash; you fundamentally CANNOT start computing k=5's matrix before k=4's matrix is ENTIRELY finished, since you don't know in advance which entries will be needed; HOWEVER, for a FIXED value of k, the INNER computation across DIFFERENT (i,j) pairs genuinely CAN be parallelized, since computing d<sub>ij</sub><sup>(k)</sup> for one specific (i,j) pair doesn't depend on the SIMULTANEOUSLY-being-computed d<sub>i'j'</sub><sup>(k)</sup> value for some OTHER (i',j') pair at the SAME k &mdash; each (i,j) pair's update at a fixed k only reads from the ALREADY-COMPLETE D<sup>(k&minus;1)</sup> matrix, making these inner updates INDEPENDENT of each other and genuinely parallelizable across multiple processors/threads, which is a well-established, practically-used parallelization strategy for Floyd-Warshall in real high-performance computing implementations. (B) is factually incorrect and reflects a serious misunderstanding of the OUTER loop's fundamental sequential dependency structure, directly contradicting the reasoning given above. (C) is also false; while the OUTER loop cannot be parallelized (as correctly explained), the INNER (i,j) loops absolutely CAN be, and this partial parallelizability is a genuinely valuable, well-studied property of Floyd-Warshall in practice. (D) is factually wrong; parallelized implementations of Floyd-Warshall (exploiting exactly the inner-loop independence described above) are well-documented, extensively studied, and PRACTICALLY IMPLEMENTED in real high-performance and GPU-based computing contexts, not merely theoretical curiosities."
})

Q.append({
"q": "What is the CORRECT way to interpret the claim 'Floyd-Warshall solves the SINGLE-PAIR shortest path problem as a special case,' and why is this generally considered a POOR practical choice despite being technically POSSIBLE?",
"opts": ["Technically, running FULL Floyd-Warshall and then simply extracting ONE specific d<sub>ij</sub> entry from the final matrix WOULD give the correct single-pair shortest-path answer, but this wastes an enormous amount of computation (&Theta;(n&sup3;) total work to answer just ONE query) compared to a dedicated single-source algorithm like Dijkstra's (O(E+VlogV) with a good heap) or even Bellman-Ford (O(VE)), both of which are specifically DESIGNED for this narrower single-source (or even more targeted single-PAIR) query and thus far more EFFICIENT when the ALL-PAIRS information isn't actually needed", "Floyd-Warshall CANNOT be used for single-pair queries under any circumstances; it strictly requires ALL pairs to be queried simultaneously as an inseparable batch operation", "Using Floyd-Warshall for a single-pair query is actually the MOST efficient approach in ALL cases, strictly better than any single-source alternative", "Single-pair shortest path queries are fundamentally UNSOLVABLE by any algorithm; only ALL-PAIRS problems have well-defined solutions"],
"ans": 0,
"exp": "This tests understanding of an important PRACTICAL EFFICIENCY consideration (choosing the RIGHT algorithm for the RIGHT problem SCOPE): while it's certainly TECHNICALLY TRUE that running the complete Floyd-Warshall algorithm and then simply LOOKING UP one specific d<sub>ij</sub> entry from the resulting matrix would give a mathematically CORRECT answer to a single-pair query, doing so involves computing the ENTIRE &Theta;(n&sup3;)-time, &Theta;(n&sup2;)-space ALL-PAIRS solution just to extract ONE piece of information from it &mdash; a substantial, unnecessary WASTE of computational resources when a dedicated, purpose-built algorithm like Dijkstra's (for non-negative weights, achieving O(E+VlogV) with an efficient priority queue) or Bellman-Ford (for graphs potentially containing negative edges, achieving O(VE)) could answer the SAME single-pair (or even single-SOURCE, to-all-destinations) query far more EFFICIENTLY, since these algorithms are specifically DESIGNED and OPTIMIZED for this narrower problem scope, without the overhead of computing distances for EVERY possible pair when only ONE (or a few) is actually needed. (B) is factually incorrect; there's no technical BARRIER preventing Floyd-Warshall from being used this way &mdash; it's simply INEFFICIENT, not IMPOSSIBLE, to do so. (C) is false and directly contradicts the well-established EFFICIENCY comparison; Floyd-Warshall is specifically LESS efficient for THIS narrower use case precisely because it computes far MORE information than actually needed for a single query. (D) is a nonsensical, false claim; single-pair shortest path problems are extremely WELL-STUDIED and have MULTIPLE well-established, efficient algorithmic solutions (Dijkstra's, Bellman-Ford, BFS for unweighted graphs, etc.), directly contradicting any claim that they're 'unsolvable.'"
})

Q.append({
"q": "Consider modifying Floyd-Warshall to find the shortest path with AT MOST K EDGES (not just any number of edges), for some fixed parameter K much smaller than n. Does the standard Floyd-Warshall recurrence, AS GIVEN, directly solve this MODIFIED problem, and why or why not?",
"opts": ["No, the standard recurrence does NOT directly solve this variant; the standard d<sub>ij</sub><sup>(k)</sup> tracks shortest paths based on which VERTICES are allowed as intermediates, NOT based on the NUMBER OF EDGES used, so a completely DIFFERENT DP formulation (typically tracking BOTH the destination AND the number of edges used so far as separate DP state dimensions, e.g., dp[edges][i][j]) would be needed to correctly enforce an edge-COUNT constraint", "Yes, the standard recurrence automatically and directly enforces an edge-count limit of exactly K by design, with K implicitly equal to n in the standard formulation", "This modified problem is mathematically equivalent to the original, unmodified problem in every case, requiring no changes to the recurrence whatsoever", "The standard algorithm can be trivially adapted by simply stopping the k-loop early after K iterations, which correctly and directly solves the edge-count-limited variant"],
"ans": 0,
"exp": "This question tests a subtle but important conceptual distinction: the STANDARD Floyd-Warshall recurrence's parameter k controls WHICH VERTICES are permitted as INTERMEDIATE vertices (progressively allowing MORE vertices as potential 'connectors' as k increases from 0 to n) &mdash; this is FUNDAMENTALLY DIFFERENT from constraining the NUMBER OF EDGES used in the path itself; a shortest path using intermediates restricted to {1,...,k} could still use ANY NUMBER of edges (potentially using ALL k+1 available vertices in a long chain, or just a single direct edge, depending on what's optimal) &mdash; there's NO direct connection between the k parameter (controlling vertex AVAILABILITY) and an edge-COUNT limit; to correctly solve the edge-count-limited variant, you'd need an ENTIRELY DIFFERENT DP formulation with a state space that EXPLICITLY tracks the number of edges used (e.g., a 3D DP table dp[m][i][j] = shortest path from i to j using AT MOST m edges, with a recurrence like dp[m][i][j]=min(dp[m&minus;1][i][j], min over intermediate vertex v of (dp[m&minus;1][i][v]+w<sub>vj</sub>)), which is a genuinely DIFFERENT algorithmic approach, closely related to certain formulations used in some versions of the Bellman-Ford algorithm's own iterative structure). (B) is factually incorrect; there's no such automatic correspondence between k (intermediate-vertex availability) and an edge-count limit &mdash; conflating these two entirely different DP state dimensions is a serious conceptual error. (C) is false; these are GENUINELY DIFFERENT problems (unrestricted-vertex shortest path vs. edge-count-limited shortest path) that can have DIFFERENT optimal answers for the SAME graph, depending on the specific value of K relative to the graph's structure. (D) is incorrect; simply STOPPING the k-loop early after K iterations does NOT correctly enforce an edge-count limit &mdash; it instead limits WHICH VERTICES may serve as intermediates (only vertices numbered 1 through K), which is a COMPLETELY DIFFERENT constraint from limiting the TOTAL NUMBER OF EDGES in the resulting path, and these two different restrictions generally produce DIFFERENT (not equivalent) results."
})

Q.append({
"q": "For a graph represented with adjacency MATRIX W where w<sub>ij</sub>=&infin; indicates 'no edge,' what happens during Floyd-Warshall's execution if a NAIVE IMPLEMENTATION uses a very large but FINITE sentinel value (e.g., INT_MAX in a language with fixed-width integers) to represent &infin;, WITHOUT any overflow-checking, when computing d<sub>ik</sub><sup>(k&minus;1)</sup>+d<sub>kj</sub><sup>(k&minus;1)</sup>?",
"opts": ["If BOTH d<sub>ik</sub><sup>(k&minus;1)</sup> and d<sub>kj</sub><sup>(k&minus;1)</sup> happen to be (or are close to) the large sentinel value simultaneously, their SUM can OVERFLOW the integer type's maximum representable value, WRAPPING AROUND to an unexpectedly SMALL (or even NEGATIVE) number, which could then be INCORRECTLY selected as the 'minimum' in the min() comparison, silently CORRUPTING the algorithm's output with a completely bogus, artificially-small distance value", "This scenario never actually occurs in practice, since Floyd-Warshall never adds two large sentinel values together under any circumstances", "Using a large finite sentinel value INSTEAD of true mathematical infinity is always PERFECTLY SAFE with no possible complications in any implementation", "The overflow, if it occurs, only affects the PREDECESSOR matrix, leaving the DISTANCE matrix completely unaffected"],
"ans": 0,
"exp": "This is a genuinely important, PRACTICAL implementation bug/consideration frequently tested regarding Floyd-Warshall (and shortest-path algorithms in general): when representing 'no edge/no path' using a large FINITE sentinel value (a common practical necessity in languages using fixed-width integer types, since a TRUE mathematical infinity isn't directly representable), you must be CAREFUL that ARITHMETIC operations (specifically, the ADDITION d<sub>ik</sub><sup>(k&minus;1)</sup>+d<sub>kj</sub><sup>(k&minus;1)</sup> in the recurrence) don't cause INTEGER OVERFLOW &mdash; if BOTH terms happen to be large sentinel values (representing 'currently unreachable' in BOTH sub-paths), their SUM could EXCEED the maximum representable integer value for the given data type, causing UNDEFINED BEHAVIOR or, in many common overflow-handling conventions, WRAPPING AROUND to a SMALL or even NEGATIVE number &mdash; which would then be INCORRECTLY interpreted as a 'very good' (small) distance by the subsequent min() comparison, potentially causing the algorithm to select this BOGUS, artificially-small value as if it were a genuine, valid shorter path, thereby SILENTLY CORRUPTING the algorithm's final output in a way that might not be immediately obvious without careful testing/debugging; the standard mitigation is to explicitly CHECK if either operand equals the sentinel infinity value BEFORE attempting the addition, and skip/avoid the addition entirely in that case (treating the sum as still 'infinity' rather than actually computing a numeric sum that risks overflow). (B) is factually incorrect; this scenario (both sub-path distances being 'infinity,' i.e., currently unreachable) is a COMMON, EXPECTED occurrence throughout the algorithm's early iterations, especially for SPARSE graphs or before enough intermediate vertices have been processed to establish connectivity between certain pairs. (C) is dangerously wrong and represents a failure to recognize a well-known, PRACTICALLY IMPORTANT implementation pitfall that real-world Floyd-Warshall implementations must explicitly guard against. (D) is incorrect; an overflow-corrupted DISTANCE value would directly and primarily corrupt the DISTANCE matrix D itself (since the overflow occurs during the distance CALCULATION), with any predecessor-matrix issues being, at most, a SECONDARY, downstream consequence of this same underlying distance-corruption problem, not an issue isolated to &Pi; alone."
})

Q.append({
"q": "Which of the following BEST describes the relationship between Floyd-Warshall's algorithm and the concept of MATRIX MULTIPLICATION over the (min,+) SEMIRING (sometimes called the 'min-plus' or 'tropical' semiring), as an alternative theoretical framing of the all-pairs shortest path problem?",
"opts": ["Computing D<sup>(n)</sup> can be conceptually framed as repeatedly 'multiplying' the weight matrix W by itself using MIN in place of standard addition's role and PLUS (+) in place of standard multiplication's role (i.e., (A&otimes;B)<sub>ij</sub> = min over k of (A<sub>ik</sub>+B<sub>kj</sub>), directly analogous to standard matrix multiplication's (AB)<sub>ij</sub> = sum over k of (A<sub>ik</sub>&times;B<sub>kj</sub>)); this reframing connects all-pairs shortest paths to FAST MATRIX MULTIPLICATION techniques, offering an ALTERNATIVE (though not identical in practical implementation) theoretical algorithmic approach distinct from Floyd-Warshall's specific triply-nested DP structure", "There is no meaningful mathematical connection between Floyd-Warshall and matrix multiplication concepts of any kind", "Floyd-Warshall IS literally, directly, standard matrix multiplication (using regular +,&times; operations) applied n times in sequence, with no special semiring reinterpretation needed", "The (min,+) semiring framing only applies to problems with strictly POSITIVE edge weights, making it entirely inapplicable whenever negative weights (as Floyd-Warshall explicitly permits) are present"],
"ans": 0,
"exp": "This is a genuinely elegant and mathematically rich alternative theoretical PERSPECTIVE on the all-pairs shortest path problem, connecting it to abstract algebra's SEMIRING concept: by defining a special 'multiplication-like' operation &otimes; where (A&otimes;B)<sub>ij</sub> = min<sub>k</sub>(A<sub>ik</sub>+B<sub>kj</sub>) (replacing STANDARD matrix multiplication's usual SUM-of-PRODUCTS with a MIN-of-SUMS structure), repeatedly applying this operation to the weight matrix W (specifically, computing W, then W&otimes;W, then (W&otimes;W)&otimes;W, and so on) EVENTUALLY converges to the all-pairs shortest-path distance matrix once enough 'multiplications' have been performed (specifically, after &lceil;log&#8322;n&rceil; repeated SQUARINGS, i.e., W&rarr;W&otimes;W&rarr;(W&otimes;W)&otimes;(W&otimes;W)&rarr;..., since each squaring DOUBLES the maximum PATH LENGTH being correctly accounted for) &mdash; this REPEATED-SQUARING approach can achieve O(n&sup3;logn) time using NAIVE min-plus matrix multiplication (SLIGHTLY worse than Floyd-Warshall's clean O(n&sup3;)), but theoretically opens the door to potentially FASTER algorithms if efficient min-plus matrix multiplication techniques (analogous to Strassen's algorithm for STANDARD matrix multiplication) can be developed, an ACTIVE area of ongoing algorithmic research; this connection is a valuable, sophisticated theoretical framing distinct from (though related in spirit to) Floyd-Warshall's own specific triply-nested-loop DP structure. (B) is false and dismisses a genuinely well-established, mathematically rich connection actively studied and discussed in advanced algorithms coursework and research literature. (C) is incorrect; Floyd-Warshall does NOT use STANDARD (+,&times;) matrix multiplication operations at all &mdash; it's the SPECIAL (min,+) SEMIRING reinterpretation that provides this alternative connection, not literal standard arithmetic matrix multiplication. (D) is a fabricated and false restriction; the (min,+) semiring framing works PERFECTLY WELL with NEGATIVE edge weights present (as long as no negative CYCLES exist, mirroring Floyd-Warshall's own stated requirement) &mdash; there's no inherent limitation to strictly positive weights in this theoretical framework."
})

Q.append({
"q": "In code-tracing terms: given a Floyd-Warshall implementation with a bug where the innermost update line is WRITTEN AS `d[i][j] = d[i][k] + d[k][j]` (an UNCONDITIONAL assignment, OMITTING the min() comparison against the existing d[i][j] entirely), what is the specific, predictable CONSEQUENCE of this bug?",
"opts": ["The algorithm will FORCE every single d[i][j] entry to be OVERWRITTEN by the (potentially much WORSE) path THROUGH vertex k, even when the EXISTING, previously-computed value (representing a path NOT using k) was ALREADY better/shorter; this systematically DISCARDS potentially-optimal existing solutions in favor of unconditionally routing through k, generally producing INCORRECT (too large, or nonsensical if involving unreachable/infinite sub-paths) final distances", "This bug has NO effect on correctness, since d[i][k]+d[k][j] always equals the CORRECT minimum in every case regardless of the min() comparison being omitted", "This specific bug causes an infinite loop, since the assignment creates a circular self-reference", "This bug only affects PERFORMANCE (making the algorithm slower), not the CORRECTNESS of the final computed distances"],
"ans": 0,
"exp": "This is a critical, very commonly tested implementation bug: OMITTING the min() comparison and UNCONDITIONALLY assigning d[i][j]=d[i][k]+d[k][j] means EVERY (i,j) pair gets FORCIBLY updated to route THROUGH vertex k, REGARDLESS of whether this is actually BENEFICIAL &mdash; if the EXISTING value of d[i][j] (representing the best path found so far, NOT necessarily using k) was ALREADY better (shorter) than the alternative path through k, this bug WRONGLY DISCARDS that better existing solution and REPLACES it with the (now KNOWN to be worse, by assumption) through-k alternative; additionally, if d[i][k] or d[k][j] happen to be INFINITY (representing 'currently unreachable' via the vertices considered SO FAR), this unconditional assignment could even PROPAGATE bogus infinite (or overflow-corrupted, per the earlier discussed overflow issue) values into d[i][j], further corrupting the computation; the CORRECT algorithm's min() comparison is NOT optional decorative syntax &mdash; it's the CENTRAL mechanism by which the algorithm correctly chooses between the 'don't use k' option (keeping the existing d[i][j]) and the 'DO use k' option (the new i-k-j path), and removing it fundamentally breaks the algorithm's core correctness guarantee. (B) is factually WRONG; there's no mathematical guarantee that d[i][k]+d[k][j] is ALWAYS the minimum/best option &mdash; that's PRECISELY the comparison the min() function is designed to correctly evaluate, and OFTEN the EXISTING d[i][j] (not routing through k) IS the better choice. (C) is incorrect; this bug doesn't create any LOOPING behavior (infinite or otherwise) &mdash; it's a straightforward (though INCORRECT) computational ASSIGNMENT that completes normally, just produces WRONG final results. (D) is false; this is UNAMBIGUOUSLY a CORRECTNESS bug (producing WRONG final shortest-path values), not merely a PERFORMANCE issue &mdash; the algorithm would still run in the same asymptotic TIME (Θ(n&sup3;)), just PRODUCE INCORRECT OUTPUT."
})

with open("/home/claude/mcq/fw_part_a.json", "w") as f:
    import json
    json.dump(Q, f)
print(len(Q))
